<?php $user_session_data = new Zend_Session_Namespace('kiosk_user_session_data'); ?>
<div id="page_title">Unenrollment</div>
<div class="three_column padding_top">
	<div class="content">
		<div id="slider">
			<ul class="enroll">
				<li>
					<div class="slider_title">Mazal Tov!</div>
					<div class="scroll-pane">
						<form>
						<div class="mainbox">
							<div class="col2_image"><IMG SRC='/file_view.php?id=3668045818' WIDTH='128' HEIGHT='128'  ALT='fatherson.png'></div>
							<div class="col2_text">You successfully unenrolled from the <?=$this->objCampaign->campaign_name?> Campaign...<br />
							</div>
							<div class="clear"></div>
						</div>
						</form>
					</div>
				</li>
			</ul>
		</div>
	</div>
</div>
