<?php include "config.phtml"; ?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
   "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title><?php print isset($title) ? $title : "Mashpia.com"; ?></title>
<link rel="stylesheet" type="text/css"	href="<?php echo $sn; ?>/css/front-end/admin/reset.css">
<link rel="stylesheet" type="text/css"	href="<?php echo $sn; ?>/css/front-end/admin/style.css">
<script type="text/javascript" src="<?php echo $sn; ?>/js/back-end/admin/jquery2.js"></script>
<script type="text/javascript" src="<?php echo $sn; ?>/js/back-end/admin/jquery-ui2.js"></script>
<script type="text/javascript" src="<?php echo $sn; ?>/js/back-end/admin/jquery.tools.js"></script>

<script type="text/javascript" src="<?php echo $sn; ?>/js/back-end/admin/jquery.validate.js"></script>
<script type="text/javascript" src="<?php echo $sn; ?>/js/mashpia_controller.js"></script>
<script type="text/javascript" src="<?php echo $sn; ?>/js/back-end/admin/jquery.dump.js"></script>
<script type="text/javascript" src="<?php echo $sn; ?>/js/back-end/admin/scripts.js"></script>
<script type="text/javascript" src="<?php echo $sn; ?>/js/back-end/admin/jquery.styleselect.js"></script>
<script type="text/javascript" src="<?php echo $sn; ?>/js/back-end/admin/jquery.editableText.js"></script>
<script type="text/javascript" src="<?php echo $sn; ?>/js/back-end/admin/jquery.jeditable.min.js"></script>