<?php
include "config.phtml";
include "parameters.phtml";
?>
<div class="slider">
	<div class="col_title">
		<span><?php print text($this->account_name . " Admin"); ?></span>
	</div>
	<div class="col_content">
		<div id="lists" class="module lists forms">
			<div class="module_content">
				<ul>
					<li>
						<?php print text("Browse the admin features for the " . $this->account_name . " system using the menu on the left."); ?>
					</li>
				</ul>
			</div>
		</div>
	</div>
</div>