<?php
	include "config.phtml";
	include "parameters.phtml";
?>
<script>
	$(function () {
		$(this).delay(1000).queue(function () {
			$(this).dequeue();
			$("#missioneditor input.datepicker").datepicker();
		});
		$('.slider:last form a.delete').click (function () {
			if (confirm("Warning: You are about to delete mission. This will erase any marking towards medals that users may have earned. It will also nullify any achievement card created for it.\n\nAre you sure you want to delete this mission?"))
				$.ajax({
					type : "POST",
					cache : false,
					start : $(".slider:last #processing_status").html('Loading...').fadeIn(),
					url : '<?php echo $sn . "/admin/missiondelete" . $strParamPath; ?>',
					dataType : "text",
					data : $('.slider:last form').serialize(),
					success : function(strResponse) {
						try {
							var arrResponse = jQuery.parseJSON(strResponse);
						} catch(e) {
							alert("<?php print text("Sorry, there was an error"); ?>: VA-ME101-2qwfgg");
							$.alert(strResponse);
							return;
						}
						if (typeof(arrResponse) != "object") {
							alert("<?php print text("Sorry, there was an error"); ?>: VA-ME102-sdfg43");
							$.alert(strResponse);
							return;
						} else {
							$(".slider:last #processing_status").fadeOut();
							if (arrResponse["error"]) {
								$(".slider:last #processing_status").html(arrResponse["error"]).fadeIn();
							} else if (arrResponse["success"] == "true") {
								$(".slider:last #processing_status").html("Mission deleted.").fadeIn("slow").queue(function () {
									$("#mainmenu_missions_a").trigger("click");
								});
							} else {
								alert("Unexpected error: VA-U105-11c12c");
								$.alert(arrResponse);
							}
						}
					}
				});
		});
		$('.slider:last .submit').click(function () {
			$('.slider:last form').submit();			
		});
		$('.slider:last form').submit( function(e) {
			e.preventDefault();
			$(".slider:last .processing_status").fadeOut();
			$.ajax({
				type : "POST",
				cache : false,
				start : $(".slider:last #processing_status").html('Loading...').fadeIn(),
				url : '<?php echo $sn . "/admin/missionedit" . $strParamPath; ?>',
				dataType : "text",
				data : $('.slider:last form').serialize(),
				success : function(strResponse) {
					try {
						var arrResponse = jQuery.parseJSON(strResponse);
					} catch(e) {
						alert("<?php print text("Sorry, there was an error"); ?>: VA-ME103-f3gdgd");
						$.alert(strResponse);
						return;
					}
					if (typeof(arrResponse) != "object") {
						alert("<?php print text("Sorry, there was an error"); ?>: VA-ME104-f32344");
						$.alert(strResponse);
						return;
					} else {
						$(".slider:last #processing_status").fadeOut();
						if (arrResponse["error"]) {
							if (typeof(arrResponse["error"]) != "object") {
								$(".slider:last #processing_status").html(arrResponse["error"]).fadeIn();
							} else {
								for (strField in arrResponse["error"])
								{
									//alert($.dump($(".slider:last #" + strField).closest("li").html()));return;
									$(".slider:last #" + strField).closest("li").next().html(arrResponse["error"][strField]).fadeIn();
								}
							}
						} else if (arrResponse["success"] == "true") {
							$(".slider:last #processing_status").html("Save successful. Reloading, please wait...").fadeIn("slow").delay(1000).fadeOut("slow").queue(function () {
								$(this).dequeue();
								if (arrResponse["new"]) {
									var strUrl = "<?php echo $sn . "/admin/missionedit/mission_id/\" + arrResponse[\"mission_id\"] + \"" . $strParamPath; ?>";
									slideRefresh(strUrl);
								}
							});
						} else {
							alert("Unexpected error: VA-ME103-n2fjk3");
							$.alert(arrResponse);
						}
					}
				}
			});
		});
		$(".slider:last .button").click(function (e) {
			e.preventDefault();
		});
	});
</script>
<div class="slider" id="missioneditor">
	<style>
		.processing_status {
			font-weight: bold;
			color: red;
		}
		.fix_select_boxes {
			border:1px solid #bbb;
			padding:6px;
			min-width:356px;
			border-radius:4px;
		}
	</style>
	<div class="col_title"><span>Mission Editor</span><div class="title_help info" title="Create new and modify existing missions to be used in the MissionsApp system."></div></div>

	<div class="col_content camper">
		<form>
			<div class="module form lists">
				<div class="module_content list">
					<ul>
						<?php include('uimods/uploadmessage.phtml'); ?>
						<li>
							<h3><?php print text("Mission Image"); ?></h3>
							<input type="hidden" name="mission_image_id" id="mission_image_id" value="<?php print @$this->objMission->image_id; ?>" />
							<iframe src="<?php print $sn . "/imgs/smalluploader/current_image/" . @$this->objMission->image_id; ?>/resultid/mission_image_id" width="100%" height="80" scrolling="no">
								<p><?php print text("Your browser does not support iframes."); ?></p>
							</iframe>
						</li>
						<div class="processing_status"></div>
						<li>
							<span class="label"><?php print text("Bar Code"); ?>:</span>
							<span class="input"><div style="padding:6px 0 0 0"><?php echo $this->objMission ? @$this->objMission->bar_code : "N/A"; ?></div></span>
							<div class="clear"></div>
						</li>
						<li>
							<span class="label"><?php print text("Network"); ?>:*</span>
							<span class="input">
								<select class="required fix_select_boxes" id="network" name="network">
<?php
	foreach ($this->arrNetworks as $objNetwork)
	{
?>
									<option <?php print $this->objCurrentNetwork->network_id == $objNetwork->network_id ? "selected" : ""; ?> value="<?php print $objNetwork->network_id; ?>"><?php print $objNetwork->network_name; ?></option>
<?php
	}
?>
								</select>
							</span>
							<div class="clear"></div>
						</li>
						<div class="processing_status"></div>
						<li>
							<span class="label"><?php print text("Holiday Name"); ?>:*</span>
							<span class="input"><input type="text" class="required" id="holiday_name" name="holiday_name" value="<?php echo @$this->objMission->holiday_name; ?>" size="25" minlength="2" /></span>
							<div class="clear"></div>
						</li>
						<div class="processing_status"></div>
						<li>
							<span class="label"><?php print text("Description"); ?>:*</span>
							<span class="input"><input type="text" class="required" id="description" name="description" value="<?php echo @$this->objMission->description; ?>" size="25" minlength="2" /></span>
							<div class="clear"></div>
						</li>
						<li>
							<span class="label"><?php print text("Badge"); ?>:</span>
							<span class="input"><input type="text" class="required" id="badge" name="badge" value="<?php echo @$this->objMission->badge; ?>" size="25" minlength="2" /></span>
							<div class="clear"></div>
						</li>
						<div class="processing_status"></div>
						<li>
							<span class="label"><?php print text("Date Label"); ?>:</span>
							<span class="input"><input type="text" class="required" id="date_label" name="date_label" value="<?php echo @$this->objMission->date_label; ?>" size="25" minlength="2" /></span>
							<div class="clear"></div>
						</li>
						<div class="processing_status"></div>
						<li>
							<span class="label"><?php print text("Start Date"); ?>:</span>
							<span class="input"><input style="width:140px" placeholder="mm/dd/yyyy" type="text" class="required datepicker hasDatepicker" id="start_date" name="start_date" value="<?php echo $this->objMission ? date("m/d/Y", $this->objMission->start_date) : ""; ?>" size="25" minlength="2" /> <input style="width:100px" placeholder="hh:mm" type="text" class="required" id="start_time" name="start_time" value="<?php echo $this->objMission ? date("H:i", $this->objMission->start_date) : ""; ?>" size="25" minlength="2" /></span>
							<div class="clear"></div>
						</li>
						<div class="processing_status"></div>
						<li>
							<span class="label"><?php print text("End Date"); ?>:</span>
							<span class="input"><input style="width:140px" placeholder="mm/dd/yyyy" type="text" class="required datepicker hasDatepicker" id="end_date" name="end_date" value="<?php echo $this->objMission ? date("m/d/Y", $this->objMission->end_date) : ""; ?>" size="25" minlength="2" /> <input style="width:100px" placeholder="hh:mm" type="text" class="required" id="end_time" name="end_time" value="<?php echo $this->objMission ? date("H:i", $this->objMission->end_date) : ""; ?>" size="25" minlength="2" /></span>
							<div class="clear"></div>
						</li>
						<li>
							<span class="label"><?php print text("Expired Date"); ?>:<div class="help_icon info" title="Only include users who were active in specific badges"></div></span>
							<span class="input"><input style="width:140px" placeholder="mm/dd/yyyy" type="text" class="required datepicker hasDatepicker" id="end_date" name="end_date" value="<?php echo $this->objMission ? date("m/d/Y", $this->objMission->end_date) : ""; ?>" size="25" minlength="2" /> <input style="width:100px" placeholder="hh:mm" type="text" class="required" id="end_time" name="end_time" value="<?php echo $this->objMission ? date("H:i", $this->objMission->end_date) : ""; ?>" size="25" minlength="2" /></span>
							<div class="clear"></div>
						</li>
						<div class="processing_status"></div>
<?php
						if ($this->objCurrentNetwork->network_id == 1)
						{
?>
							<input type="hidden" name="access_level" value="1" />
<?php
						}
						else
						{
?>
						<li>
							<span class="label"><?php print text("Access Level"); ?>:</span>
							<span class="input"><select class="fix_select_boxes" id="access_level" name="access_level">
								<option value="1" <?php print $this->objMission->access_level == 1 ? "selected" : ""; ?>>Once per student</option>
								<option value="2" <?php print $this->objMission->access_level == 2 ? "selected" : ""; ?>>Once per day per student</option>
							</select></span>
							<div class="clear"></div>
						</li>
						<div class="processing_status"></div>
<?php
						}
?>
						
						<div id="processing_status" style="padding:6px 6px 6px 10px; display:none"></div>
						<li>
							<span><a class="button submit save"><?php print text("Save"); ?></a></span>
<?php
	if (!empty($this->mission_id))
	{
?>
							<span><a style="float:right;" class="button delete"><?php print text("Delete"); ?></a></span>
<?php
	}
?>
							<div class="clear"></div>
						</li>
					</ul>
				</div>
			</div>
		</form>
	</div>
</div>