<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Print Achievement Cards</title>
        <style type="text/css">
		.cards {
			width:672px;
			page-break-after:always;
			font-family:'Myriad Pro',Arial,sans-serif;
			margin:-0.1875in auto 0;
		}
		.cards .row {
			display:table;
			margin:-0.1875in auto 0;
			margin-bottom: 8px;
		}
		.cards .card {
			width:3.5in;
			height:2in;
			text-align:center;

			width:306px;
			height:162px;
			padding:10px 15px 10px 15px;
			display:table-cell;
		}
		.cards .card .container {
			border:2px solid #000;
			border-radius:10px;
			-moz-border-radius:10px;
			height:100%;
		}

		.cards .logo {
			float:left;
			margin-left:30px;
		}
		.cards .institution {
			float:right;
			margin-right:30px;
		}
		.cards .logo img, .cards .institution img {
			margin:5px 0;
			width:55px;
			height:55px;
		}
		.cards .clear {
			clear:both;
		}

		.cards .title img {
			width:250px;
			height:34px;
		}

		.cards .campaign {
			/*clear:both;*/
			font-weight:bold;
			/*position:absolute;*/
			width:302px;
		}

		.cards .name {
			font-size:12px;
			margin:5px 10px 7px 10px;
			height:15px;
			line-height:10px;
			/*font-weight:bold;*/
		}

		.cards .barcode {
			font-size:10px;
		}

		.cards .points {
			font-size:12px;
			width:110px;
			height:29px;
			text-align:center;
			font-weight:bold;
			border:0px solid #000000;
			border-radius:7px;
			-moz-border-radius:7px;
			padding:3px;
			margin:-55px auto 2px;
		}
		/*.cards:first-child {
			margin-top: 20px;
		}*/
        </style>
    </head>
	<body>
    <body onLoad="print();">
		<div class="cards achievement">
			<div class="row">
<?php
    include "config.phtml";
	$intKey = -1;
    foreach($this->arrBarcodes as $objCard)
    {
    	$intKey++;
		if ($intKey && $intKey % 10 == 0)
		{
			if ($intKey && $intKey % 2 == 0)
				print "
					</div>
				";
			print "
				</div><div class='cards achievement'>
				";
			if ($intKey && $intKey % 2 == 0)
				print "
					<div class='row'>
				";
		}
		else if ($intKey && $intKey % 2 == 0)
		{
			print "
				</div><div class='row'>
				";
		}
?>
		<div class="card">
			<div class="container">
<?php
		$strNetworkLogo = $sn . '/imgs/v/w/55/src/5461539_1916.png';
		$strImage = $sn . '/imgs/v/w/55/src/' . $objCard->campaign_image_id;	
		$intBarcode = $objCard->card_serial;
		preg_match('/^([^\/]+)\/ (.+)/', $objCard->achievement, $arrMatch);
		list ($strMatch, $strName, $strDescription) = $arrMatch;
		$strName = trim($strName);
?>
				<div class="logo"><img src="<?php echo $strNetworkLogo; ?>" /></div>
				<div class="institution"><img src="<?php echo $strImage; ?>" /></div>
				<div class="clear"></div>
				<div class="points"><?php print $strName; ?></div>
				<div class="title"><img src="<?php print $sn; ?>/imgs/v/src/3375159_3398.png" /></div>
				<div class="name"><?php print $strDescription; ?></div>
				<div class="barcode"><img src="<?php echo $sn; ?>/kiosk/get-barcode-legacy/serial/<?php print $intBarcode; ?>" width="210" height="20" /><br/><?php print $intBarcode; ?></div>
			</div>
		</div>
<?php
    }
?>
			</div>
		</div>


    </body>
</html>