<?php
	include "config.phtml";
	include "parameters.phtml";
?>
<div class="slider" id="announcements_listviewer">
<style type="text/css">
	.lable_count {
		float:right;
		background-color:#fff;
		border:1px solid gray;
		margin:5px;
		padding:2px 12px 2px 12px;
		text-align:center;
	}
	div.lists li .title.title_fix {
		max-width: 300px;
		white-space:nowrap;
		overflow:hidden;
		text-overflow:ellipsis;
	}
</style>
<script>
	$(document).ready(function () {
		if ($('#announcements_listviewer .lable_count.lable_name').length) {
			$('#announcements_listviewer div.lists li .title').addClass('title_fix');
		}
	});
</script>
	<div class="col_title">
		<span><?php print text($this->strTitle); ?></span>
	</div>
	<div class="col_content">
<?php
	include("uimods/sliderefresh.phtml");
?>
		<div id="lists" class="module lists forms">
			<div class="module_content">
				<ul>
<?php
	if (!count($this->arrList))
	{
?>
				<li>
					<div class="icon"></div>
					<div class="title"><?php print text("There are no announcements available."); ?></div>
				</li>
<?php
	}
	else
	{
		foreach ($this->arrList as $arrItem)
		{
?>
					<li>
						<a class="link" href="<?php echo (preg_match("/^http/", $arrItem['link']) ? "" : $sn) . (preg_match("/^\//", $arrItem['link']) ? "" : "/"). $arrItem['link']; ?>">
							<div class="icon"></div>
							<div class="title"><?php echo text($arrItem['text']); ?></div>
<?php
			if (isset($arrItem['name']))
			{
?>
							<div class="lable_count lable_name"><?php echo $arrItem['name']; ?></div>
<?php
			}
			if (isset($arrItem['date']))
			{
?>
							<div class="lable_count label_date"><?php echo $arrItem['date']; ?></div>
<?php
			}
?>
						</a>
					</li>
<?php
		}
	}
?>
				</ul>
			</div>
		</div>
	</div>
</div>