<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<meta http-equiv="X-UA-Compatible" content="chrome=1">
		<title><?php print $this->layout()->strTitle ? $this->layout()->strTitle . " - " : "" ?>Tzivos Hashem Kiosk</title>

		<script type="text/javascript" src="<?php print WEB_ROOT; ?>/js/back-end/admin/jquery2.js"></script>
		<script src="<?php print WEB_ROOT; ?>/js/back-end/kiosk/jquery.keypad.js" type="text/javascript"></script>

		<link href="<?php print WEB_ROOT; ?>/css/back-end/kiosk/reset.css" rel="stylesheet" type="text/css" />
		<link href="<?php print WEB_ROOT; ?>/css/back-end/kiosk/style.css" rel="stylesheet" type="text/css" />
		<link href="<?php print WEB_ROOT; ?>/css/back-end/kiosk/print.css" rel="stylesheet" type="text/css" media="print" />
		<link href="<?php print WEB_ROOT; ?>/css/back-end/kiosk/jquery.keypad.css" rel="stylesheet" type="text/css" />
		<!--[if IE]>
		<link href="<?php print WEB_ROOT; ?>/css/back-end/kiosk/style_ie.css" rel="stylesheet" type="text/css" />
		<![endif]-->

        <style type="text/css">
			.hasKeypad {
				width:200px;
				height:42px;
				background:none;
				background-color:#FFF;
				font-size:35px;
				font-weight:bold;
				font-family:"Myriad Pro",Arial,Helvetica,sans-serif;
				color:#000;
				padding:0;
				text-align:center;
				border:0;
			}
			.fronts, .backs {
				margin:-.05in .125in;
				page-break-after: always;
			}

			.fronts td, .backs td {
				border: 1px dashed black;
				-webkit-box-sizing: border-box;
				-moz-box-sizing: border-box;
				vertical-align: middle;
				height: 2in;
				width: 3.5in;
			}

			.fronts td td, .backs td td {
				width: auto;
				height: auto;
				border: none;
			}
			.cards {
				width:672px;
				page-break-after:always;
				margin:-0.1875in auto 0;
				font-family:'Myriad Pro',Arial,sans-serif;
			}
			.cards .card {
				width:3.5in;
				height:2in;
				text-align:center;

				width:306px;
				height:162px;
				padding:15px;
				float:left;

				background:#fff;
				color:#000;
				text-shadow:none;
			}
			.cards .card .container {
				border:2px solid #000;
				border-radius:10px;
				-moz-border-radius:10px;
				height:100%;
			}

			.cards .logo {
				float:left;
				margin-left:30px;
				height:60px;
			}
			.cards .institution {
				float:right;
				margin-right:30px;
			}
			.cards .logo img, .cards .institution img {
				margin:5px 0;
				width:55px;
				height:55px;
			}
			.cards .clear {
				clear:both;
			}

			.cards .title img {
				width:250px;
				height:34px;
			}

			.cards .campaign {
				clear:both;
				font-weight:bold;
				position:absolute;
				width:302px;
				font-size:14px;
			}

			.cards .name {
				font-size:12px;
				margin:6px 0;
				height:15px;
				font-weight:normal;
			}

			.cards .barcode {
				font-size:9px;
			}

			.cards .points {
				font-size:12px;
				width:50px;
				font-weight:bold;
				border:2px solid #000000;
				border-radius:7px;
				-moz-border-radius:7px;
				padding:3px;
				margin:-55px auto 10px;
			}


			.card_box {
				width:336px;
				padding:0 18px;
				background-position:-1px -10px;
			}
			.cards {
				width:auto;
				margin:0;
			}
			.cards .card {
				background:#fff;
				color:#000;
				text-shadow:none;
			}
			.cards .title {
				padding:0;
			}

			@media print {
				.fronts td, .backs td {
					border: none;
				}

				hr {
					display: none;
				}
			}

		</style>
	</head>

	<body class="green cardpop">
		<div id="wrapper">
			<div class="padding_left padding_top">
				<div id="close_pop"><a onClick="window.parent.Shadowbox.close()">Close</a></div>
<?php
	if ($this->boolHarvestControlCode)
	{
		if (!$this->objCard)
		{
?>
				<div id="page_title">Scan failed!</div>
				<div style="text-align:center; display:block;padding:10px;">
					<span style="font-family: Times New Roman sans-serif; font-size:20px; color: #fff;">Sorry, there seems to be something wrong with the card you are attempting to scan.</span>
				</div>
<?php
		}
		else
		{
?>
				<script>
					$(document).ready(function() {
						$('.keypad').focus().blur().keypad();
						window.onkeydown = scanFocus;
						window.onload = scanFocus;
						function scanFocus() {
							$('.keypad').focus();
						}

						$("#cardpop_control").bind("submit", function (event) {
							event.preventDefault();
							parent.control($("#control").val(), <?php print $this->objCard->card_serial; ?>);
						});

					});
				</script>
				<div id="page_title">Mazel Tov!</div>
				<div style="text-align:center; display:block;padding:10px;">
					<form method="post" action="#" id="cardpop_control">
						<div style="padding: 4px;font-family: Times New Roman sans-serif; font-size:20px; color: #fff;">Please enter your 6 digit control number found on the top right of your card.<br>
						Once you put in the right number the miles will be added to your account.<br>&nbsp<br>
						<table border="0" width="100%"><tr><td width="33%" align="right"><img src="<?php print WEB_ROOT . "/images/cardcontrol.jpg";?>" /></td><td>&nbsp;&nbsp;&nbsp;&nbsp;</td><td valign="middle" align="left" width="26%"><input type="text" maxlength="6" class="keypad" name="control" id="control" value="" autocomplete="off" /></td><td>&nbsp;&nbsp;&nbsp;&nbsp;</td><td align="left" width="41%"><input style="font-size: 14pt; padding: 5px;" type="submit" value="ADD TO MY ACCOUNT" /></td></tr>
						<tr><td colspan="2">&nbsp;</td><td id="cardpop_control_status"></table></div>
					</form>
				</div>
<?php
		}
	}
	else
	{
?>
		<div id="scancardbox" style="position:absolute;z-index:-100;filter:alpha(opacity=0);opacity:0;">
			<form method="POST" name="scancard" onSubmit="parent.loadShadow(this.scantext); return false;">
				<input name="scantext" id="scantext" type="text" autocomplete="off" />
			</form>
		</div>
		<script type="text/javascript">
			window.onload = scanFocus;
			window.onkeydown = scanFocus;
			function scanFocus() {
				if (document.scancard)
					document.scancard.scantext.focus();
			}
		</script>
<?php
		if ($this->strScanCodeMessage)
		{
?>
				<div id="page_title"><?php print text("Scan failed!"); ?></div>
				<div style="text-align:center; display:block;padding:10px;">
					<span style="font-family: Times New Roman sans-serif; font-size:20px; color: #fff;"><?php print text($this->strScanCodeMessage); ?></span>
				</div>
<?php

		}
		else if ($this->objCard && $this->objCard->status != "scanned")
		{
?>
		<script type="text/javascript">
			window.parent.add_to_miles(<?php print $this->objCard->card_points; ?> * 1);
		</script>
				<div id="page_title">Scan successful!</div>
				<div style="text-align:center; display:block;padding:10px;">
					<span style="font-family: Times New Roman sans-serif; font-size:20px; color: #fff;">You where just awarded <?php print $this->objCard->card_points; ?> points!</span>
				</div>
<?php
		}
		else if (!isset($this->objCampaign)) {
?>
				<div id="page_title">Scan failed!</div>
				<div style="text-align:center; display:block;padding:10px;">
					<span style="font-family: Times New Roman sans-serif; font-size:20px; color: #fff;">Sorry, there seems to be something wrong with the card you are attempting to scan.</span>
				</div>
<?php
		}
		else if (!$this->objCard || $this->objCard->status == "scanned")
		{
?>
				<div id="page_title">Scan failed!</div>
				<div style="text-align:center; display:block;padding:10px;">
					<span style="font-family: Times New Roman sans-serif; font-size:20px; color: #fff;">Sorry, this card was already scanned and cannot be scanned twice.</span>
				</div>
<?php
		}
		else if (1||$this->objCard->campaign_id)
		{
?>
				<div id="page_title"><?php print $this->objCard ? "Scanned Successfully<br>Mazal Tov - Keep up the good work! " : "Sorry, something went wrong!"; ?></div>
				<div class="card_box">
					<div class="cards achievement">
						<div class="card">
							<div class="container">
								<div class="logo"><img src="<?php echo WEB_ROOT; ?>images/show-image/image_id/<?php print $this->objInstitution->image_id; ?>" /></div>
								<div class="institution"><img src="<?php echo WEB_ROOT; ?>images/show-image/image_id/<?php print @$this->objCampaign->image_achievement; ?>" /></div>
								<div class="clear"></div>
								<div class="points"><?php print $this->objCard->card_points . " point" . ($this->objCard->card_points > 1 ? "s" : ""); ?></div>
								<div class="campaign"><?php print @$this->objCampaign->campaign_name; ?></div>
								<div class="title"><img src="<?php echo WEB_ROOT; ?>images/Achievement_Card.png" /></div>
								<div class="name"><?php print @$this->objTask->task_name; ?></div>
								<div class="barcode"><img src="<?php echo WEB_ROOT; ?>kiosk/get-barcode-legacy/serial/<?php print $this->objCard->card_serial; ?>" width="210" height="20"><?php print $this->objCard->card_serial; ?></div>
							</div>
						</div>
					</div>
				</div>
<?php
		} else {
			print "<div>" . $this->objCard->card_points . " point" . ($this->objCard->card_points > 1 ? "s" : "") . " have been awarded to you!</div>";
		}
	}
?>
		  </div>
		</div>
	</body>

</HTML>

