<?php
	include "config.phtml";
	include "parameters.phtml";
?>
<script language="javascript">
$(document).ready(function()
{
	var objTimeout = false;
	$('.slider:last form').keyup(function (e) {
		var charCode = (e.which) ? e.which : e.keyCode;
		if (charCode == 13) {
			e.preventDefault();
			if ($(this).find('.submit').length)
				$(this).find('.submit').click();
			else
				$(this).submit();
		}
		window.clearTimeout(objTimeout);
		objTimeout = window.setTimeout(function () {
			var arrData = $('body').data("reg_data");
			if (!arrData)
				arrData = {};
			var arrNewData = $('.slider:last form').serializeArray();
			for (var intItr in arrNewData)
			{
				arrData[arrNewData[intItr]["name"]] = arrNewData[intItr]["value"];
			}
			$('body').data("reg_data", arrData);
		}, 100);
	});

	var arrRegData = $('body').data("reg_data");
	for (var strKey in arrRegData)
	{
		$(".slider:last #" + strKey).val(arrRegData[strKey]);
	}

	$('.slider:last form a.submit').click( function(e) {
		$(".slider:last .processing_status").fadeOut();
		$.ajax({
			type : "POST",
			cache : false,
			start: $(".slider:last #processing_status").html('Loading...').fadeIn(),
			url : '<?php echo $sn . "/registration/institution" . $strParamPath; ?>',
			dataType : "text",
			data: $('.slider:last form').serialize(),
			success : function(strResponse) {
				try {
					var arrResponse = jQuery.parseJSON(strResponse);
				} catch(e) {
					$(".slider:last #processing_status").html('Sorry, there was an error: VU-E101-3RR3RE');
					alert("Sorry, there was an error: VI-J101-SDF88D");
					alert(strResponse);
					return;
				}
				if (typeof(arrResponse) != "object") {
					$(".slider:last #processing_status").html('Sorry, there was an error: VU-E102-SDF8BX');
					alert("Sorry, there was an error: VI-J102-ASD9S9");
					return;
				} else {
					$(".slider:last #processing_status").fadeOut();
					if (arrResponse["error"]) {
						if (typeof(arrResponse["error"]) != "object") {
							$(".slider:last #processing_status").html(arrResponse["error"]);
						} else {
							for (strField in arrResponse["error"])
							{
								//alert($.dump($(".slider:last #" + strField).closest("li").html()));return;
								$(".slider:last #" + strField).closest("li").next().html(arrResponse["error"][strField]).fadeIn();
							}
						}
					} else if (arrResponse["success"] == "true") {
						var strURL = '<?php print $sn . "/registration/kioskaccessories" . $strParamPath; ?>';
						slideURL(strURL);
					} else {
						alert("Sorry, there was an error: VI-J103-99DS0S");
						//alert($.dump(arrResponse));
					}
				}
			}
		});
	});
});
</script>

<div class="slider">
	<div class="col_title"><span>Institution Information</span></div>
	<div class="col_content camper">
		<div class="module form" id="module-info">
			<div class="module_content list">
				<form name="registration_institution" id="registration_institution" method="post" action="">
					<input type="hidden" id="registration_institution_data" value="" />
				<ul>
<?php
	global $arrAppDetails;
	$strCurrentImage = "0.gif";
	if (isset($arrAppDetails[$this->tstyle]['default_institution_logo']))
		$strCurrentImage = str_replace('/imgs/v/src/', '', $arrAppDetails[$this->tstyle]['default_institution_logo']);
?>
					<li>
						<h3>Institution logo</h3>
						<input type="hidden" name="institution_image_id" id="institution_image_id" value="<?php print $strCurrentImage; ?>" />
						<iframe src="<?php print $sn; ?>/imgs/smalluploader/current_image/<?php print $strCurrentImage; ?>/resultid/institution_image_id" width="100%" height="80" scrolling="no">
							<p>Your browser does not support iframes.</p>
						</iframe>
					</li>
					<div class="processing_status"></div>
					<li>
						<span class="label">Institution name: *</span>
						<span class="input"><input autocomplete="off" type="text" class="required" name="institution_name" id="institution_name" value="" /></span>
						<div class="clear"></div>
					</li>
					<div class="processing_status"></div>
					<li>
						<span class="label">Institution e-mail: *</span>
						<span class="input"><input autocomplete="off" type="text" name="institution_email" id="institution_email" value="" /></span>
						<div class="clear"></div>
					</li>
					<div class="processing_status"></div>
					<li>
						<span class="label">Institution phone: *</span>
						<span class="input"><input autocomplete="off" type="text" name="institution_phone" id="institution_phone" value="" /></span>
						<div class="clear"></div>
					</li>
					<div class="processing_status"></div>
					<li>
						<span class="label">Institution website:</span>
						<span class="input"><input autocomplete="off" type="text" name="institution_website" id="institution_website" value="" /></span>
						<div class="clear"></div>
					</li>
					<div class="processing_status"></div>
					<div id="processing_status" style="padding:4px"></div>
					<li>
						<span><a href="#" title="Save" class="button submit">Next</a></span>
						<div class="clear"></div>
					</li>
				</ul>
			</form>
			</div>
		</div>
	</div>
</div>