<?php
	if (empty($this->tstyle))
		$this->tstyle = "chabadhebrewschool";
	include "public_header.phtml";
	include "config.phtml";
	include "parameters.phtml";
	global $arrAppDetails;
	$arrDetails = $arrAppDetails[$this->tstyle];
?>
<script type="text/javascript">
var GLOBAL_SLIDES = {};
$(document).ready(function()
{
	$('#email').focus();
	$('#footer_links a').mouseover(function () {
		$(this).css({
			'color' : '#000'
		});
	});
	$('#footer_links a').mouseout(function () {
		$(this).css({
			'color' : '#555'
		});
	});
});
</script>
<style>
#footer_links a {
	color:#555;
}
#footer_links {
	width:1024px;
	margin:0 auto;
	height:30px;
	padding:4px;
	color:#555;
}
h1 {
	margin-bottom:20px;
	border-bottom: 1px solid #ddd;
	padding-bottom: 12px;
	padding:8px;
}
h2 {
	text-align: left;
	border-bottom: 1px solid #ddd;
	margin-bottom: 8px;
	padding:8px;
	padding-top:19px;
	padding-bottom: 12px;
}
div.line {
	border-bottom: 1px solid #ddd;
	margin: 8px 0;
	height:1px;
}
.promo td {
	padding:4px;
}
#nav ul.list_first li img {
	margin-right: 15px;
}
#footer_links {
	height:auto !important;
}
</style>
</head>

<body>
    <NOSCRIPT><P STYLE="color: red; font-size: larger;"><?php print text("Notice: You have javascript disabled. This site will not function without javascript."); ?></P></NOSCRIPT>
	<div id="wrapper">
    	<div id="nav">
        	<div class="col_title_bg"></div>
            <div class="col_title"><?php print text("Menu"); ?></div>
            <ul class="list_first">
				<li class="list_parent"><a href="#" onclick="window.location.href='<?php echo $sn;?>/registration/index2/tstyle/<?php print $this->tstyle; ?>';"><img src="<?php print $sn; ?>/images/front-end/admin/icon_school.png" width="28" height="28" /><?php print text("Register"); ?></a></li>
                <li class="list_parent"><a href="#" onclick="window.location.href='<?php echo $sn;?>';"><img src="<?php print $sn; ?>/images/front-end/admin/icon_door_in.png" width="28" height="28" /><?php print text("Login"); ?></a></li>
				<li class="list_parent"><a href="#" onclick="window.location.href='<?php echo $sn;?>/mobile';"><img src="<?php print $sn; ?>/images/MOBILE-APP-ICON-GREEN_300x300.png" width="28" height="28" /><?php print text("Mobile"); ?></a></li>
            </ul>
        </div>
        <div id="content">
        	<div class="col_title_bg"></div>
            <div class="slider_container">
                <div class="slider">
                    <div class="col_title"><span><?php print text("Mashpia Online Scanner App"); ?></span></div>
                    <div class="col_content">
						<div class="module message" style="padding:20px;vertical-align: top;font-size:14pt;line-height: 14pt">
                            <div class="module_content" style="vertical-align: top;text-align: left;">
								<h1>Privacy Policy</h1>
								<h2>Personal Information</h2>
								<p>We do not collect any personal information about the users of our apps.<br>
								We do not contact any of the users of our app.<br>
								We may collect anonymous usage information to help us improve our services and applications.</p>
								<h2>Geo-Location</h2>
								<p>Our apps do not collect information about the location of your mobile device.</p>
								<h2>In-App Purchases</h2>
								<p>Our apps do not contain any In-App Purchases.</p>
								<h2>Advertising</h2>
								<p>Our apps do not contain any third party advertising.</p>
								<h2>Privacy Questions</h2>
								<p>If you have any questions about our apps or privacy policy please contact us at: privacy@mashpia.com</p>
								<h2>Changes</h2>
								<p>We reserve the right, at any time, to add to, change, update, or modify this Policy, simply by posting such change, update, or modification on the Site and without any other notice to you. Any such change, update, or modification will be effective immediately upon posting on the Site. It is your responsibility to review this Policy from time to time to ensure that you continue to agree with all of its terms.</p>
							</div>
						</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
	<div id="footer_links">
		<div style="float:left;text-align:left;width:90px;margin:0 8px;"><a href="<?php print $sn; ?>/index/contact<?php print $strParamPath; ?>" class="overlay">Contact Us</a></div>
		<div style="float:left;text-align:left;width:383px;margin:0 8px;"><a href="<?php print $sn; ?>/index/privacy<?php print $strParamPath; ?>">Privacy Policy</a></div>
		<div style="float:right;text-align:right;display:inline-block;margin:0 8px;width:383px;">Copyright © 2015 - mashpia.com</div>
	</div>
	<div id="overlay">
		<div class="content"></div>
	</div>
</body>
</html>
