<?php 
	include "config.phtml";
	include "parameters.phtml";
?>
<div class="slider">
	<div class="col_title">
		<span>Marking Campaigns</span>
	</div>
	<div class="col_content">
<?php
	if (!count($this->arrCampaigns))
	{
?>
		<div class="module" style="padding:5px;">
			There are no Campaigns available to display.
		</div>
<?php
	}
	else
	{
?>
		<div id="lists" class="module lists forms">
			<div class="module_content">
				<ul>
<?php 
		foreach ($this->arrCampaigns as $objCampaign)
		{
?>
					<li>
						<a class="link" href="<?php print $sn . "/marking/markinglist/campaign_id/" . $objCampaign->campaign_id . $strParamPath; ?>">
							<div class="icon"></div>
							<div class="title"><?php echo $objCampaign->campaign_name; ?></div>
						</a>
					</li>
<?php		
		}
?>
				</ul>
			</div>
		</div>
<?php
	}
?>
	</div>
</div>