<?php 
	include "config.phtml";
	include "parameters.phtml";
	$user_session_data = new Zend_Session_Namespace('user_session_data');
?>
<div class="slider">
	<div class="col_title">
		<span><?php print $user_session_data->institution_type == "School" ? "Student" : "Camper"; ?> Accounts</span>
	</div>
	<div class="col_content">
<?php 
	if(!count($this->arrUsers))
	{
?>
		<div class="module" style="padding:5px;">There are no Users available to display.</div>
<?php 
	}
	else
	{
?>
		<div id="lists" class="module lists forms">
			<div class="module_content">
				<ul>
					<li>
						<a class="link" href="<?php echo $sn; ?>/orders/orderslist/class_id/<?php print $this->class_id; ?>">
							<div class="icon"></div>
							<div class="title">Skip to Orders List</div>
						</a>
					 </li>
<?php
		
		foreach ($this->arrUsers as $objUser)
		{
?>
					<li>
						<a class="link" href="<?php echo $sn; ?>/orders/orderslist/student_id/<?php echo $objUser->user_id . $strParamPath;?>">
							<div class="icon"></div>
							<div class="title"><?php echo $objUser->first_name . " " . $objUser->last_name; ?></div>
						</a>
					</li>
<?php
        }
?>
				</ul>
			</div>
		</div>
<?php
	}
?>
	</div>
</div>