<?php
	include "config.phtml";
	include "parameters.phtml";
	$user_session_data = new Zend_Session_Namespace("user_session_data");
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Voucher</title>
<style type="text/css">
.mainWrapper {
	font-family: Verdana, Geneva, sans-serif;
	font-size: 16px;
	height: 400px;
	width: 300px;
	padding:20px;
	border: 1px dotted #999;
	margin-left:auto;
	margin-right:auto;
	margin-bottom: 2px;
}
h1 {
	margin:0px;
}
</style>
</head>
<body onLoad="print();">
<?php
	foreach ($this->arrVouchers as $arrVoucherCategory)
	{
		foreach ($arrVoucherCategory as $arrVoucher)
		{
?>
		<div class="mainWrapper" >

		  <div align="center" style="width:300px;height:63px"><?php print $arrVoucher["objInstitution"]->name;?> </div>
			<h1 align="center"><strong>Store Voucher </strong></h1>
		  <hr />
		  <p align="center">This voucher entitles <br />
		  <em><strong><?php print $arrVoucher["objUser"]->first_name . " " . $arrVoucher["objUser"]->last_name;?></strong></em><br />
		  to</p>
		  <h3 align="center"> <?php print $arrVoucher["objUserPrize"]->quantity . " X " . $arrVoucher["objPrize"]->prize_name;?></h3>
		  <p>Print this voucher and present it to your base commander to redeem it.  </p>
		  <p>This voucher is only valid in <em><?php print $arrVoucher["objInstitution"]->institution_type; ?></em>.<br />
		  </p>
<?php
			if ($arrVoucher["objUserPrize"]->serial)
			{
?>
		  <center><img src="<?php print $sn; ?>/kiosk/get-barcode-legacy/serial/<?php print $arrVoucher["objUserPrize"]->serial; ?>" /></center>
			<center><?php print $arrVoucher["objUserPrize"]->serial; ?></center>
<?php
			}
			else
			{
				print "<br>&nbsp;<br>&nbsp;";
			}
?>
		</div>
		<div style="page-break-after:always"></div>
<?php
		}
	}
?>
	</body>
</html>
