<?php
	include "config.phtml";
	$strUrl = "";
	if (isset($this->intHost))
		$strUrl .= "host_id/" . $this->intHost . "/";
	if (isset($this->intNetwork))
		$strUrl .= "network_id/" . $this->intNetwork . "/";
	if (isset($this->intInstitution))
		$strUrl .= "institution_id/" . $this->intInstitution . "/";
	if (isset($this->intClass))
		$strUrl .= "class_id/" . $this->intClass . "/";
?>
<div class="slider">
	<div class="col_title">
		<span>Prize Templates</span>
	</div>
	<div class="col_content">
		<div id="lists" class="module lists forms">
			<div class="module_content">
<?php
	if (!count($this->arrTemplates))
	{
?>
				<div class="module" style="padding:5px;">There are no templates available to view.</div>
<?php
	}
	else {
?>
				<form name="form" id="form" method="post" action="">
					<ul>
<?php
		foreach ($this->arrTemplates as $objTemplate)
		{
?>
						<li>
							<a class="link" href="<?php echo $sn; ?>/store/prize/mode/template/<?php echo $strUrl . "template_id/" . $objTemplate->prize_id; ?>">
								<div class="icon"></div>
								<div class="title"><?php echo $objTemplate->prize_name; ?></div>
							</a>
						</li>
<?php
		}
?>
					</ul>
				</form>
<?php
	}
?>
			</div>
		</div>
	</div>
</div>