<?php include "config.phtml"; ?>
<?php include "parameters.phtml"; ?>
<div class="slider" id='slider_grades'>
	<div class="col_title">
			<span>Grades</span>
	</div>
	<div class="col_content">
		
		<div id="lists" class="module lists forms">
			<div class="module_content">
				<ul>
<?php
	if ($this->objRoles->isAllowed('Super Administrator'))
	{
?>
					<li>
						<a class="link" href="<?php echo $sn; ?>/grades/gradeshostlist">
							<div class="icon"></div>
							<div class="title">View Grades by Hosts</div>
						</a>
					</li>
					<li>
						<a class="link" href="<?php echo $sn; ?>/grades/gradenetworks">
							<div class="icon"></div>
							<div class="title">View Grades by Network</div>
						</a>
					</li>
					<li>
						<a class="link" href="<?php echo $sn; ?>/grades/gradeslist">
							<div class="icon"></div>
							<div class="title">View All Grades</div>
						</a>
					</li>
					<li>
						<a class="link" href="<?php echo $sn; ?>/grades/gradeaddhosts">
							<div class="icon"></div>
							<div class="title">Add New Grade</div>
						</a>
					</li>
<?php
	}
	elseif ($this->objRoles->isAllowed('Host Administrator'))
	{
?>
					<li>
						<a class="link" href="<?php echo $sn; ?>/grades/gradenetworks<?php echo $institution_string; ?>">
							<div class="icon"></div>
							<div class="title">View Grades by Network</div>
						</a>
					</li>
					<li>
						<a class="link" href="<?php echo $sn; ?>/grades/gradesstatus<?php echo $institution_string; ?>">
							<div class="icon"></div>
							<div class="title">View All Grades</div>
						</a>
					</li>
					<li>
						<a class="link" href="<?php echo $sn; ?>/grades/gradeaddnetworks<?php echo $institution_string; ?>">
							<div class="icon"></div>
							<div class="title">Add New Grade</div>
						</a>
					</li>
<?php
	}
	elseif ($this->objRoles->isAllowed('Network Administrator'))
	{
?>
					<li>
						<a class="link" href="<?php echo $sn; ?>/grades/gradesstatus">
							<div class="icon"></div>
							<div class="title">View All Grades</div>
						</a>
					</li>
					<li>
						<a class="link" href="<?php echo $sn; ?>/grades/gradeadd">
							<div class="icon"></div>
							<div class="title">Add New Grade</div>
						</a>
					</li>
					
<?php
}
?>
				</ul>
			</div>
		</div>
		
	</div>
</div>