<?php include "config.phtml"; ?>
<?php include "parameters.phtml"; ?>
<div class="slider">
	<div class="col_title">
			<span>Institutions</span>
	</div>
	<div class="col_content">
		
		<div id="lists" class="module lists forms">
			<div class="module_content">
				<ul>
					<li>
						<a class="link" href="<?php echo $sn; ?>/dashboard/hosts">
							<div class="icon"></div>
							<div class="title">View Hosts</div>
						</a>
					</li>
					<li>
						<a class="link" href="<?php echo $sn; ?>/dashboard/networks">
							<div class="icon"></div>
							<div class="title">View Networks</div>
						</a>
					</li>
					<li>
						<a class="link" href="<?php echo $sn; ?>/dashboard/institutions">
							<div class="icon"></div>
							<div class="title">View Institutions</div>
						</a>
					</li>
				</ul>
			</div>
		</div>
		
	</div>
</div>