<?php
include "config.phtml";
include "parameters.phtml";
?>
<div class="slider">
	<div class="col_title">
			<span>Campaign Marking</span>
	</div>
	<div class="col_content">		
		<div id="lists" class="module lists forms">
			<div class="module_content">
				<ul>
					<li>
						<a class="link" href="<?php echo $sn; ?>/marking/markingclasses<?php echo $strParamPath?>">
							<div class="icon"></div>
							<div class="title">Marking by Class</div>
						</a>
					</li>
				</ul>
			</div>
		</div>
	</div>
</div>