<?php 
	include "config.phtml";
	include "parameters.phtml";
	
	$user_session_data = new Zend_Session_Namespace('user_session_data');	
?>

<div class="slider">
	
	<div class="col_title">
		<span>Missions</span>
	</div>
	
	<div class="col_content">
		
		<div id="lists" class="module lists forms">
			
			<div class="module_content">
				
				<ul>
					
<?php if ($this->objRoles->isAllowed('Super Administrator')) : ?>
					<li>
						<a class="link" href="<?php echo $sn; ?>/campaigns/missionhosts/">
							<div class="icon"></div>
							<div class="title">View Missions by Host</div>
						</a>
					</li>
					<li>
						<a class="link" href="<?php echo $sn; ?>/campaigns/missionnetworks/">
							<div class="icon"></div>
							<div class="title">View Missions by Networks</div>
						</a>
					</li>
					<li>
						<a class="link" href="<?php echo $sn; ?>/campaigns/missioninstitutions/">
							<div class="icon"></div>
							<div class="title">View Missions by Institutions</div>
						</a>
					</li>
					<li>
						<a class="link" href="<?php echo $sn; ?>/campaigns/missioncampaign/">
							<div class="icon"></div>
							<div class="title">View Missions by Campaign</div>
						</a>
					</li>
					<li>
						<a class="link" href="<?php echo $sn; ?>/campaigns/missionlist">
							<div class="icon"></div>
							<div class="title">View All Missions</div>
						</a>
					</li>					
					<li>
						<a class="link" href="<?php echo $sn; ?>/campaigns/missionaddhosts">
							<div class="icon"></div>
							<div class="title">Add New Mission</div>
						</a>
					</li>
<?php elseif ($this->objRoles->isAllowed('Host Administrator')) : ?>
					<li>
						<a class="link" href="<?php echo $sn; ?>/campaigns/missionnetworks<?php echo $institution_string; ?>">
							<div class="icon"></div>
							<div class="title">View Missions by Networks</div>
						</a>
					</li>
					<li>
						<a class="link" href="<?php echo $sn; ?>/campaigns/missioninstitutions<?php echo $institution_string; ?>">
							<div class="icon"></div>
							<div class="title">View Missions by Institutions</div>
						</a>
					</li>
					<li>
						<a class="link" href="<?php echo $sn; ?>/campaigns/missioncampaign<?php echo $institution_string; ?>">
							<div class="icon"></div>
							<div class="title">View Missions by Campaign</div>
						</a>
					</li>
					<li>
						<a class="link" href="<?php echo $sn; ?>/campaigns/missionlist<?php echo $institution_string; ?>">
							<div class="icon"></div>
							<div class="title">View All Missions</div>
						</a>
					</li>					
					<li>
						<a class="link" href="<?php echo $sn; ?>/campaigns/missionaddnetworks<?php echo $institution_string; ?>">
							<div class="icon"></div>
							<div class="title">Add New Mission</div>
						</a>
					</li>
<?php elseif ($this->objRoles->isAllowed('Network Administrator')) : ?>
					<li>
						<a class="link" href="<?php echo $sn; ?>/campaigns/missioninstitutions<?php echo $institution_string; ?>">
							<div class="icon"></div>
							<div class="title">View Missions by Institutions</div>
						</a>
					</li>
					<li>
						<a class="link" href="<?php echo $sn; ?>/campaigns/missioncampaign<?php echo $institution_string; ?>">
							<div class="icon"></div>
							<div class="title">View Missions by Campaign</div>
						</a>
					</li>
					<li>
						<a class="link" href="<?php echo $sn; ?>/campaigns/missionlist<?php echo $institution_string; ?>">
							<div class="icon"></div>
							<div class="title">View All Missions</div>
						</a>
					</li>					
					<li>
						<a class="link" href="<?php echo $sn; ?>/campaigns/missionaddinstitutions<?php echo $institution_string; ?>">
							<div class="icon"></div>
							<div class="title">Add New Mission</div>
						</a>
					</li>			
<?php elseif ($this->objRoles->isAllowed('Institution Administrator')) : ?>
					<li>
						<a class="link" href="<?php echo $sn; ?>/campaigns/missioncampaign<?php echo $institution_string; ?>">
							<div class="icon"></div>
							<div class="title">View Missions by Campaign</div>
						</a>
					</li>
					<li>
						<a class="link" href="<?php echo $sn; ?>/campaigns/missionlist<?php echo $institution_string; ?>">
							<div class="icon"></div>
							<div class="title">View All Missions</div>
						</a>
					</li>
					<!--
					<li>
						<a class="link" href="<?php //echo $sn; ?>/campaigns/missionaddinstitutions<?php //echo $institution_string; ?>">
							<div class="icon"></div>
							<div class="title">Add New Mission</div>
						</a>
					</li>
					-->
<?php endif; ?>


				</ul>
				
			</div>
		
		</div>
	
	</div>

</div>