<?php
include "config.phtml";
include "parameters.phtml";
?>

<div class="slider">
	<div class="col_title">
			<span>Networks</span>
	</div>
	<div class="col_content">
		
		<div id="lists" class="module lists forms">
			<div class="module_content">
				<ul>
<?php if ($this->objRoles->isAllowed('Super Administrator')) : ?>
					<li>
						<a class="link" href="<?php echo $sn; ?>/administration/networkhostlist">
							<div class="icon"></div>
							<div class="title">View Networks by Hosts</div>
						</a>
					</li>
					<li>
						<a class="link" href="<?php echo $sn; ?>/administration/networklist">
							<div class="icon"></div>
							<div class="title">View All Networks</div>
						</a>
					</li>
					<li>
						<a class="link" href="<?php echo $sn; ?>/administration/networkaddhosts">
							<div class="icon"></div>
							<div class="title">Add New Network</div>
						</a>
					</li>
<?php elseif ($this->objRoles->isAllowed('Host Administrator')) : ?>
					<li>
						<a class="link" href="<?php echo $sn; ?>/administration/networklist<?php echo $institution_string; ?>">
							<div class="icon"></div>
							<div class="title">View All Networks</div>
						</a>
					</li>
					<li>
						<a class="link" href="<?php echo $sn; ?>/administration/networkadd<?php echo $institution_string; ?>">
							<div class="icon"></div>
							<div class="title">Add New Network</div>
						</a>
					</li>
					
<?php endif ?>
				</ul>
			</div>
		</div>
		
	</div>
</div>