<?php
	include "config.phtml";
	include "parameters.phtml";
	$objUserSession = new Zend_Session_Namespace("user_session_data");
?>
<script language="javascript">
$(document).ready(function()
{
	$(this).delay(1).queue(function () {
		$(this).dequeue();
		$('.slider:last input[type=checkbox]').iphoneStyle({});
		$(".slider:last .date").datepicker();
		$('.slider:last form.reset_student_points input[type=checkbox].reset_checkbox').bind('didchange', function () {
			var boolChecked = $(this).attr('checked');
			if (boolChecked)
				$('.slider:last form.reset_student_points .action_button').removeClass('ihidden');
			else
				$('.slider:last form.reset_student_points .action_button').addClass('ihidden');
		});
		var fnResetPoints = function (strFormName, intStartPoint) {
			if ($('.slider:last .retro_active_date').attr('checked') && !intStartPoint) {
				if (!confirm("<?php print text("Warning: Students who have made purchases between the the retroactive date you specified and today, may now have negative points because you will be removing the points they used to purchase the prizes retroactively."); ?>\n"
					+ "\nAre you sure you would like to do a retroactive delele?")) {
					$(".slider:last ." + strFormName + " .processing_status").fadeOut("fast");
					return;
				}
			}
			$.ajax({
				type : "POST",
				cache : false,
				url : '<?php echo $sn . "/dashboard/resetpoints/start_point/' + intStartPoint + '/' + strFormName + '/true" . $strParamPath; ?>',
				dataType : "text",
				data: $('.slider:last form.' + strFormName).serialize(),
				success : function(strResponse) {
					try {
						var arrResponse = jQuery.parseJSON(strResponse);
					} catch(e) {
						$.alert(strResponse);
						$(".slider:last ." + strFormName + " .processing_status").html('<?php print text("Sorry, there was an error"); ?>: VU-rp01-3RR3RE');
						return;
					}
					if (typeof(arrResponse) != "object") {
						$.alert(strResponse);
						$(".slider:last ." + strFormName + " .processing_status").html('<?php print text("Sorry, there was an error"); ?>: VU-rp102-SDF8BX');
						return;
					} else {
						if (arrResponse.success) {
							if (arrResponse.intPermissionsCount == 100) {
								fnResetPoints(strFormName, intStartPoint+100);
							} else
								$(".slider:last ." + strFormName + " .processing_status").html("Reset successful.").fadeIn("slow").delay(10000).fadeOut("slow");
						} else if (arrResponse.error) {
							$(".slider:last ." + strFormName + " .processing_status").html(arrResponse.error).fadeIn("slow");
						} else {
							$(".slider:last ." + strFormName + " .processing_status").html('<?php print text('Sorry, there was an error'); ?>: VU-rp103-sdf98s').fadeIn("slow");
						}
					}
				}
			});
		};
		$('.slider:last form.reset_student_points .action_button').bind('click', function () {
			var strFormName = 'reset_student_points';
			$(".slider:last ." + strFormName + " .processing_status").html('Loading...').fadeIn("fast");
			fnResetPoints(strFormName, 0);
		});
	});
});
</script>
<div class="slider">
	<style>
		.processing_status {
			color: black;
		}
	</style>
	<div class="col_title">
		<span><?php print text("Reset [|Points|]"); ?></span>
		<div class="title_help info" title="<?php print text('Apply an automated event that does a subtraction to all your [|students|] [|points|], setting them all to zero.'); ?> "></div>
	</div>
<?php
//if (!isset($this->arrConfigOptions["achievementcards"]["achievementcardimage"]))
//	$intImage = '3375159_3398.png';
//else
	$intImage = $this->arrConfigOptions["achievementcards"]["achievementcardimage"];
?>
	<div class="col_content">
		<h2><?php print text("Reset [|Students|] Store [|Points|]"); ?></h2>
		<div class="module form use_custom_image">
			<div class="module_content lists">
				<form class="reset_student_points">
					<ul>
						<li>
							<span class="label" style="width:340px"><?php print text("Set a retroactive date for the reset:"); ?></span>
							<span class="input">
								<div style="float:left;margin: 4px 30px 0px 1px;">
									<input type="checkbox" class="icheck retro_active_date" name="retro_active_date" value="1" />
								</div>
								<input style="padding-left:4px;width:160px" placeholder="MM/DD/YYYY" type="text" class="noinput required date start_date" name="retro_date" />
							</span>
							<div class="clear"></div>
						</li>
						<li>
							<span class="label" style="width:340px"><?php print text("Reset all your [|students|] store [|points|]:"); ?></span>
							<span class="input" style="margin: 4px 0px 0px 1px;">
								<input class="reset_checkbox" type="checkbox" value="1" />
							</span>
							<span class="ihidden input action_button" style="padding-left:10px;margin: 3px 0px 0px 20px;">
								<div class="button"><?php print text('Reset Store [|Points|]'); ?></div>
							</span>
							<div class="clear"></div>
						</li>
						<div class="processing_status"></div>
					</ul>
				</form>
			</div>
		</div>
	</div>
</div>