<?php
	include "config.phtml";
	include "parameters.phtml";
?>
<div class="slider">
	
	<div class="col_title">
		<span>Resources</span>
	</div>
	
	<div class="col_content">
		<div id="lists" class="module lists forms">
			<div class="module_content">
				<ul>
					<li>
						<a href="#" onclick="window.open('<?php echo $sn . "/images/Tanya With Nekudos.pdf"; ?>', 'tanya pdf', 'menubar=0,status=0,toolbar=0');">
							<div class="icon"></div>
							<div class="title">Tanya with Nekudos</div>
						</a>
					</li>
					<li>
						<a href="#" onclick="window.open('http://www.jewishaudio.org/rabbi-sholom-ber-engel/tanya/', 'tanya resources', 'menubar=0,status=0,toolbar=0,scrollbars=1');">
							<div class="icon"></div>
							<div class="title">Tanya Music CD</div>
						</a>
					</li>
					<li>
						<a href="#" onclick="window.open('<?php echo $sn; ?>/images/TBP%20BC%20Tutorial.pdf', 'tanya resources', 'menubar=0,status=0,toolbar=0');">
							<div class="icon"></div>
							<div class="title">TBP Tutorial</div>
						</a>
					</li>
				</ul>
			</div>
		</div>
	</div>
</div>