<?php
	include "config.phtml";
	include "parameters.phtml";
	$intCustomSize = (isset($this->intCustomSize) && $this->intCustomSize) ? $this->intCustomSize : 70;
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
   "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<META HTTP-EQUIV="PRAGMA" CONTENT="NO-CACHE">
	<title>Mashpia.com Image Upload Tool</title>
	<script src="<?php print WEB_ROOT; ?>/js/back-end/admin/jquery2.js" type="text/javascript"></script>
	<script type="text/javascript" src="<?php print WEB_ROOT; ?>/js/back-end/admin/jquery.dump.js"></script>
	<script language="javascript">
		$(document).ready(function()
		{
<?php

	if (preg_match("/^(?:[0-9]{7}_)?[0-9]+\.(jpeg|jpg|gif|png)$/i", $this->strCurrentImage) || $this->strCurrentImage > 0)
	{
?>
			$('#photo_preview_table').css('display', 'block');
			$('#photo_upload_table').css('display', 'none');
			$("#photo_preview_image").html("<img src='<?php print WEB_ROOT; ?>/imgs/v/w/<?php print $intCustomSize; ?>/h/<?php print $intCustomSize; ?>/src/<?php print $this->strCurrentImage; ?>' border='0' width='<?php print $intCustomSize; ?>' height='<?php print $intCustomSize; ?>' />");
<?php
	}
	else
	{
?>
			$('#photo_preview_table').css('display', 'none');
<?php
	}
?>
		});
	</script>
</head>
<body>
	<script language="javascript">
	$.fn.extend({
		iframe: function(){
			var iframeDoc = this.contents()[0];
			iframeDoc.open();
			iframeDoc.write('<!doctype html><html><head></head><body></body></html>');
			iframeDoc.close();
			return this;
		}
	});
	$(document).ready(function () {
		$('#image_uploader_button').bind('click', function () {
			var domIframe = $('<iframe src="about:blank" class="browse_computer_getter"></iframe>')
			.appendTo('body')
			.css({
				position : 'absolute',
				opacity : 0,
				top : -10000,
				left : 0,
				'z-index' : 10000
			}).iframe();
			$(domIframe)
			.contents()
			.find('body')
			.append('<form enctype="multipart/form-data" method="post"></form>')
			.find('form')
			.attr('action', '<?php print WEB_ROOT; ?>imgs/uploadprocess2')
			.append('<input type="hidden" name="upload" value="true" />')
			.append('<input type="file" name="file" value="_" />')
			.find('input')
			.bind('change', function () {
				$(this).closest('form').trigger('submit');
				$('#image_uploader_button').val($('#image_uploader_button').attr('loading_msg'));
			})
			.trigger('click');
		});
	});
	function uploadSuccessCust(file, serverData) {
		$("#photo_upload_table").css("display", "none");
		$('#photo_preview_table').css('display', 'block');
		if ($("#photo_preview_image img").attr("src") != "<?php print WEB_ROOT; ?>/imgs/v/w/<?php print $intCustomSize; ?>/h/<?php print $intCustomSize; ?>src/" + serverData)
			$("#photo_preview_image").html("<img src='<?php print WEB_ROOT; ?>/imgs/v/w/<?php print $intCustomSize; ?>/h/<?php print $intCustomSize; ?>/src/" + serverData + "' border='0' width='<?php print $intCustomSize; ?>' height='<?php print $intCustomSize; ?>' />");
		$(".slider:last #<?php print $this->strResultID; ?>", top.document).val(serverData);
		top.$(".slider:last #<?php print $this->strResultID; ?>", top.document).trigger("updated");
		$("#uploader_start_buttons").css({"visibility" : "visible"});
	}
	function uploadStart(file) {
		$("#smalluploader #lefttext").html("Uploading Image...");
		$("#uploader_start_buttons").css({"visibility" : "hidden"});
		$('#fsUploadProgress').css({'display' : 'block'});
		$('#photo_upload_table').removeClass('photo_upload_table');
		return true;
	}

	function fn_change_image() {
		$('#fsUploadProgress').css({'display' : 'none'});
		$('#photo_preview_table').css('display', 'none');
		$('#photo_upload_table').css('display', 'block');
		$('#photo_upload_table').addClass('photo_upload_table');
		$("#smalluploader #lefttext").html("Upload Image");
		$(".slider:last #<?php print $this->strResultID; ?>", top.document).val('');
	}
	function fn_set_image(strImageSrc) {
		if (strImageSrc == "0.jpg")
			return fn_change_image();
		$('#photo_preview_table').css('display', 'block');
		$('#photo_upload_table').css('display', 'none');
		$("#photo_preview_image").html("<img src='<?php print WEB_ROOT; ?>/imgs/v/w/<?php print $intCustomSize; ?>/h/<?php print $intCustomSize; ?>/src/" + strImageSrc + "' border='0' width='<?php print $intCustomSize; ?>' height='<?php print $intCustomSize; ?>' />");
	}
	</script>
	<style>
		.photo_upload_table {
			padding: 8px 0 0 8px;
		}
		#lefttext {
			padding-bottom: 7px;
		}
		body {
			font-family:"Myriad Pro", Arial, Helvetica, sans-serif; font-size:17px; line-height:20px;
		}
	</style>
	<form method="post" id="smalluploader">
		<input type="hidden" id="uploader_photo_name" value="">
		<table cellpadding="0" cellspacing="0" border="0" id="photo_preview_table">
			<tr>
				<td style="text-align:center;vertical-align:middle" width="<?php print $intCustomSize; ?>" height="<?php print $intCustomSize; ?>" id="photo_preview_image"></td>
				<td style="padding-left: 4px"><input type="button" value="Change Image" id="image_uploader_button" /></td>
			</tr>
		</table>
	</form>
	</body>
</html>