<?php
	include "config.phtml";
	include "parameters.phtml";
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<HTML DIR="LTR">
<HEAD>
<LINK href="/css/back-end/login.css" rel="stylesheet" type="text/css">
<TITLE><?php print text("Login - Tzivos Hashem Management System"); ?></TITLE>
<script src="<?php print $sn; ?>/js/back-end/kiosk/jquery.core1.5.1.js" type="text/javascript"></script>
<script src="<?php print $sn; ?>/js/back-end/admin/jquery.dump.js" type="text/javascript"></script>
<SCRIPT type="text/javascript">
window.onload = scanFocus;
window.onkeydown = scanFocus;
function scanFocus() {
	$("#bar_code").focus();
}
/*
function eKeyPress(evt) {
	var charCode = (evt.which) ? evt.which : event.keyCode
	if (charCode == 13)
		$("form").trigger("submit");
}
*/
scanFocus();
$(document).ready(function() {
	$("form").submit(function(e) {
		e.preventDefault();
		if ($("#bar_code").val().length < 1)
		{
			$("#processing_status").html('<?php print text("Please try again."); ?>');
			return;
		}
		$.ajax({
			type : "POST",
			cache : false,
			start: $("#processing_status").html('<?php print text("Loading..."); ?>').fadeIn(),
			url : '<?php echo $sn . "/kiosk01/index" . $strParamPath; ?>',
			dataType : "text",
			data: $('form').serialize(),
			success : function(strResponse) {
				try {
					var arrResponse = jQuery.parseJSON(strResponse);
				} catch(e) {
					alert("<?php print text("Sorry, there was an error"); ?>: VKL-I101-3RR3RE");
					$.dumper(strResponse);
					return;
				}
				if (typeof(arrResponse) != "object") {
					alert("<?php print text("Sorry, there was an error"); ?>: VKL-I102-SDF8BX");
					$.dumper(strResponse);
					return;
				} else if (arrResponse["success"] == "true") {
					$("#processing_status").html('<?php print text("Authenticated. Please wait..."); ?>').delay(15000).queue(function() {
						$(this).dequeue().html("<?php print text("Still trying..."); ?>");
					});
					$("#processing_status").delay(30000).queue(function() {
						$(this).dequeue().html("<?php print text("There seems to be a connection issue."); ?>");
					});
					window.location.href = "<?php print $sn . "/kiosk01/profile" . $strParamPath; ?>";
				} else {
					$("#processing_status").html(arrResponse["error"]).delay(30000).fadeOut();;
					//$("#processing_status").html('Failed. Please try again.').delay(3000).fadeOut();;
				}
			}
		});
	});
});
</SCRIPT>
</HEAD>
<BODY class="kiosk">
	<DIV id="header">
		<DIV></DIV>
	</DIV>
	<DIV STYLE="text-align: center;">
		<NOSCRIPT>
			<P STYLE="color: red; font-size: larger;"><?php print text("Notice: You have javascript disabled. Some parts of the site will not function without javascript."); ?></P>
		</NOSCRIPT>

		<FORM>
			<DIV id="body" class="dayschool">
				<DIV>
					<INPUT type="text" name="bar_code" id="bar_code" size=25 maxlength=20 autocomplete="off">
					<p id="processing_status" style="display:none"></p>
				</DIV>
						<BR>
						<BR>
						<P>
						</P>
			</DIV>
		</FORM>
	</DIV>
</BODY>
</HTML>
