# CircleCI 2.0 configuration file for this project
version: 2

jobs:
  test-react:
    # use node js
    docker:
      - image: circleci/node:8.12
    
    # use the base-commander project as the working directory
    working_directory: ~/repo/base-commander
    
    steps:
      - checkout:
          path: ~/repo

      # cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      # Download dependencies
      - run: yarn install

      # Save the cache if it chages
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test

  test-php:
    # use php 7.2 for testing
    docker:
      - image: circleci/php:7.2-apache
    # do all the work in mashpia.com
    working_directory: ~/repo/mashpia.com
    # run the tests
    steps:
      - checkout:
          path: ~/repo
      # Download and cache dependencies
      - restore_cache:
          keys:
          - composer-v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - composer-v1-dependencies-
      # install required PHP extensions
      - run:
          name: Install PHP extensions
          command: |
            sudo docker-php-ext-install mysqli pcntl
            sudo docker-php-ext-enable mysqli pcntl
      # install the dependencies as fast as possible
      - run: composer install -n --prefer-dist
      # and save the cache
      - save_cache:
          paths:
            - vendor
          key: composer-v1-dependencies-{{ checksum "composer.json" }}
      # run tests in tests folder
      - run: phpunit tests

workflows:
  version: 2
  
  test:
    jobs:
      - test-php
      - test-react:
          requires:
            - test-php
