# CircleCI 2.0 configuration file for this project
version: 2

jobs:
  test-react:
    # use node js
    docker:
      - image: circleci/node:8.12
    
    # use the base-commander project as the working directory
    working_directory: ~/repo/base-commander
    
    steps:
      # attempt to load the repo from the cache
      - restore_cache:
          keys:
            - source-v1-{{ .Branch }}-{{ .Revision }}
            - source-v1-{{ .Branch }}-
            - source-v1-
      # checkout the code
      - checkout:
          path: ~/repo
      # save the code to the cache to speed up later steps
      - save_cache:
          key: source-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - "~/repo/.git"

      # cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      # Download dependencies
      - run: yarn install

      # Save the cache if it chages
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test

  test-php:
    # use php 7.2 for testing
    docker:
      - image: circleci/php:7.2-apache
    # do all the work in mashpia.com
    working_directory: ~/repo/mashpia.com
    # run the tests
    steps:
      # attempt to load the repo from the cache
      - restore_cache:
          keys:
            - source-v1-{{ .Branch }}-{{ .Revision }}
            - source-v1-{{ .Branch }}-
            - source-v1-
      # checkout the code
      - checkout:
          path: ~/repo
      # save the code to the cache to speed up later steps
      - save_cache:
          key: source-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - "~/repo/.git"

      # Download and cache dependencies
      - restore_cache:
          keys:
          - composer-v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - composer-v1-dependencies-
      # install required PHP extensions
      - run:
          name: Install PHP extensions
          command: |
            sudo docker-php-ext-install mysqli pcntl
            sudo docker-php-ext-enable mysqli pcntl
      # install the dependencies as fast as possible
      - run: composer install -n --prefer-dist
      # and save the cache
      - save_cache:
          paths:
            - vendor
          key: composer-v1-dependencies-{{ checksum "composer.json" }}
      # run tests in tests folder
      - run: ./vendor/bin/phpunit --bootstrap vendor/autoload.php tests
  
  build-react:
    # Use node to build the react client
    docker:
      - image: circleci/node:8.12
    # use the base-commander project as the working directory
    working_directory: ~/repo/base-commander

    steps:
      # attempt to load the repo from the cache
      - restore_cache:
          keys:
            - source-v1-{{ .Branch }}-{{ .Revision }}
            - source-v1-{{ .Branch }}-
            - source-v1-
      # checkout the code
      - checkout:
          path: ~/repo
      # save the code to the cache to speed up later steps
      - save_cache:
          key: source-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - "~/repo/.git"

      - attach_workspace:
          at: ~/repo

      # load cached dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      # run the build
      - run: yarn build:prod
      # save the results to the worksspace
      - persist_to_workspace:
          root: ~/repo
          paths:
            - base-commander/build/*

  # deploy build artifacts to staging
  deploy-staging:
    docker:
      - image: circleci/node:8.12
    # work in the repository
    working_directory: ~/repo
    
    steps:
      - attach_workspace:
          at: ~/repo
      
      - run:
           name: Add Test.Mashpia.com to known_hosts
           command: ssh-keyscan -H test.mashpia.com >> ~/.ssh/known_hosts

      - run:
          name: Send the react build Over SSH to deploy/build
          command: |
            scp -r build/* mashtest@test.mashpia.com:tzivos-hashem/deploy/build

      - run:
          name: Run the Deployment script
          command: |
            ssh mashtest@test.mashpia.com "./tzivos-hashem/deploy/deploy.sh"

  # deploy build artifacts to staging
  deploy-production:
    docker:
      - image: circleci/node:8.12
    # work in the repository
    working_directory: ~/repo
    
    steps:
      - attach_workspace:
          at: ~/repo
      
      - run:
           name: Add Mashpia.com to known_hosts
           command: ssh-keyscan -H mashpia.com >> ~/.ssh/known_hosts

      - run:
          name: Send the react build Over SSH to deploy/build
          command: |
            scp -r build/* mashpia@mashpia.com:tzivos-hashem/deploy/build

      - run:
          name: Run the Deployment script
          command: |
            ssh mashpia@mashpia.com "./tzivos-hashem/deploy/deploy.sh"

      

workflows:
  version: 2
  
  test-deploy:
    jobs:
      - test-php
      - test-react

      - build-react:
          requires:
            - test-php
            - test-react
          filters:
            branches:
              only:
                - master
                - staging

      - deploy-staging:
          requires:
            - build-react
          filters:
            branches:
              only:
                - staging

      - deploy-staging:
          requires:
            - build-react
          filters:
            branches:
              only:
                - master
