# CircleCI 2.0 configuration file for this project
version: 2

jobs:
  test-react:
    # use node js
    docker:
      - image: circleci/node:8.12
    
    # use the base-commander project as the working directory
    working_directory: ~/repo/base-commander
    
    steps:
      - checkout:
          path: ~/repo

      # cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      # Download dependencies
      - run: yarn install

      # Save the cache if it chages
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test

workflows:
  version: 2
  
  test:
    jobs:
      - test-react