<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>Mobile Web Site</title>
		<base href="http://mashpia.com/ckids/reg/" />
		<link href="<?php print css; ?>/missionsapp/reg_style.css" type="text/css" rel="stylesheet" />

        <link href="http://mashpia.com/ckids/reg/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
        <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
        <link href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet" type="text/css" />
        <link href="plugins/iCheck/all.css" rel="stylesheet" type="text/css" />
        <link href="dist/css/Tsivot-Mobile.css" rel="stylesheet" type="text/css" />
        <link href="dist/css/skins/skin-blue-Tsivot.css" rel="stylesheet" type="text/css" />

		<link href="css/responsive.css" type="text/css" rel="stylesheet" />
		<script src="js/jquery-1.9.1.min.js"></script>
		<script src="bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
		<style>
			.login-box {
				font-size: 18px;
			}
			.head {
				font-size: 28px;
				font-weight: bold;
				text-align: center;
				padding-top: 20px;
			}
		</style>
        <script>
            $(document).ready( function() {
            	$(".signUp").click( function() {
            		window.location.href = "<?php print bp; ?>/missionsapp/register";
            	});
            	$(".login").click( function() {
            		window.location.href = "<?php print bp; ?>/missionsapp/login";
            	});
            });
        </script>
	</head>
	<body>
        <div class="container login-page">
            <div class="span12 body">
            	<div class="login-box">
                    <div class="head">
                    	WELCOME
                    </div>
               </div>
                <div class="logo" style="margin-top: 0;">
                    <img style="max-width:340px;" src="http://v2.mashpia.com/imgs/v/w/340/src/4003836_15208.gif" class="img-responsive center-block">
                </div>
                <div class="login-box">
                    <div class="login-box-body">
						<div class="row">
							<div class="col-xs-6">
                                <button class="btn btn-primary btn-block signUp"><b>SIGN UP</b></button>
                            </div><!-- /.col -->
                            <div class="col-xs-6">
                                <button class="btn btn-primary btn-block login"><b>LOGIN</b></button>
                            </div><!-- /.col -->
                        </div>
						<br /><br />
	                	Tzivos Hashem CKids is the Jewish boys’ and girls’ brigade of Hashem's (G-d’s) army,
	                	made up of kids just like yourself, who do acts of kindness,
	                	show care and concern for others, learn Torah and fulfill mitzvot (good deeds).
						<br /><br />
						When you enroll in Tzivos Hashem, you start out as a Private,
						but as you do more good deeds and complete missions, you’ll earn Mitzva badges.
						After collecting enough badges, you’ll be awarded medals. When you get enough medals,
						you’ll be promoted in rank. If you keep working at it, you just might become a general!
						<br /><br />

	                </div>
	        	</div>
            </div>
        </div>
	</body>
</html>