<!DOCTYPE html>

<html>
	<head>
		<base href="http://mashpia.com/ckids/reg/" />
		<meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>Mobile Web Site</title>
        <link href="<?php print css; ?>/missionsapp/bootstrap.css" rel="stylesheet" type="text/css" />
        <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
        <link href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet" type="text/css" />
        <link href="plugins/iCheck/all.css" rel="stylesheet" type="text/css" />
        <link href="dist/css/Tsivot-Mobile.css" rel="stylesheet" type="text/css" />
        <link href="dist/css/skins/skin-blue-Tsivot.css" rel="stylesheet" type="text/css" />

		<link href="<?php print css; ?>/missionsapp/reg_style.css" type="text/css" rel="stylesheet" />

		<link href="css/responsive.css" type="text/css" rel="stylesheet" />
		<script src="js/jquery-1.9.1.min.js"></script>
		<script src="bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
        <script src="plugins/iCheck/icheck.min.js" type="text/javascript"></script>
        <script>
            $(function () {
                $('input').iCheck({
                    checkboxClass: 'icheckbox_square-blue',
                    radioClass: 'iradio_square-blue',
                    increaseArea: '20%' // optional
                });
            });
        </script>
        <script src="js/js.cookie.js"></script>
        <script>
            $(document).ready( function() {
            	//check for connected cookie
            	if (Cookies.get('isconnected')) {
            		window.location = "parent_detail.html";
            	}

                $( "#loginForm" ).submit(function( event ) {
                    event.preventDefault();
					$(".error-box").hide();
                    var $form = $( this ),
                        barcode = $form.find( "input[name='pwd']" ).val();
					$.ajax({
						type : "POST",
						cache : false,
						url : "<?php print bp; ?>/missionsapp/login",
						data : {
							bar_code : barcode
						},
						success : function(strResponse) {
							try {
								var arrResponse = jQuery.parseJSON(strResponse);
							} catch(e) {
								$.alert(strResponse);
								alert("Unexpected error: MG23m3f3kw");
								return;
							}
							if (typeof(arrResponse) != "object") {
								alert("Unexpected error: GDs3mo3k0w");
								$.alert(strResponse);
								return;
							}
							else if (arrResponse["success"] == "true")
							{
								window.location.href = "<?php print bp; ?>/missionsapp/missions/bc/" + barcode;
							}
							else if (arrResponse.error)
							{
								$(".error-box").show();
							}
							else
							{
								alert("Unexpected error: DFlmsdfk323");
								//$.alert(strResponse);
								return;
							}
						}
					});

                    /*$.post('ajax/auth.php', {
                    	username : login,
                    	password : pwd
                    }, function( success ) {
                    	if ( success > 0 ) {
                    		//check for 'remember me'
                    		if ($(".remember input").is(":checked")) {
                    			Cookies.set('isconnected', 'true', { expires: 365 });
                    		} else {
                    			Cookies.set('isconnected', 'true', { expires: 1 });
                    		}
                    		Cookies.set('admin', success, { expires: 1 });
                    		window.location = "parent_detail.html";
                    	} else {
                    		$(".error-box").show();
                    	}
                    });*/

                });
            });
        </script>
	</head>
	<body>
        <div class="container login-page">
            <div class="login-header">
                <span class="span12">MISSIONS LOGIN</span>
            </div>
            <div class="span12 body">
                <div class="logo">
					<img style="max-width:340px;" src="http://v2.mashpia.com/imgs/v/w/340/src/4003836_15208.gif" class="img-responsive center-block">
                </div>
                <div class="login-box">
                    <div class="login-box-body">
                        <form id="loginForm">
                            <div class="form-group has-feedback" id="divpwd" >
                                <div class="input-group">
                                    <span class="input-group-addon"><span class="glyphicon glyphicon-lock "></span></span>
                                    <input id="pwd" name="pwd" type="text" class="form-control" placeholder="My Serial Number" required/>
                                </div>
                            </div>
                            <!--
                            <div class="row">
                                <div class="col-xs-12">
                                    <div class="form-group no-border remember">
                                        <label>
                                            <input type="checkbox" class="flat-red" />
                                            <span>&nbsp; remember me </span>
                                        </label>
                                    </div>
                                </div><!-- /.col
                            </div>-->
                            <div class="row">
                                <div class="col-xs-12">
                                    <button type="submit" class="btn btn-primary btn-block H8"><b>LOGIN</b></button>
                                </div><!-- /.col -->
                            </div>
                        </form>
                        <br>
                        <!--div class="row">
                            <div class="col-xs-7 forgot">
                                <div class="error-change"><a href="forgot.html">Forgot your number?</a></div>
                                <div class="error-box" style="display: none;"><img src="images/error.png" width="16%"><span class="color-red"><b>oops!</b></span></div>
                            </div>
                            <!--
                            <div class="col-xs-5 text-right create-account">
                                <a href="parent_register.html" ><b>Create account</b></a>
                            </div>
                            -->
                        </div-->
                        <div class="row" id="error-block">
                            <div class="col-sm-12 error-box" style="display: none;">
                                <span class="color-grey">The</span>
                                <span class="color-red">bar code</span>
                                <span class="color-grey">you entered is</span>
                                <span class="color-red">incorrect.</span></br>
                                <span class="color-grey">Please try again.</span>
                            </div>
                        </div>
                    </div>

                </div>

            </div>
        </div>
	</body>
</html>