<?php
function fix_date_format($strInput) {
	$arrDate = preg_split('/ *[\/\\\\-|] */', $strInput);
	if (count($arrDate) != 3)
		return "";
	list ($strMonth, $strDay, $strYear) = $arrDate;
	$arrMonths = array("January","February","March","April","May","June","July","August","September","October","November","December");
	return $strDay . " " . $arrMonths[$strMonth*1-1] . " " . $strYear;
}
?>
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>New Registration</title>
	 <base href="http://mashpia.com/ckids/reg/" />
      <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>


      <link href="<?php print css; ?>/missionsapp/bootstrap.css" rel="stylesheet" type="text/css" />
      <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
      <link href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet" type="text/css" />
      <link rel="stylesheet" href="plugins/bootstrap-select/dist/css/bootstrap-select.css">
      <link href="plugins/iCheck/all.css" rel="stylesheet" type="text/css" />
      <link href="plugins/bootstrap-fileinput/css/fileinput.min.css" media="all" rel="stylesheet" type="text/css" />
      <link href="dist/css/Tsivot-Mobile.css" rel="stylesheet" type="text/css" />
      <link href="dist/css/skins/skin-blue-Tsivot.css" rel="stylesheet" type="text/css" />
      <link href="<?php print css; ?>/missionsapp/reg_style.css" type="text/css" rel="stylesheet" />
      <link href="css/responsive.css" type="text/css" rel="stylesheet" />
      <script src="js/jquery-1.9.1.min.js"></script>


<?php
	if (is_dev())
	{
?>


	<script type="text/javascript" src="//v2dev1.mashpia.com/js/back-end/admin/jquery.dump.js"></script>
<?php
	}
?>
      <!--[if lt IE 9]>
      <script src="http://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="http://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
      <![endif]-->
      <style>
      	  .login-box {
      	  	font-size: 28px;
      	  	font-weight: bold;
      	  }
      	  .agree-terms {
      	  	font-size: 16px !important;
      	  }
		  .row.display-error .with-errors {
			  display:none;
		  }
		  .with-errors li {
			  padding-left:10px;
			  font-weight: bold;
			  font-size:10pt;
			  color:#A94442;
		  }
		  .row.display-error .with-errors {
			  display: block;
		  }
		  .form-group.success {
				border-color:#3c763d;
				-webkit-box-shadow:inset 0 1px 1px rgba(0,0,0,.075);
				box-shadow:inset 0 1px 1px rgba(0,0,0,.075)
		  }
		  .form-group.success .input-group-addon {
			  border-right:2px solid #3c763d;
		  }
      </style>
	  <script src="plugins/bootstrap-select/dist/js/bootstrap-select.js"></script>
    <script src="plugins/validator/validator.min.js" type="text/javascript"></script>
	<script src="plugins/input-mask/jquery.inputmask.js" type="text/javascript"></script>
    <script src="plugins/input-mask/jquery.inputmask.date.extensions.js" type="text/javascript"></script>
    <script src="plugins/input-mask/jquery.inputmask.extensions.js" type="text/javascript"></script>

    <script src="plugins/bootstrap-fileinput/js/fileinput.min.js" type="text/javascript"></script>
    <script type="text/javascript" src="bootstrap/js/transition.js"></script>
    <script type="text/javascript" src="bootstrap/js/collapse.js"></script>


<script type="text/javascript" src="plugins/moment/moment.js"></script>
<script type="text/javascript" src="plugins/moment/bootstrap-datetimepicker.js"></script>
<script src="plugins/bootstrap-fileinput/js/fileinput_locale_fr.js"></script>
<script src="plugins/iCheck/icheck.min.js" type="text/javascript"></script>
<script src="bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
<script>
$(document).ready(function(){

	<?php
	if (dev && $this->objUser)
		print "\n//" . $this->objUser->user_id . "\n\n";
	if (!$this->objOrder)
		print "$('#cardAddress').hide();\n";

?>

	$('input').iCheck({
		checkboxClass: 'icheckbox_square-blue',
		radioClass: 'iradio_square-blue',
		increaseArea: '20%' // optional
	});
    //Red color scheme for iCheck
    $('input[type="checkbox"].minimal-red, input[type="radio"].minimal-red').iCheck({
       checkboxClass: 'icheckbox_minimal-red',
       radioClass: 'iradio_minimal-red'
    });
    $("input[name='gender']").on('ifChecked', function() {
		if ($('#imageservername').val().length)
			return;
    	if ($(this).val() == 'B')
    		$("#imgchild").attr('src', 'images/father-3.png');
    	else if ($(this).val() == 'G')
    		$("#imgchild").attr('src', 'images/mother-3.png');
    });
    $(".base").hide();
    $(".byZip").hide();

    $(".remember input").on('ifChecked', function() {
		$(".base").show();
		$(".nearestBase input").iCheck('uncheck');
	});
	$(".remember input").on('ifUnchecked', function() {
		$(".base").hide();
	});
	$(".nearestBase input").on('ifChecked', function() {
		var zip = $("#zip").val();
		if (zip != '') $("#baseZip").val( zip );
		$(".byZip").show();
		$(".remember input").iCheck('uncheck');
	});
	$(".nearestBase input").on('ifUnchecked', function() {
		$(".byZip").hide();
	});
	$(".memb input").on('ifChecked', function() {
		$("#cardAddress").show();
	});
	$(".memb input").on('ifUnchecked', function() {
		$("#cardAddress").hide();
	});

	$("#newMember").submit( function(e) {
		e.preventDefault();
		$('.has-feedback.has-error').closest('.row').find('.help-block li').text("");
		$('.has-feedback.has-error').removeClass('has-error');
		$.ajax({
			type : "POST",
			cache : false,
			url : "<?php print bp . "/missionsapp/register" . ($this->bc ? "/bc/" . $this->bc : ""); ?>",
			data : $("#newMember").serialize(),
			success : function(strResponse) {
				try {
					var arrResponse = jQuery.parseJSON(strResponse);
				} catch(e) {
					$.alert(strResponse);
					alert("Unexpected error: MG23m3f3kw");
					return;
				}
				if (typeof(arrResponse) != "object") {
					alert("Unexpected error: GDs3mo3k0w");
					$.alert(strResponse);
					return;
				}
				else if (arrResponse["success"] == "true")
				{
					if (arrResponse["go_to_mission"])
						window.location.href = "<?php print bp; ?>/missionsapp/missions/bc/" + arrResponse["bar_code"];
					else
						window.location.href = "<?php print bp; ?>/missionsapp/card/code/" + arrResponse["pass"] + "/bc/" + arrResponse["bar_code"];
				}
				else if (arrResponse.error)
				{
					//$.alert(arrResponse);
					var objItem = $("#div" + arrResponse.item);
					if (!objItem.length) {
						alert("Unexpected error: GE1f1ffasf");
						return;
					}
					objItem.find(".has-feedback").addClass('has-error');
					objItem.find('.help-block li').text(arrResponse.error);
					objItem.find('input:first').focus();
				}
				else
				{
					alert("Unexpected error: DFlmsdfk323");
					//$.alert(strResponse);
					return;
				}
			}
		});
	});
	$(".has-feedback input").bind('change',function () {
		if ($(this).closest('.has-feedback.has-error').length) {
			$('.has-feedback.has-error').closest('.row').find('.help-block li').text("");
			$('.has-feedback.has-error').removeClass('has-error');
		}
	});

	//-------------------
	var $input = $('#imagechild');
	$("#imagechild").fileinput({
		showPreview: false,
		showCancel: false,
		showUploadedThumbs: false,
		showcaption: false,
		showUpload: false,
		showRemove: false,
		uploadAsync : false,
		allowedFileExtensions : ['jpg', 'png', 'gif'],
		uploadUrl: "<?php print bp; ?>/missionsapp/register", // your upload server url
		minFileCount: 1,
		maxFileCount: 1,
		uploadExtraData: function() {   // pour le futur...
			return {
				action: 'inputimg'
			};
		}
	}).on("filebatchselected", function(event, files) {
		// trigger upload method immediately after files are selected
		$input.fileinput("upload")
		.on('filebatchuploadsuccess', function(event, data, previewId, index) {
			var form = data.form,
			files = data.files,
			extra = data.extra,
			response = data.response,
			reader = data.reader;
			//$.alert(response);
			$("#imageservername").val(data.response.name);
			$("#imgchild").attr('src',"<?php print bp; ?>/imgs/v/w/156/h/156/src/" + data.response.name);

		})
		.on('filebatchuploaderror', function (event, data, previewId, index) {
			alert(data.response.error);
		});
	});
	$('#dob').datetimepicker({
		defaultDate: "<?php if (isset($this->objUser)) print $this->objUser->dob; ?>"
	});
	$('#dob').data("DateTimePicker").format('DD MMMM YYYY');
	$('#dob').data("DateTimePicker").options({showClose:true});
	$('#firstname').focus();
});
</script>
</head>
<body class="skin-blue sidebar-mini">
<div class="container register-page">
  <div class="login-header">
      <span class="span12"><?php print isset($this->objUser) ? "EDIT PROFILE" : "NEW REGISTRATION"; ?></span>
  </div>
  <div class="register-box">
      <div class="register-box-body">
        <form  method="post" id="newMember" enctype="multipart/form-data">
			<input type="hidden" name="action" value="registration" />
      <div class="row">
          <div class="col-xs-12">
              <div class="image-upload">
                  <label for="imagechild" style="display: inline;">
                      <img id="imgchild" src="<?php if (isset($this->objUser)) print bp."/imgs/v/w/160/h/160/src/".(empty($this->objUser->image_id) ? "0.gif" : $this->objUser->image_id); else print "images/father-3.png"; ?>" class="img-people"  data-toggle="tooltip" title="Click here to load child's picture"/>
                  </label>
                  <input id="imagechild" name="image" type="file" multiple class="file-loading" >
				  <input id="imageservername" name="image_name" type="hidden" value="<?php if (isset($this->objUser)) print empty($this->objUser->image_id) ? "0.gif" : $this->objUser->image_id; ?>" />
              </div>
          </div>
      </div>
      <div class="row" id="divgender">
          <div class="col-xs-12">
              <div class="form-group no-border has-feedback" style="text-align: center;margin-bottom: -10px;" >
                  <div style ='display: inline-block'>
                      <label >
                          <input <?php if (isset($this->objUser) && $this->objUser->gender=="M") print "checked"; ?> type="radio" name="gender" class="flat-red" value="B"/>
                          Boy&nbsp;&nbsp;
                      </label>
                      <label >
                          <input <?php if (isset($this->objUser) && $this->objUser->gender=="F") print "checked"; ?> type="radio" name="gender" class="flat-red" value="G" />
                          Girl
                      </label>
                  </div>
              </div>
			  <div class="help-block with-errors">
				  <ul class="list-unstyled">
					  <li></li>
				  </ul>
			  </div>
          </div>
      </div>
      <div class="row" id="divfirstname">
          <div class="col-xs-12">
              <div class="form-group has-feedback">
                  <div class="input-group">
                      <span class="input-group-addon"><span class="glyphicon glyphicon-user "></span></span>
                      <input id="firstname" name="firstname" type="text" class="form-control" placeholder="First Name" value="<?php if (isset($this->objUser)) print $this->objUser->first_name; ?>" />
                  </div>
              </div>
			  <div class="help-block with-errors">
				  <ul class="list-unstyled">
					  <li></li>
				  </ul>
			  </div>
          </div>
      </div>
      <div class="row display-error" id="divlastname">
          <div class="col-xs-12">
              <div class="form-group has-feedback">
                  <div class="input-group">
                      <span class="input-group-addon"><span class="glyphicon glyphicon-user "></span></span>
                      <input id="lastname" name="lastname" type="text" class="form-control" placeholder="Last Name" value="<?php if (isset($this->objUser)) print $this->objUser->last_name; ?>" />
                  </div>
              </div>
			  <div class="help-block with-errors">
				  <ul class="list-unstyled">
					  <li></li>
				  </ul>
			  </div>
          </div>
      </div>

      <div class="row" id="divdob">
          <div class='col-xs-12'>
              <div class="form-group has-feedback">
                  <div class="input-group">
                      <span class="input-group-addon"><span class="glyphicon glyphicon-calendar "></span></span>
                      <input type='text' name="dob" class="form-control" id='dob' placeholder="English Date of Birth" value="<?php if (isset($this->objUser)) print $this->objUser->dob; ?>" />
                  </div>
              </div>
			  <div class="help-block with-errors">
				  <ul class="list-unstyled">
					  <li></li>
				  </ul>
			  </div>
          </div>
      </div>

      <div class="row" id="divemail1">
          <div class="col-xs-12">
              <div class="form-group has-feedback">
              	  <div class="input-group">
                  	  <span class="input-group-addon"><span class="fa fa-envelope-o"></span></span>
                      <input id="email1" name="email1" type="text" class="form-control" placeholder="Parent Email" value="<?php if (isset($this->objUser)) print $this->objUser->student_email; ?>" />
                  </div>
              </div>
			  <div class="help-block with-errors">
				  <ul class="list-unstyled">
					  <li></li>
				  </ul>
			  </div>
          </div>

      </div>

      <div class="row" id="divemail2">
          <div class="col-xs-12">
              <div class="form-group has-feedback">
              	  <div class="input-group">
                  	  <span class="input-group-addon"><span class="fa fa-envelope-o"></span></span>
                      <input id="email2" name="email2" type="text" class="form-control" placeholder="Confirm Email" />
                  </div>
              </div>
			  <div class="help-block with-errors">
				  <ul class="list-unstyled">
					  <li></li>
				  </ul>
			  </div>
          </div>
      </div>

      <div class="row" id="divphone">
          <div class="col-xs-12">
              <div class="form-group has-feedback">
                  <div class="input-group">
                      <span class="input-group-addon"><span class="fa fa fa-pencil  "></span></span>
                      <input id="phone" name="phone" type="text" class="form-control" placeholder="Parent's Phone Number" value="<?php if (isset($this->objUser)) print $this->objUser->phone; ?>" />
                  </div>
              </div>
			  <div class="help-block with-errors">
				  <ul class="list-unstyled">
					  <li></li>
				  </ul>
			  </div>
          </div>
      </div>

      <br />

      <div class="row">
          <div class="col-xs-12">
              <div class="login-box">
                    Notifications
          	   </div>
          </div>
      </div>

      <div class="row">
        <div class="col-xs-12">
            <div class="form-group no-border" style="height: auto;">
                <table>
                    <tr>
                        <td><input type="checkbox" name="send_email"<?php if (isset($this->objPermission)) print $this->objPermission->email_notification == "1" ? " checked" : ""; ?> value="1" class="flat-red" /></td>
                        <td><label class="agree-terms">&nbsp; Please email me when new missions are available or due.</label></td>
                    </tr>
                </table>
            </div>
        </div>
     </div>

     <br />

     <div class="row">
          <div class="col-xs-12">
              <div class="login-box">
                    Membership Card
          	   </div>
          </div>
      </div>

     <div class="row">
        <div class="col-xs-12">
            <div class="form-group no-border memb" style="height: auto;">
                <table>
                    <tr>
                        <td><input type="checkbox" value="" name="send_card"<?php if ($this->objOrder) print " disabled checked"; ?> value="1" class="flat-red" /></td>
                        <td><label class="agree-terms">&nbsp; Yes, please send me a Free Membership Card!</label></td>
                    </tr>
                </table>
            </div>
        </div>
     </div>

     <br />
	<div class="row">
		<div class="col-xs-12">
			<label><?php
	if ($this->objOrder)
	{
		if ($this->objOrder->order_status == "ordered")
			print "Card not printed yet";
		else if ($this->objOrder->order_status == "printed")
			print "Card has been printed";
		else if ($this->objOrder->order_status == "sent")
			print "Card has been shipped";
	}

?></label>
		</div>
	</div>

     <div id="cardAddress">
	     <div class="row" id="divaddress">
	          <div class="col-xs-12">
	              <div class="form-group has-feedback">
	                  <div class="input-group">
	                      <span class="input-group-addon"><span class="fa fa-home "></span></span>
	                      <input id="address" name="address" value="<?php if (isset($this->objUser)) print $this->objUser->address; ?>" type="text" class="form-control" placeholder="Home Address" />
	                  </div>
	              </div>
					<div class="help-block with-errors">
						<ul class="list-unstyled">
							<li></li>
						</ul>
					</div>
	          </div>
	      </div>
	      <div class="row" id="divcity">
	          <div class="col-xs-12">
	              <div class="form-group has-feedback">
	                  <div class="input-group">
	                      <span class="input-group-addon"><span class="fa fa-pencil "></span></span>
	                      <input id="city" name="city" value="<?php if (isset($this->objUser)) print $this->objUser->city; ?>" type="text" class="form-control" placeholder="City" />
	                  </div>
	              </div>
					<div class="help-block with-errors">
						<ul class="list-unstyled">
							<li></li>
						</ul>
					</div>
	          </div>
	      </div>
	      <div class="row">
	          <div class="col-xs-6" id="divstate">
	              <div class="form-group has-feedback">
	                  <div class="input-group">
	                      <span class="input-group-addon"><span class="glyphicon glyphicon-user "></span></span>
	                      <input id="state" name="state" value="<?php if (isset($this->objUser)) print $this->objUser->state; ?>" type="text" class="form-control" placeholder="State" />
	                  </div>
	              </div>
					<div class="help-block with-errors">
						<ul class="list-unstyled">
							<li></li>
						</ul>
					</div>
	          </div>
	          <div class="col-xs-6" id="divzip">
	              <div class="form-group has-feedback">
	                  <div class="input-group">
	                      <span class="input-group-addon"><span class="fa fa fa-pencil  "></span></span>
	                      <input id="zip" name="zip" value="<?php if (isset($this->objUser)) print $this->objUser->postal; ?>" type="text" class="form-control" placeholder="Zip Code" />
	                  </div>
	              </div>
					<div class="help-block with-errors">
						<ul class="list-unstyled">
							<li></li>
						</ul>
					</div>
	          </div>
	      </div>
	      <div class="row" id="divcountry">
	          <div class="col-xs-12">
	              <div class="form-group has-feedback">
	                  <div class="input-group">
	                      <span class="input-group-addon"><span class="fa fa fa-pencil  "></span></span>
	                      <input id="country" name="country" value="<?php if (isset($this->objUser)) print $this->objUser->country; ?>" type="text" class="form-control" placeholder="Country" />
	                  </div>
	              </div>
					<div class="help-block with-errors">
						<ul class="list-unstyled">
							<li></li>
						</ul>
					</div>
	          </div>
	      </div>
	  </div>

      <!--div class="row">
          <div class="col-xs-12">
              <div class="login-box">
                    Join a CKids Base!
          	   </div>
          </div>
      </div>

      <div class="row">
            <div class="col-xs-12">
                <div class="form-group no-border remember" style="height: auto;">
                    <table>
                        <tr>
                            <td><input type="checkbox" class="flat-red" /></td>
                            <td><label class="agree-terms">&nbsp; I already belong to a CKids Base</label></td>
                        </tr>
                    </table>
                    <div class="input-group base">
                      <span class="input-group-addon"><span class="fa fa-university "></span></span>
                      <select id="school" name="school" class="selectpicker show-tick form-control"  data-style="btn-default">
                      </select>
                  	</div>
                </div>
                <div class="form-group no-border nearestBase" style="height: auto;">
                  	<table>
                        <tr>
                            <td><input type="checkbox" class="flat-red" /></td>
                            <td><label class="agree-terms">&nbsp; Please connect me with information about the CKids base nearest me!</label></td>
                        </tr>
                    </table>
                    <div class="input-group byZip">
                      <span class="input-group-addon"><span class="fa fa-university "></span></span>
                      <input id="baseZip" name="baseZip" type="text" class="form-control" placeholder="Zip" />
                  	</div>
                </div>
            </div>
        </div-->

        <br />

        <div class="row">
            <div class="col-xs-12">
                <button type="submit" id="btn_create" class="btn btn-primary btn-block H8">
                    <b><?php print isset($this->objUser) ? "SAVE" : "SIGN UP"; ?></b>
                </button>
            </div><!-- /.col -->
        </div>
      </form>

      </div><!-- /.form-box -->
    </div><!-- /.register-box -->
	</div><!-- wrapper  -->
</body>
</html>