<?php
if($this->rules->response_code == 0) { 
	echo "error::" . $this->rules->response;
}else{?>
	<? foreach ($this->arrCartItems as $cartItem) : ?>
		<div class="cart_item" name="cart_item_<?=$cartItem->prize_id;?>" id="cart_item_<?=$cartItem->prize_id;?>">
			<div class="cart_item_image">							
				<div class="badge" name="badge">
					<?=$cartItem->quantity;?>
				</div>
				<!--<img height="48" width="48" alt="" src="/file_view.php?id=3346916422">-->
				<img src="/images/show-image/image_id/<?=$cartItem->image_id;?>" width="48" height="48" alt="">
			</div>								
		</div>
	<? endforeach; ?>
	[SPLIT1]
	<? foreach ($this->arrCartItems as $cartItem) : ?>
		<div class="pane_item" name="pane_item_<?=$cartItem->prize_id;?>" id="pane_item_<?=$cartItem->prize_id;?>">
			<div class="pane_item_image">
				<div class="badge" name="badge" id="badge">
					<?=$cartItem->quantity;?>
				</div>
				<!--<img height="100" width="100" src="/file_view.php?id=3346916422">-->
				<img src="/images/show-image/image_id/<?=$cartItem->image_id;?>" width="100" height="100" alt="">            
			</div>
			
			<div class="pane_item_title">
				<?=$cartItem->prize_name;?>
			</div>
		</div>    
	<? endforeach; ?>
	[SPLIT2]<?=$this->current_balance;?>
<?php } ?>
