<?php
include "config.phtml";
include "application/views/scripts/includes/headers/kiosk_header.phtml";
?>

<body class="blue">

    <div id="wrapper">
		
        <div id="header">
			<?php include "application/views/scripts/includes/topbar.phtml"; ?>
        </div>
		
        <div id="main">
			
            <div id="page_title">
				Enrollment
			</div>
			
            <div class="three_column padding_top">
				
				<div class="content">
					
                    <div id="slider">
						
						<ul class="enroll">
							
                            <li>
								
                                <div class="slider_title">
									<?php echo $this->objCampaign->campaign_name; ?>'s Commitment
								</div>
								
                                <div class="scroll-pane">
									
                                    <form>
										
										<div class="mainbox">
											
											<div class="col2_image iconl_child">												
											</div>
											
											<div class="col2_text">I commit to:
												<div class="col2_list">
													<?php echo $this->objCampaign->commitments; ?>
												</div>
											</div>
											
											<div class="clear">												
											</div>
											
											<div class="buttons_bar">
												<div class="button button_icons">
													<div>
														<a href="<?php echo $sn . '/kiosk/campaigns'; ?>" class="icon_check">
															Cancel
														</a>
													</div>
												</div>
												
												<div class="button button_icons">
													<div>
														<a href="<?php echo $sn . '/kiosk/campaignenrollthree/campaign_id/' . $this->intCampaignId;?>" class="icon_check">
															Enroll Now
														</a>
													</div>
												</div>
											</div>
											
										</div>
										
                                    </form>
									
                                </div>
								
                            </li>
							
						</ul>
						
                    </div>
					
				</div>
				
            </div>
			
        </div>
		
        <div id="footer">
			<?php include "application/views/scripts/includes/bottombar.phtml"; ?>
		</div>
		
    </div>
	
</body>

<?php include "application/views/scripts/includes/footer.phtml"; ?>
