<?php 
	include "config.phtml";
	include "parameters.phtml";
?>
<div class="slider">
	<div class="col_title">
		<span>Report Users</span>
	</div>
	<div class="col_content">
<?php
	if (!count($this->arrUsers))
	{
?>
		<div class="module" style="padding:5px;">
			There are no Users available to display.
		</div>
<?php
	}
	else
	{
?>
		<div id="lists" class="module lists forms">
			<div class="module_content">
				<ul>
					<li>
						<a class="link" href="<?php print $sn . "/reports/reportcampaigns" . $strParamPath; ?>">
							<div class="icon"></div>
							<div class="title">> View Report for Class</div>
						</a>
					</li>
<?php 
		foreach ($this->arrUsers as $objUser)
		{
?>
					<li>
						<a class="link" href="<?php print $sn . "/reports/reportcampaigns/user_id/" . $objUser->user_id . $strParamPath; ?>">
							<div class="icon"></div>
							<div class="title"><?php print $objUser->last_name?>, <?php print $objUser->first_name?></div>
						</a>
					</li>
<?php		
		}
?>
				</ul>
			</div>
		</div>
<?php
	}
?>
	</div>
</div>