<?php
	include "config.phtml";
	include "parameters.phtml";
	$user_session_data = new Zend_Session_Namespace("user_session_data");
	$arrCategories = array(
		'Checked Out' => "Unprinted Vouchers",
		'Printed' => "Printed Vouchers",
		'Redeemed' => "Redeemed Items"
	);
?>
<script>
$(document).ready(function()
{
	$(".slider:last .print_button").click(function () {
		slideRefresh("<?php print $sn; ?>/orders/orderseditor");
	});
});
function orders_redeem(objForm)
{
	$.ajax({
		type : "POST",
		cache : false,
		start: $(objForm).find("#processing_status").stop().fadeIn("slow"),
		url : "<?php print $sn;?>/orders/orderseditor",
		dataType : "text",
		data: $(objForm).serialize(),
		success : function(strResponse)
		{
			if (strResponse == "1")
				slideRefresh("<?php print $sn; ?>/orders/orderseditor");
		}
	});
}
function row_toggle(objThis)
{
	$(objThis).find(":checkbox").attr("checked", !$(objThis).find(":checkbox").is(':checked'));
	$(objThis).css("background-color", $(objThis).find(":checkbox").is(':checked') ? "#dadee6" : "#e8eaef");
}
function uncheckall(objThis)
{
	$(objThis).closest(".module_collection").find(":checkbox").attr("checked", false);
	$(objThis).closest(".module_collection").find(".module table .row").css("background-color", "#e8eaef");
}
function checkall(objThis)
{
	$(objThis).closest(".module_collection").find(":checkbox").attr("checked", true);
	$(objThis).closest(".module_collection").find(".module table .row").css("background-color", "#dadee6");
}
</script>
<div class="slider" id="slider_orderslist">
	<div class="col_title">
		<span>Orders</span>
	</div>
	<div class="col_content">
<?php
	foreach ($arrCategories as $strStatus => $strTitle)
	{
?>
		<h2><?php print $strTitle; ?></h2>
<?php
		if (
			!isset($this->arrOrders[$strStatus])
			|| !count($this->arrOrders[$strStatus])
		) {
?>
		<div class="module" style="padding:5px;">
			Nothing to display.
		</div>
<?php
		}
		else
		{
?>			<div class="module_collection">
				<form method="post" action="<?php print $sn; ?>/orders/ordersprintvouchers" target="_blank">
					<div style="margin-bottom:4px"><table width="96%" cellpadding="4" cellspacing="4"><tr><td>&nbsp;</td><td width="60"><span><a onclick="checkall(this)" href="#" title="Check All" class="button">Check All</a></span></td><td width="6">&nbsp;</td><td width="60"><span><a onclick="uncheckall(this)" href="#" title="Uncheck All" class="button">Uncheck All</a></span></td></tr></table></div>
					<div class='module' style='margin-bottom:6px !important'><table border='1' width='100%' style='margin-bottom:5px'>
					<tr>
						<td style='padding:4px'>&nbsp;</td>
						<td><b>Date</b></td>
						<td><b>Student</b></td>
						<td><b>Prize</b></td>
						<td><b>Prize Size</b>&nbsp;</td>
						<td align='right'><b>Quantity</b>&nbsp;</td>
					</tr>
<?php
			foreach ($this->arrOrders[$strStatus] as $arrOrderData)
			{
?>
					<tr class="row" style="background-color:#e8eaef; cursor:default;" onclick="row_toggle(this);">
						<td width="30" style="padding:4px"><input type="checkbox" onclick="this.checked = this.checked ? 0 : 1;" name="<?php print $arrOrderData["objUserPrize"]->user_prize_id; ?>" value="1" /></td>
						<td width="160"><?php print $arrOrderData["objUserPrize"]->modified != '0000-00-00 00:00:00' ? $arrOrderData["objUserPrize"]->modified : $arrOrderData["objUserPrize"]->created; ?></td>
						<td><?php print $arrOrderData["objUser"]->first_name . " " . $arrOrderData["objUser"]->last_name; ?></td>
						<td><?php print $arrOrderData["objPrize"]->prize_name; ?></td>
						<td width="100"><?php print $arrOrderData["objUserPrize"]->prize_size; ?></td>
						<td width="30"><?php print $arrOrderData["objUserPrize"]->quantity; ?></td>
					</tr>
<?php
			}
?>
					</table></div>
					<div style="margin-bottom:4px"><div id="processing_status"></div><table width="96%" cellpadding="4" cellspacing="4"><tr><td>&nbsp;</td>
<?php
			if ($strStatus != "Redeemed")
			{
?>
					<td width="60"><span><a onclick="orders_redeem($(this).closest('form'));" href="#" title="Redeem" class="button">Redeem</a></span></td><td width="6">&nbsp;</td>
<?php
			}
?>
					<td width="50"><span><a onclick="$(this).closest('form').submit();" href="#" title="Print" class="button print_button">Print</a></span></td></tr></table></div>
				</form>
			</div>
<?php
		}
	}
?>
	</div>
</div>