<?php
	include "config.phtml";
	include "parameters.phtml";
$objSesh = new Zend_Session_Namespace('hebrewschools');
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<meta http-equiv="X-UA-Compatible" content="chrome=1">
		<title><?php print $this->layout()->strTitle ? $this->layout()->strTitle . " - " : "" ?>Tzivos Hashem Kiosk</title>
		<script src="<?php print WEB_ROOT; ?>/js/back-end/kiosk/jquery.core1.5.1.js" type="text/javascript"></script>
		<script src="<?php print WEB_ROOT; ?>/js/back-end/kiosk/jquery.ui.js" type="text/javascript"></script>
		<script src="<?php print WEB_ROOT; ?>/js/back-end/kiosk/jquery.checkbox.js" type="text/javascript"></script>
		<script src="<?php print WEB_ROOT; ?>/js/back-end/kiosk/easySlider1.7.js" type="text/javascript"></script>
		<script src="<?php print WEB_ROOT; ?>/js/back-end/kiosk/jquery.scroll.js" type="text/javascript"></script>
		<script src="<?php print WEB_ROOT; ?>/js/back-end/kiosk/jquery.ui.spinner.js" type="text/javascript"></script>
		<script src="<?php print WEB_ROOT; ?>/js/back-end/kiosk/shadowbox2/shadowbox.js" type="text/javascript"></script>
		<script src="<?php print WEB_ROOT; ?>/js/back-end/kiosk/jquery.keypad.js" type="text/javascript"></script>
		<script src="<?php print WEB_ROOT; ?>/js/back-end/admin/jquery.dump.js" type="text/javascript"></script>
		<script src="<?php print WEB_ROOT; ?>/js/back-end/kiosk/jquery.tools.tabs.min.js" type="text/javascript"></script>
		<script type="text/javascript" src="<?php print $sn; ?>/js/back-end/admin/ckeditor/ckeditor.js"></script>
		<script type="text/javascript" src="<?php print $sn; ?>/js/back-end/admin/ckeditor/styles.js"></script>
		<script type="text/javascript">
		$(document).ready(function()
		{
			$('input[type=checkbox]').checkbox();
			$('.scroll-pane').jScrollPane({showArrows:true, scrollbarWidth: 42, arrowSize: 42});
			$('.icon_logout a').click(function (e) {
				var intPermissions = <?php print count($this->arrStudentPermissions);?>;
				if (intPermissions > 1) {
					e.preventDefault();
					$('#logout_backdrop').fadeTo('normal', 0.7);
					$("#logout_overlay").fadeIn();
					$('#logout_overlay_parent').css({
						"top" : Math.max(0, (($('body').height()-430)/2)) + 'px',
						"display" : "block"
					});
					$('#logout_overlay').css({
						"top" : Math.max(0, (($('body').height()-430)/2)) + 'px',
						"display" : "block"
					});
				}
			});
			$('.close_overlay').bind('click', function(event) {
				$('#logout_backdrop').fadeTo('normal', 0).queue(function () {
					$(this).dequeue().css("display", "none");
				});
				$("#logout_overlay").fadeOut();
			});
		});
if (!Object.keys) {
    Object.keys = function (obj) {
        var keys = [],
            k;
        for (k in obj) {
            if (Object.prototype.hasOwnProperty.call(obj, k)) {
                keys.push(k);
            }
        }
        return keys;
    };
}
		</script>

		<link href="<?php print WEB_ROOT; ?>/css/back-end/kiosk/jquery.spinner.css" rel="stylesheet" type="text/css" />
		<link href="<?php print WEB_ROOT; ?>/js/back-end/kiosk/shadowbox2/shadowbox.css" rel="stylesheet" type="text/css" />

        <link rel="stylesheet" type="text/css" href="<?php print WEB_ROOT; ?>/css/back-end/kiosk/styles_reset.css">
        <link rel="stylesheet" type="text/css" href="<?php print WEB_ROOT; ?>/css/back-end/kiosk/styles_kiosk.css">
        <link rel="stylesheet" type="text/css" href="<?php print WEB_ROOT; ?>/css/back-end/kiosk/reset.css">
        <link rel="stylesheet" type="text/css" href="<?php print WEB_ROOT; ?>/css/back-end/kiosk/style.css">

        <link rel="stylesheet" type="text/css" href="<?php print WEB_ROOT; ?>/css/back-end/kiosk/jquery.checkbox.css" />
		<link href="<?php print WEB_ROOT; ?>/css/back-end/kiosk/jquery.scroll.css" rel="stylesheet" type="text/css" />
		<link href="<?php print WEB_ROOT; ?>/css/back-end/kiosk/jquery.keypad.css" rel="stylesheet" type="text/css" />

		<!--[if IE]>
		<link href="<?php print WEB_ROOT; ?>/css/back-end/kiosk/style_ie.css" rel="stylesheet" type="text/css" />
		<![endif]-->

		<style>
			.rank {
				width: 100px;
				height: auto;
				border: none;
				position: absolute;
				margin-top: 100px;
			}
			.overlay {
				display: none;
				position: relative;
				width:640px;
				padding: 10px;
				background-color:#333;
				color: white;
				background-image:url(//v2dev1.mashpia.com/images/back-end/kiosk/Camouflage-Background-Green.jpg);
				background-position:50% 50%;
				border:1px solid #666;

				/* CSS3 styling for latest browsers*/
				box-shadow:0 0 90px 5px #000;
				-moz-box-shadow:0 0 90px 5px #000;
				-webkit-box-shadow: 0 0 90px #000;
			}
			#logout_backdrop {
				position: absolute;
				display: none;
				background-color: black;
				z-index: 998;
				top:0px;
				left:0px;
				width:100%;
				height:100%;
			}
			.selecton_box {
				margin: 9px 3px 3px 3px;
				text-align:center;
				padding: 9px 3px 3px 3px;
				border: 1px solid #fff;
				background: rgba(255, 255, 255, 0.1);
				cursor: pointer;
			}
		</style>

<?php
	if (
		$objSesh->template_style == 'hoo'
		|| $objSesh->template_style == 'chabadhebrewschool'
	) {
?>

        <link rel="stylesheet" type="text/css" href="<?php print $sn; ?>/css/brands/hoo/kiosk/style.css">
<?php
	}
	// Additional styles that are loaded dynamically
	echo $this->headLink();

	// Additional javascript that are loaded dynamically
	echo $this->headScript();
?>
	</head>

	<body class="<?php print $this->layout()->bgColor?>">
		<div id="logout_backdrop"></div>
<div id="logout_overlay_parent" style="position:absolute; width:100%; display: none; z-index:999">
	<div id="logout_overlay" class="overlay logout_overlay display_overlay display_type_overlay" style="margin: auto;">
		<div class="close close_overlay" style="z-index:1000"></div>
		<div class="view_type">
			<div style="width:100%;text-align:center;margin-bottom: 22px;">Session Manager</div>
			<a href="<?php print $sn; ?>/hebrewschools/index/tstyle/<?php print $this->tstyle; ?>"><div class="selecton_box" value="all">Logout</div></a>
<?php
	global $arrAppDetails;
	foreach ($this->arrStudentPermissions as $objPermission)
	{
		if ($objSesh->template_style == $objPermission->template_style)
			continue;
?>
			<a href="<?php print $sn; ?>/hebrewschools/index/tstyle/<?php print $objPermission->template_style; ?>/from_widget/ims_kiosk/exit_mode/close_window/barcode/<?php print $this->objUser->bar_code; ?>"><div class="selecton_box" value="purchases"><?php print $arrAppDetails[$objPermission->template_style]['name']; ?></div></a>
<?php
	}
?>
		</div>
	</div>
</div>
		<div id="wrapper">
<?php
	print $this->layout()->content;
?>
		</div>
	</BODY>
</HTML>

