<?php
	$kiosk_user_session_data = new Zend_Session_Namespace('kiosk_user_session_data');
	$objUserSession = new Zend_Session_Namespace('userInfo');
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<meta http-equiv="X-UA-Compatible" content="chrome=1">
		<title><?php print $this->layout()->strTitle ? $this->layout()->strTitle . " - " : "" ?>Tzivos Hashem Kiosk</title>

		<script src="<?php print WEB_ROOT; ?>/js/back-end/kiosk/jquery.core1.5.1.js" type="text/javascript"></script>
		<script src="<?php print WEB_ROOT; ?>/js/back-end/kiosk/jquery.ui.js" type="text/javascript"></script>
		<script src="<?php print WEB_ROOT; ?>/js/back-end/kiosk/jquery.checkbox.js" type="text/javascript"></script>
		<script src="<?php print WEB_ROOT; ?>/js/back-end/kiosk/easySlider1.7.js" type="text/javascript"></script>
		<script src="<?php print WEB_ROOT; ?>/js/back-end/kiosk/jquery.scroll.js" type="text/javascript"></script>
		<script src="<?php print WEB_ROOT; ?>/js/back-end/kiosk/jquery.ui.spinner.js" type="text/javascript"></script>
		<!--script src="<?php print WEB_ROOT; ?>js/back-end/kiosk/shadowbox/shadowbox.js" type="text/javascript"></script-->
		<script src="<?php print WEB_ROOT; ?>/js/back-end/kiosk/jquery.keypad.js" type="text/javascript"></script>
		<script src="<?php print WEB_ROOT; ?>/js/back-end/admin/jquery.dump.js" type="text/javascript"></script>
		<script src="<?php print WEB_ROOT; ?>/js/back-end/kiosk/jquery.tools.tabs.min.js" type="text/javascript"></script>

		<script type="text/javascript">
		$(document).ready(function()
		{
			$('input[type=checkbox]').checkbox();
			$('.scroll-pane').jScrollPane({showArrows:true, scrollbarWidth: 42, arrowSize: 42});
		});
		</script>

		<link href="<?php print WEB_ROOT; ?>/css/back-end/kiosk/jquery.spinner.css" rel="stylesheet" type="text/css" />
		<link href="<?php print WEB_ROOT; ?>/js/front-end/kiosk/shadowbox/shadowbox.css" rel="stylesheet" type="text/css">
		<link href="<?php print WEB_ROOT; ?>/css/back-end/kiosk/reset.css" rel="stylesheet" type="text/css" />
		<link href="<?php print WEB_ROOT; ?>/css/back-end/kiosk/style.css" rel="stylesheet" type="text/css" />
		<link href="<?php print WEB_ROOT; ?>/css/back-end/kiosk/print.css" rel="stylesheet" type="text/css" media="print" />
		<link href="<?php print WEB_ROOT; ?>/css/back-end/kiosk/jquery.scroll.css" rel="stylesheet" type="text/css" />
		<link href="<?php print WEB_ROOT; ?>/css/back-end/kiosk/jquery.keypad.css" rel="stylesheet" type="text/css" />

		<!--[if IE]>
		<link href="<?php print WEB_ROOT; ?>/css/back-end/kiosk/style_ie.css" rel="stylesheet" type="text/css" />
		<![endif]-->

		<style>
			.rank {
				width: 100px;
				height: auto;
				border: none;
				position: absolute;
				margin-top: 100px;
			}
		</style>

		<!-- <?php print $kiosk_user_session_data->user_id; ?> : <?php print $kiosk_user_session_data->institution_id; ?> -->

<?php
	// Additional styles that are loaded dynamically
	echo $this->headLink();

	// Additional javascript that are loaded dynamically
	echo $this->headScript();
?>
	</head>

	<body class="<?php print $this->layout()->bgColor?>">
		<div id="wrapper">
			<div id="header">
				<div class="org">
					<div class="nav">
						<ul>
<?php
	if ($_SERVER['REQUEST_URI'] != "/kiosk-main")
	{
?>
							<li class="icon_back"><a href="#" onclick="javascript:history.back(); return false">Back</a></li>
<?php
	}
	if ($objUserSession->tanya_portal)
	{
?>
							<li class="icon_home"><a href="http://www.mashpia.com/statement.php">Home</a></li>
							<li class="icon_logout"><a href="http://www.mashpia.com/logout.php?n=kiosk.php">Logout</a></li>
<?php
	}
	else
	{
?>
							<li class="icon_home"><a href="<?php print WEB_ROOT; ?>kiosk-main/index">Home</a></li>
							<li class="icon_logout"><a href="/kiosk-login/reset">Logout</a></li>
<?php
	}
?>
						</ul>
					</div>
					<div class="org_photo">
<?php
	if ($this->objInstitution->image_id)
	{
		print "<img src='" . WEB_ROOT . "images/show-image/image_id/" . $this->objInstitution->image_id . "' WIDTH='100' HEIGHT='100' />";
	}
?>
					</div>
<?php
	if ($objUserSession->tanya_portal)
	{
?>
					Base: #<?php print $objUserSession->base_num; ?><br>
					<?php print $kiosk_user_session_data->institution_name; ?><br>
					<?php
		if ($objUserSession->rank_title)
			print ucwords($objUserSession->rank_title) . " ";
		print $kiosk_user_session_data->first_name . " " . $kiosk_user_session_data->last_name;
	}
	else
	{
?>
					Institution: <?php print $kiosk_user_session_data->institution_name; ?><br>
					Name: <?php
		if ($objUserSession->rank_title)
			print ucwords($objUserSession->rank_title) . " ";
		print $kiosk_user_session_data->first_name . " " . $kiosk_user_session_data->last_name;
	}
?><br>
				</div>
			</div>
			<div id="main">
<?php
	print $this->layout()->content;
?>
			</div>
			<div style="width:100%;text-align:center;padding:5px;bottom:0; position:absolute; left:120;"><BR></div>
		</div> <!-- wrapper -->
	</BODY>
</HTML>

