<?php
	include "config.phtml";
	include "parameters.phtml";
	$user_session_data = new Zend_Session_Namespace('user_session_data');

	function dateToHebrewShortYear($date)
	{
		if(is_null($date)) return '';
		@list($day, $month, $year, $year2) = mb_split(' ', dateToHebrew($date));
		if(!empty($year2))
		{
		  $month = "$month $year";
		}
		$year = mb_substr($year, 3);
		return "$day $month $year";
	}
	function dateToHebrew($date)
	{
		if(is_null($date))
			return '';
		else
			return mb_convert_encoding(jdtojewish($date, true, CAL_JEWISH_ADD_GERESHAYIM), 'UTF-8', 'ISO-8859-8');
	}
	//covert yyyy-mm-dd to julian date
	function dateToJD($date)
	{
		@list($year, $month, $day) = split('-', $date);
		$jd = cal_to_jd(CAL_GREGORIAN, intval($month), intval($day), intval($year));
		return $jd ? $jd : NULL;
	}
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<title>Print Rank Cards</title>
		<style type="text/css">

.cards .card {
	width:3.5in;
	height:2in;
	text-align:center;
	background:#fff;
	width:306px;
	height:162px;
	padding:15px;
	font-size:24px;
	page-break-after:always;
}
.cards .card .container {
	border:2px solid #000;
	border-radius:10px;
	-moz-border-radius:10px;
	height:100%;
}
.cards .priveleges {
	font-size:8px;
}
.cards .name {
	height:30px;
	margin-bottom:-33px;
	margin-top:3px;
	padding-left:8px;
	text-align:left;
	font-weight:bold;
	color:#ddd;
}
.cards .signature {
	font-size:8px;
	text-align:right;
	border-top:1px solid #000;
	border-bottom:1px solid #000;
	margin:1px 0 2px;
	padding:2px 5px;
}
.cards .signature h2 {
	font-size:16px;
	margin:0;
}
.cards .photo {
	float:right;
	margin-right:5px;
	padding:0;
}
.cards .photo img {
	height:75px;
	border:none;
}
.cards .logo {
	float:left;
	margin:-17px 10px;
}
.cards .logo img {
	margin:5px 0;
	width:55px;
	height:55px;
}
.cards .institution {
	font-size:8px;
	margin-top:-15px;
	text-align:right;
}
.cards .institution img {
	float:right;
	margin:5px;
	width:55px;
	height:55px;
}
.cards .institution h2 {
	font-size:12px;
	margin:0;
}
.cards .institution .box {
	margin:5px 0 0;
	float:right;
}
.cards .barcode {
	font-size:9px;
}
@media print {
  body {
    background-color: transparent;
  }
}
		</style>
	</head>
	<body>
<?php
	foreach ($this->arrUsers as $objUser)
	{
		$strFirstName = !empty($objUser->hebrew_first_name) ? $objUser->hebrew_first_name : $objUser->first_name;
		$strLastName = !empty($objUser->hebrew_last_name) ? $objUser->hebrew_last_name : $objUser->last_name;
?>
		<div class="cards id">
			<div class="card">
				<div class="container">
					<div class="priveleges">This card entitles the cardholder to TH privileges</div>
					<div class="name">ID CARD 5772</div>
					<div class="signature">Authorized Signature<h2><?php echo $strFirstName . ' ' . $strLastName;?></h2></div>
					<div class="barcode"><img src="<?php echo $sn; ?>/kiosk/get-barcode-legacy/serial/<?php print $objUser->bar_code; ?>" width="210" height="20" /><br /><?php print $objUser->bar_code; ?></div>
					<div class="photo" style="float:left; padding-left:8px"><img src="<?php echo $sn; ?>/imgs/v/src/<?php echo $objUser->image_id; ?>" /></div>
					<!--div class="logo"><img src="<?php $sn; ?>/images/cth_logo_print.png" /></div-->

					<div class="institution">
						<img src="<?php echo $sn . '/imgs/v/src/' . $this->objInstitution->image_id; ?>" style="width:50px; height:50px;" width="50" height="50" />
						<div class="box">
							<h2><?php print $this->objInstitution->name; ?></h2>
							<p><?php print $this->objInstitution->city; ?>, <?php print $this->objInstitution->state;?></p>
						</div>
					</div>
				</div>
			</div>
		</div>
<?php
    }
?>
	</body>
</html>