<?php
	include "config.phtml";
	include "parameters.phtml";
?>
<style>
	.processing_status {
		display: none;
		padding: 4px 0 8px 8px;
		color: red;
		width: 500px;
	}
</style>
<script language="javascript">
$(document).ready(function()
{
	$('.slider:last form a.submit').click( function(e) {
		$(".slider:last .processing_status").fadeOut();
		$.ajax({
			type : "POST",
			cache : false,
			start: $(".slider:last #processing_status").html('Loading...').fadeIn(),
			url : '<?php echo $sn . "/administration/changepassword" . $strParamPath; ?>',
			dataType : "text",
			data: $('.slider:last form').serialize(),
			success : function(strResponse) {
				//alert(strResponse);
				try {
					var arrResponse = jQuery.parseJSON(strResponse);
				} catch(e) {
					$(".slider:last #processing_status").html('Sorry, there was an error: VA-CP101-3RR3RE');
					alert("Sorry, there was an error: VA-CP101-3RR3RE");
					alert(strResponse);
					return;
				}
				if (typeof(arrResponse) != "object") {
					$(".slider:last #processing_status").html('Sorry, there was an error: VA-CP102-SDF8BX');
					alert("Sorry, there was an error: VA-CP102-SDF8BX");
					return;
				} else {
					$(".slider:last #processing_status").fadeOut();
					if (arrResponse["error"]) {
						if (typeof(arrResponse["error"]) != "object") {
							$(".slider:last #processing_status").html(arrResponse["error"]);
						} else {
							for (strField in arrResponse["error"])
							{
								$(".slider:last #" + strField).closest("li").next().html(arrResponse["error"][strField]).fadeIn();
							}
						}
					} else if (arrResponse["success"] == "true") {
						$(".slider:last #processing_status").html("Success").fadeIn();
					} else {
						alert("Sorry, there was an error: VA-CP103-DS7DDS");
						//alert($.dump(arrResponse));
					}
				}
			}
		});
	});
});
</script>
<div class="slider" id="registration_administrator">
	<div class="col_title"><span>Change Password</span></div>	
	<div class="col_content camper">
		<div id="lists" class="module lists forms">			
			<div class="module_content">
				<ul>
					<li>
						Please provide your current password and choose your new password.</li>
				</ul>
			</div>
		</div>
		<div class="module form" id="module-info">
			<div class="module_content list">
				<form name="registration_administrator" id="registration_administrator" method="post" action="">
					<input type="hidden" id="registration_administrator_data" value="" />
					<ul>
						<li>
							<span class="label">Current Password:</span>
							<span class="input"><input autocomplete="off" type="password" class="required" id="current_password" name="current_password" value="" size="25" minlength="2" /></span>
							<div class="clear"></div>
						</li>
						<div class="processing_status"></div>
						<li>Insert your new password of 6 characters or more.</li>
						<li>
							<span class="label">New Password:</span>
							<span class="input"><input autocomplete="off" type="text" class="required" id="new_password" name="new_password" value="" size="25" minlength="2" /></span>
							<div class="clear"></div>
						</li>
						<div class="processing_status"></div>
						<li>
							<span class="label">Confirm New Password:</span>
							<span class="input"><input autocomplete="off" type="text" class="required" id="confirm_new_password" name="confirm_new_password" value="" size="25" minlength="2" /></span>
							<div class="clear"></div>
						</li>
						<div class="processing_status"></div>
						<div id="processing_status" style="padding:4px"></div>
						<li>
							<span><a href="#" title="Save" class="button submit">Save</a></span>							
							<div class="clear"></div>							
						</li>
					</ul>
				</form>
			</div>							
		</div>
	</div>
</div>