<div class="slider">
	<div class="col_title"><span><?php print text("Mashpia Developer Resources"); ?></span></div>
	<div class="col_content">
		<style>
			p {
				margin-top: 16px !important;
				font-size:12pt !important;
			}
			h2 {
				padding-top: 20px;
				margin-top: 20px;
				border-bottom:none;
				text-align: left;
				font-size:16pt;

			}
			h2:not(.reset) {
				padding-top: 40px;
				margin-top: 40px;
				border-top:1px solid #ccc;
			}
		</style>
		<div class="module message" style="padding:6px;vertical-align: top;">
			<div class="module_content" style="vertical-align: top;text-align: left;">
				<h2 class="reset">Welcome Developers</h2>
				<p>
					Here we have documented some of our most repetitive components required
					to build essential aspects of our software.
				</p>
				<p>
					A lot of our code has repetitive components to it such as
					transitions, navigation, AJAX, advanced sorting, est...
					Rather than forcing you to go through our code looking
					for how we complete a specific operation you can use this
					page as guide.
				</p>
				<h2>Coding Standards</h2>
				<p>
					We have a few language/version independent standards
					that are required in any code that is developed for our company.
					These standards were created to keep our code clean, consistent, safe and scalable.
				</p>
				<p>
					If this is your first time visiting developing it is essential for you to review
					these standards and prepare to incorporate them in your code.
				</p>
				<p>
					View our <a href="#">Coding Standards</a>
				</p>
				<p>
					&nbsp;
				</p>
			</div>
		</div>
	</div>
</div>