<div class="slider">
	<div class="col_title"><span><?php print text("Mashpia Developer Resources"); ?></span></div>
	<div class="col_content">
		<style>
			p {
				margin-top: 16px !important;
				font-size:12pt !important;
			}
			h2 {
				padding-top: 20px;
				margin-top: 20px;
				border-bottom:none;
				text-align: left;
				font-size:16pt;

			}
			h2:not(.reset) {
				padding-top: 40px;
				margin-top: 40px;
				border-top:1px solid #ccc;
			}
		</style>
		<div class="module message" style="padding:6px;vertical-align: top;">
			<div class="module_content" style="vertical-align: top;text-align: left;">
				<h2 class="reset">HTML Environment</h2>
				<p>
					Here you will find the current admin features that
					should be implemented if the situation calls for it. For example,
					if there is a checkbox that needs to be implemented, the one found
					here should be used rather than a default HTML checkbox or another
					plugin found on the internet.
				</p>
				<p>
					We have been refining our UI for years in attempt to make our
					product as clear as possible to our clients. At the same time
					as trying to implement these innovations we've had to also keep in mind
					a few other things, such as consistency, flow, framework versions
					and user-friendliness.
				</p>

				<p>
					&nbsp;
				</p>
			</div>
		</div>
	</div>
</div>