<?php 
	include "config.phtml";
	
	$strUrl = '';
	if(isset($this->host_id)) $strUrl .= '/host_id/'.$this->host_id;
	if(isset($this->network_id)) $strUrl .= '/network_id/'.$this->network_id;
	if(isset($this->institution_id)) $strUrl .= '/institution_id/'.$this->institution_id;
	
?>
<div class="slider" id='slider_gradeslist'>
	<div class="col_title">
		<span>Grades</span>
	</div>
	<div class="col_content">		
		<div id="lists" class="module lists forms">
			<div class="module_content">
				<form name="listgrades" id="listallinstitutions" method="post" action="">
					<ul>
						
<?php				
				if($this->arrGrades)
				{		
					foreach ($this->arrGrades as $value)
					{		
						echo '<li>
								<a class="link" href="'.$sn.'/grades/gradesedit/grade_id/'.$value->grade_id.'">
									<div class="icon"></div>
									<div class="title">'.$value->grade_name.'</div>
								</a>
							 </li>';
					}
				}
				else
				{
					echo "No grades found.";
				}
?>
					</ul>
				</form>
			</div>
		</div>		
	</div>
</div>