<?php
	include "config.phtml";
	include "parameters.phtml";
?>
<script language="javascript">
	$(document).ready(function()
	{
		$('.slider:last #add_grade').click( function(e) {
			e.preventDefault();
			$.ajax({
				type : "POST",
				cache : false,
				start: $(".slider:last #processing_status").html('<?php print text("Loading..."); ?>').fadeIn("slow"),
				url : '<?php echo $sn . "/grades/gradeseditor" . $strParamPath; ?>',
				dataType : "text",
				data: $('.slider:last #add_module form').serialize(),
				success : function(strResponse) {
					if (strResponse.match(/^[0-9]+$/)) {
						$(".slider:last #processing_status").fadeOut("slow");
						ajax_grades();
					} else {
						$(".slider:last #processing_status").html(strResponse).fadeIn("slow");
					}
				}
			});
		});
		ajax_grades();
	});

	function ajax_action(strAction, intGradeId) {
		$.ajax({
			type : "GET",
			cache : false,
			start: $(".slider:last #processing_status2").html('<?php print text("Loading..."); ?>').fadeIn("slow"),
			url : '<?php echo $sn . "/grades/gradeseditor" . $strParamPath; ?>/' + strAction + '/true/grade_id/' + intGradeId,
			dataType : "text",
			success : function(strResponse) {
				if (strResponse.match(/^[0-9]+$/)) {
					ajax_grades();
				} else {
					$(".slider:last #processing_status2").html(strResponse).fadeIn("slow");
				}
			}
		});
	}

	function popdeletequestion(intGradeId) {
		$(".slider:last #item_to_delete").val(intGradeId);
		$.blockUI({ message: $('.slider:last #gradeeditor_question')});
	}
	$('.slider:last #gradeeditor_question #option1').click(function(e) {
		e.preventDefault();
		ajax_action("delete", $(".slider:last #item_to_delete").val());
		$.unblockUI();
	});
	$('.slider:last #gradeeditor_question #option2').click(function(e) {
		e.preventDefault();
		$.unblockUI();
	});

	function ajax_grades() {
		$.ajax({
			type : "GET",
			cache : false,
			start: $(".slider:last #grade_list").fadeIn("slow"),
			url : '<?php echo $sn . "/grades/gradeseditor/ajax/true" . $strParamPath; ?>',
			dataType : "text",
			success : function(strResponse) {
				var objTarget = $(".slider:last #grade_list");
				var arrResponse = jQuery.parseJSON(strResponse);
				if (arrResponse.length) {
					var strHTML = "<table>\n\t<tr>\n";
					strHTML += "		<td><b><?php print text("Name"); ?></b></td>\n";
					strHTML += "		<td><b><?php print text("[|Sub|]"); ?></b></td>\n";
					strHTML += "		<td colspan='3'>&nbsp;</td>\n";
					strHTML += "	</tr>\n";
					for (var intItr=0; intItr!=arrResponse.length; intItr++) {
						var intGradeId = arrResponse[intItr]["objGrade"]["grade_id"];
						var strRowName = intItr;
						strHTML += "	<tr>\n";
						strHTML += "		<td><input type='hidden' name='" + strRowName + "_grade_id' value='" + intGradeId + "' />";
						strHTML += '			<span class="input"><input type="text" class="required" id="' + strRowName + '_name" name="' + strRowName + '_name" value="' + arrResponse[intItr]["objGrade"]["grade_name"] + '" size="25" minlength="2" /></span></td>';
						strHTML += '		<td><span class="input"><input type="text" class="required" id="' + strRowName + '_sub" name="' + strRowName + '_sub" value="' + arrResponse[intItr]["objClass"]["sub"] + '" size="5" minlength="1" style="width: 80px;" /></span></td>';
						if (intItr) {
							strHTML += '		<td><div class="button arrow" onclick="ajax_action(\'up\', ' + intGradeId + ')"><img src="/images/back-end/admin/arrow-up2.png" style="opacity:0.5" /></div></td>';
						} else {
							strHTML += "		<td>&nbsp;</td>";
						}
						if (intItr!=arrResponse.length-1) {
							strHTML += '		<td><div class="button arrow" onclick="ajax_action(\'down\', ' + intGradeId + ')"><img src="/images/back-end/admin/arrow-down2.png" style="opacity:0.5" /></div></td>';
						} else {
							strHTML += "		<td>&nbsp;</td>";
						}
						strHTML += '		<td align="right" width="70">&nbsp;<span><a onclick="popdeletequestion(' + intGradeId + ');" style="display:inline !important;" href="#" class="button submit" id="delete"><?php print text("Delete"); ?></a></span></td>';
						strHTML += "	</tr>\n";
						strHTML += '	<tr class="processing_status"><td colspan="5"></td></tr>';
					}
					strHTML += "</table><hr>";
					strHTML += '<div id="processing_status2"></div><span><a onclick="ajax_update();" href="#" title="<?php print text("Save"); ?>" class="button submit"><?php print text("Save Changes"); ?></a></span><div class="clear"></div>';
					$(objTarget).html(strHTML);
				} else {
					$(objTarget).html("<?php print text("There are no [|classes|] yet."); ?>");
				}
			}
		});
	}

	function ajax_update()
	{
		$(".slider:last .processing_status").fadeOut();
		$.ajax({
			type : "POST",
			cache : false,
			start: $(".slider:last #processing_status2").html('<?php print text("Loading..."); ?>').fadeIn("slow"),
			url : '<?php echo $sn . "/grades/gradeseditor/update/true" . $strParamPath; ?>',
			dataType : "text",
			data: $('.slider:last form.class_list').serialize(),
			success : function(strResponse) {
				try {
					var arrResponse = jQuery.parseJSON(strResponse);
				} catch(e) {
					$(".slider:last #processing_status2").html('<?php print text("Sorry, there was an error"); ?>: VU-E101-3RR3RE');
					return;
				}
				if (typeof(arrResponse) != "object") {
					$(".slider:last #processing_status2").html('<?php print text("Sorry, there was an error"); ?>: VU-E102-SDF8BX');
					return;
				} else {
					$(".slider:last #processing_status2").fadeOut();
					if (arrResponse["error"]) {
						if (typeof(arrResponse["error"]) != "object") {
							$(".slider:last #processing_status2").html(arrResponse["error"]);
						} else {
							for (var strField in arrResponse["error"])
							{
								//alert($.dump($(".slider:last #" + strField).closest("li").html()));return;
								//alert($(".slider:last #" + strField).closest("table").html());
								//alert($(".slider:last #" + strField).closest("tr").next().next().get(0).tagName);
								//return;
								$(".slider:last #" + strField).closest("tr").next().find("td").html(arrResponse["error"][strField]);
								$(".slider:last #" + strField).closest("tr").next().fadeIn();
							}
						}
					} else if (arrResponse["success"] == "true") {
						$(".slider:last #processing_status2").html(arrResponse["count"] + " item(s) updated successfully.").fadeIn("slow").delay(2000).fadeOut("slow");
					} else {
						alert("<?php print text("Sorry, there was an error"); ?>: VA-J103-DS7DDS");
						alert($.dump(arrResponse));
					}
				}
			}
		});
	}
</script>
<div class="slider" id="gradeseditor">
	<style>
	#gradeseditor .processing_status {
		display: none;
	}
	#gradeseditor .processing_status td {
		padding: 4px 0 8px 8px;
		color: red;
		width: 500px;
	}
	#gradeseditor .arrow {
		display:inline-block;
		width:16px;
		height:16px;
		margin:3px;
	}
	</style>
	<div class="col_title">
		<span><?php print text("Add / Edit [|Classes|]"); ?></span><div class="title_help info" title="<?php print text("Manage your current [|classes|]. You can rename [|classes|] by writing a new name in the text box, change their order with  the up/down arrows, or delete them from your [|class|] (any [|students|] in a deleted [|class|] will revert to having no [|class|] assigned). The order of [|classes|] will define how they show up in certain lists. Don’t forget to hit ‘Save’ when you’re done!"); ?>"></div>
	</div>

	<div class="col_content">
		<div class="module form">
			<div class="module_content list">
				<form class="class_list">
					<ul>
						<li>
							<h1><?php print text("My [|Classes|]"); ?></h1>
						</li>
						<li>
							<div id="grade_list">
								<?php print text("Loading [|classes|]..."); ?>
							</div>
						</li>
					</ul>
				</form>
			</div>
		</div>
		<h2><?php print text('Add a [|Class|]'); ?> &nbsp;<div class="help_icon info" title="<?php print text("You can create a new [|class|] for your [|school|] by entering a name and [|sub|]-name, and then pressing ‘Add [|Class|]’. New [|classes|] go automatically to the bottom of the [|class|] list."); ?>"></div></h2>
		<div class="module form">
			<div class="module_content list" id="add_module">
				<form>
					<ul>
						<li>
							<table>
								<tr>
									<td><b><?php print text("[|Class|] Name"); ?></b></td>
									<td colspan="2"><b><?php print text("[|Sub|] [|Class|]"); ?></b></td>
								</tr>
								<tr>
									<td><span class="input"><input class="gradeseditor_text_input" type="text" class="required" id="grade_name" name="grade_name" value="" size="25" minlength="2" /></span></td>
									<td><span class="input"><input style="width:80px" class="gradeseditor_text_input" type="text" class="required" id="grade_sub" name="grade_sub" value="" size="6" minlength="0" /></span></td>
									<td><span><a href="#" title="Save" class="button submit" id="add_grade"><?php print text('Add [|class|]'); ?></a></span></td>
								</tr>
							</table>
						</li>
						<div id="processing_status"><?php if ($this->message) { echo $this->message . "<br>"; } ?></div>
					</ul>
				</form>
			</div>
		</div>
		<div id="gradeeditor_question" class="question">
			<p><?php print text("Are you sure you would like to delete this [|class|]?"); ?></p>
			<p><a id="option1" class="button"><?php print text("Yes, delete it."); ?></a></p>
			<p><a id="option2" class="button"><?php print text("No, do <u>NOT</u> delete it."); ?></a></p>
		</div>
		<intput type="hidden" id="item_to_delete" value="" />
	</div>
</div>
