<?php
	include "config.phtml";
	
	$strUrl = '';
	if(isset($this->host_id)) $strUrl .= '/host_id/'.$this->host_id;
	if(isset($this->network_id)) $strUrl .= '/network_id/'.$this->network_id;
	if(isset($this->institution_id)) $strUrl .= '/institution_id/'.$this->institution_id;	
?>
<div class="slider" id='slider_gradeaddnetworks'>
	<div class="col_title">
			<span>Select a Network</span>
	</div>
	<div class="col_content">
		
		<div id="lists" class="module lists forms">
			<div class="module_content">
				<ul>
					<ul>
						<li>
							<a class="link" href="<?=$sn?>/grades/gradeseditor<?=$strUrl?>">
							<div class="icon"></div>
							<div class="title">> Skip to Add / Edit Grade</div>
							</a>
						</li>
<?php 
if ($this->all_networks)
{			
	foreach ($this->all_networks as $value)
	{		
		echo '<li>
				<a class="link" href="'.$sn.'/grades/gradeinstitutionadd/host_id/'.$value->host_id.'/network_id/'.$value->institution_id.'">
				<div class="icon"></div>
				<div class="title">'.$value->name.'</div>
				</a>
			</li>';
	}	
}
else
{
	echo 'There are no Networks';
}
?>	
		</ul>
		</div>
	</div>
</div>
</div>