<?php
	include "config.phtml";
	include "parameters.phtml";
	$objSesh = new Zend_Session_Namespace('hebrewschools');
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<HTML DIR="LTR">
<HEAD>
<LINK href="/css/back-end/login.css" rel="stylesheet" type="text/css"/>
<?php
	if ($this->template_style == 'hoo')
	{
?>
<LINK href="<?php echo $sn; ?>/css/brands/hoo/kiosk/login.css" rel="stylesheet" type="text/css"/>
<?php
	}
	else if ($this->template_style == 'chabadhebrewschool')
	{
?>
<LINK href="<?php echo $sn; ?>/css/brands/hoo/kiosk/login.css" rel="stylesheet" type="text/css"/>
<style>
	#header:before {
		background: url(/images/ckids/TH-CKids-Logo-8.png) no-repeat center top;
		height: 234px;
		z-index: 1;
		position: absolute;
		content:'';
		top:0;
		width:100%;
		left: 0;
		margin: 30px 0;
	}
</style>
<?php
	}
	else if ($this->template_style == 'tzivoshashem')
	{
?>
<LINK href="<?php echo $sn; ?>/css/brands/hoo/kiosk/login.css" rel="stylesheet" type="text/css"/>
<style>
	#header:before {
		background: url(/imgs/v/src/9402345_5978.png/w/260) no-repeat center top;
		height: 234px;
		z-index: 1;
		position: absolute;
		content:'';
		top:0px;
		width:100%;
		left: 0;
		margin: 30px 0;
	}
</style>
<?php
	}
?>
<TITLE><?php print text("Login"); ?></TITLE>
<script src="<?php print $sn; ?>/js/back-end/kiosk/jquery.core1.5.1.js" type="text/javascript"></script>
<script src="<?php print $sn; ?>/js/back-end/admin/jquery.dump.js" type="text/javascript"></script>
<SCRIPT type="text/javascript">
window.onload = scanFocus;
window.onkeydown = scanFocus;
function scanFocus() {
	$("#bar_code").focus();
}
/*
function eKeyPress(evt) {
	var charCode = (evt.which) ? evt.which : event.keyCode
	if (charCode == 13)
		$("form").trigger("submit");
}
*/
scanFocus();
$(document).ready(function() {
	$("form").submit(function(e) {
		e.preventDefault();
		if ($("#bar_code").val().length < 1)
		{
			$("#processing_status").html('<?php print text("Please try again."); ?>');
			return;
		}
		var strPost = $('form').serialize();
		$("#bar_code").val('');
		$.ajax({
			type : "POST",
			cache : false,
			start: $("#processing_status").html('<?php print text("Loading..."); ?>').fadeIn(),
			url : '<?php echo $sn . "/hebrewschools/index" . $strParamPath; ?>',
			dataType : "text",
			data: strPost,
			success : function(strResponse) {
				try {
					var arrResponse = jQuery.parseJSON(strResponse);
				} catch(e) {
					alert("<?php print text("Sorry, there was an error"); ?>: VKL-I101-3RR3RE");
					$.dumper(strResponse);
					return;
				}
				if (typeof(arrResponse) != "object") {
					alert("<?php print text("Sorry, there was an error"); ?>: VKL-I102-SDF8BX");
					$.dumper(strResponse);
					return;
				} else if (arrResponse["success"] == "true") {
					$("#processing_status").html('<?php print text("Authenticated. Please wait..."); ?>').delay(15000).queue(function() {
						$(this).dequeue().html("<?php print text("Still trying..."); ?>");
					});
					$("#processing_status").delay(30000).queue(function() {
						$(this).dequeue().html("<?php print text("There seems to be a connection issue."); ?>");
					});
					window.location.href = "<?php print $sn . "/hebrewschools/profile" . $strParamPath; ?>";
				} else {
					$("#processing_status").html(arrResponse["error"]).delay(30000).fadeOut();;
					//$("#processing_status").html('Failed. Please try again.').delay(3000).fadeOut();;
				}
			}
		});
	});
<?php
if (!empty($this->arrGet['barcode']))
{
?>
	$("#bar_code").val('<?php print $this->arrGet['barcode']; ?>');
	$("form").trigger('submit');
	$("#bar_code")[0].select();
<?php
}
?>
});
</SCRIPT>
</HEAD>
<!--BODY class="kiosk">
	<DIV id="header">
		<DIV></DIV>
	</DIV>
	<DIV STYLE="text-align: center;">
		<NOSCRIPT>
			<P STYLE="color: red; font-size: larger;"><?php print text("Notice: You have javascript disabled. Some parts of the site will not function without javascript."); ?></P>
		</NOSCRIPT>

		<FORM>
			<DIV id="body" class="login">
				<DIV style="height:48px">
					<INPUT type="text" name="bar_code" id="bar_code" size=25 maxlength=20 autocomplete="off">
					<p id="processing_status" style="display:none"></p>
				</DIV>
			</DIV>
		</FORM>
	</DIV>
</BODY-->
<BODY class="kiosk">
	<DIV id="header">
		<DIV></DIV>
	</DIV>
	<DIV STYLE="text-align: center;">
		<NOSCRIPT>
			<P STYLE="color: red; font-size: larger;"><?php print text("Notice: You have javascript disabled. Some parts of the site will not function without javascript."); ?></P>
		</NOSCRIPT>

		<FORM>
			<DIV id="body" class="dayschool">
				<DIV>
					<INPUT type="text" name="bar_code" id="bar_code" size=25 maxlength=20 autocomplete="off">
					<p id="processing_status" style="display:none"></p>
				</DIV>
						<BR>
						<BR>
						<P>

						</P>
			</DIV>
			<div style="position: absolute;width: 100%;">
				<div style="width:1024px;display: inline-block;padding-top:40px">
					<table>
						<tr>
<?php
	if ($this->institution_id)
	{
		for ($intItr=1; $intItr!=6; $intItr++)
		{
			$strImage = "&nbsp;";
			if (
				$this->arrKioskLogos['kiosk_logos_on']['logo_on_' . $intItr] == 1
				&& !empty($this->arrKioskLogos['kiosk_logos']['logo_' . $intItr])
				&& $this->arrKioskLogos['kiosk_logos']['logo_' . $intItr] != "0.gif"
			) {
				$strImage = "<img src='" . $sn . "/imgs/v/w/90/h/90/p/h/src/" . $this->arrKioskLogos['kiosk_logos']['logo_' . $intItr] . "' />";
			}
?>
							<td width="190"><?php print $strImage; ?></td>
<?php
		}
	}
?>
						</tr>
					</table>
				</div>
			</div>
		</FORM>
	</DIV>
</BODY>
</HTML>
