<?php
require $_SERVER['DOCUMENT_ROOT'] . '/db.php';
$schools = [
    "Achei Temimim",
    "Addlestone Hebrew Academy, Mt Pleasant, South Carolina",
    "Akiva Academy, Calgary, Alberta",
    "Akiva Academy, Dallas, Texas",
    "Ateres Bais Yaakov, Spring Valley, New York",
    "Bais Menachem Yeshiva Day School, San Francisco, California",
    "Bais Rochel, Staten Island, New York",
    "Bais Shifra Miriam, Monsey, New York",
    "Bais Yaakov Ateres Miriam, Merrick, New York",
    "Bais Yaakov Bnai Aliya, New York, New York",
    "Bais Yaakov Chofetz Chaim, Pomona, New York",
    "Bais Yaakov Ger, Brooklyn, New York",
    "Bais Yaakov of Boro Park, Brooklyn, New York",
    "Bais Yaakov, Brooklyn, New york",
    "Bais Yaakov, New york, New York",
    "Bais Yaakov of the Lower East Side, New york, New York",
    "Bas Mikroh, Spring Valley, New York",
    "Bay Area Cheder",
    "Beis Bina, Lakewood, New Jersey",
    "Beit Chana Tzfat, Milan, Italy",
    "Bess and Paul Sigel Hebrew Academy, Greater Hartford, Connecticut",
    "Bet Menachem, Budapest, Hungary",
    "Bet Sefer Net, Selly Park, Birmingham, England",
    "Bet Yaakov, Jersey Shore, New Jersey",
    "Bnos Bobov, Brooklyn, New york",
    "Bnos Malka, Forest Hills, New York",
    "Bnos Yisroel, Baltimore, Maryland",
    "Bnot Israel, Buenos Aires, Argentina",
    "Canberra Jewish School, Canberra, Australia",
    "Caskey Torah Academy, Philadelphia, Pennsylvania",
    "Chabad Cheder, Stonybrook, New York",
    "Chabad Girls Academy, New York, New York",
    "Chabad Hebrew Academy, San Diego, California",
    "Chabad Lubavitch Winnipeg Day School, Winnipeg, Manitoba, Canada",
    "Chabad School, Kiryat Shmuel, Israel",
    "Jewish Day School, Charlotte, North Carolina",
    "Chaya Mushka Children's House, Atlanta, Georgia",
    "Chaya Mushka High School, Cortland, New York",
    "Chaya Mushka High School, Grand Rapids, Michigan",
    "Cheder Beit Chaia Mushka, Rio de Janeiro, Brazil",
    "Cheder, Los Angeles, California",
    "Cheder Chabad, Jacksonville, Florida",
    "Cheder Chabad, Pleasanton, California",
    "Oholei Yosef Yitzchok Lubavitch, Michigan, Detroit",
    "Cheder Menachem, Moscow, Russia",
    "Cheder Menachem, Wilkes-Barre, Pennsylvania",
    "Cheder of the Bay Area, Napa, California",
    "Cheder of the East Bay",
    "Cheder Online",
    "Cheder, Passaic, New Jersey",
    "Cheder School, Amsterdam, Netherlands",
    "Hebrew Day School, Cincinnati, Ohio",
    "Clifton Cheder, Fair Lawn, New Jersey",
    "Torah Academy, Columbus, Ohio",
    "Darchai Torah, Far Rockway, New York",
    "Derech Hatorah, Rochester, New York",
    "Eitz Chaim, Thornhill, Ontario",
    "Gan Yisroel, Boro Park, New York",
    "Ganenu, Curitiba, Parana",
    "Gibraltar Girls High School, Las Vegas, Nevada",
    "Hebrew Academy, Hamilton, Ontario",
    "Hank Day School, Long Beach, New York",
    "Hebrew Academy, Indianapolis, Indiana",
    "Hebrew Academy, Long Beach, New York",
    "Hebrew Academy, Little Rock, Arkansas",
    "Hebrew Academy, Cleveland, Ohio",
    "Hebrew Academy, Orange County",
    "Hillel Academy, Broome County, New York",
    "Hillel Academy, Denver, Colorado",
    "Hillel School, Stockholm, Sweden",
    "Homeschool",
    "Hyman Brand Hebrew Academy, Kansas City, Michiganssouri",
    "Jewish Center for Special Education, Brooklyn, New York",
    "Jewish Girls School, Zurich, Switzerland",
    "Jewish Girls Unite, Oak Park, Michigan",
    "Jewish Virtual Academy",
    "JOS, Knoxville, Tenessee",
    "Katz Hillel Day School, Boca Raton, florida",
    "Kehillat Ashreinu Montessori, Rockville, Maryland",
    "King David, Birmingham, England",
    "Lamdeni, Brussels, Belgium",
    "Menorah School, Leeds, West Yorkshire",
    "Lerner Day School, Raleigh, North Carolina",
    "Lev Bais Yaakov, Brooklyn, New York",
    "Community Hebrew Day School, London, Ontario",
    "Jewish Day School, Louisville, Kentucky",
    "Lubavitch on the Palisades, Tenafly, New Jersey",
    "Or Menachem, Sao Paulo, Brazil",
    "Lubavitcher Yeshiva Academy, Springfield, Massachusetts",
    "Machon Beis Chaya Mushka, Dnipro, Ukraine",
    "Maimonides Hebrew Day School, Albany, New York",
    "Maimonides Jewish Day School, Portland, Oregon",
    "Maimonidies Chabad Cheder, Setauket, New York",
    "Maimonidies Hebrew Day School, Punta Gorda, Florida",
    "Mechina, Little Rock, Arizona",
    "Menachem Mendel Academy, Melbourne, Australia",
    "Menorah Academy, Edmonton, Alberta",
    "Merkos Leinyonei Chinuch, Milan, Italy",
    "Mesivta of Crown Heights, Brooklyn, New York",
    "Mirrer Yeshiva, Brooklyn, New York",
    "Mizrahi Torah Academy",
    "N. E. Miles Jewish Day School, Birmingham, Alabama",
    "Hebrew Academy, New England, Massachusetts",
    "Nigri Shluchim Online School",
    "Oholei Torah, Winnipeg, Manitoba",
    "Ohr Torah, Cincinnati, Ohio",
    "Online Russia",
    "Or Jabad, Caracas, Venezuela",
    "Jewish Day School, Orlando, Florida",
    "Park East Day School, New York, New York",
    "Politz Hebrew Academy, Yardley, Pennsylvania",
    "Prospect Park Yeshiva, Brooklyn, New York",
    "Hebrew Day School, Providence, Rhode Island",
    "Public School",
    "Robert M. Beren Academy, Houston, Texas",
    "Rosenbaum Yeshivah of North Jersey",
    "Rudlin Torah Academy, Richmond, Virginia",
    "Jewish Academy, Sacramento, California",
    "Scheck Hillel Community Day School, Bay Harbor Islands, Florida",
    "Siach Yitzchok",
    "Slater Torah Academy, New Orleans, Louisiana",
    "South Florida Jewish Academy",
    "South Peninsula Hebrew Day School",
    "Stichting Joodse Kindergemeenschap Cheider, Nijmegen, Netherlands",
    "Hebrew Dayschool, Syracuse, New York",
    "Tashbar, Lakewood, New Jersey",
    "Tehilas Chaya Sara, Freehold, New Jersey",
    "Torah Academy, Long Beach, New Jersey",
    "Torah Academy, Boston, Massachusetts",
    "Torah Academy, Brookline, Massachusetts",
    "Torah Day School, Dallas, Texas",
    "Torah Day School, Ottawa, Ontario",
    "Torah Day School, Phoenix, Arizona",
    "Torah School, Greater Washington, Virginia",
    "Torah Temimah, Brooklyn, New York",
    "Torahchinuch.com",
    "Tzanz, Hillside, New Jersey",
    "Tzemach Tzedek, Chicago, Illinois",
    "Tzivot Menachem",
    "Yaldeinu Day School, New York, New York",
    "Yeshiva Katana, Passaic, New Jersey",
    "Yeshiva Ketana, Manhattan, New York",
    "Yeshiva Shaarei Tzion, East Windsor, New Jersey",
    "Yeshivas Beis Hillel, Passaic, New Jersey",
    "Yeshivas Darchei Torah, West Bloomfield, Michigan",
    "Yeshivas Toras Emes, Monroe Township, New Jersey",
    "Tiferes Daniel, Zurich, Switzerland",
    "Akiba Yavneh Academy",
    "Bais Dovid",
    "Bais Malka Belz Lakewood",
    "Bais Yaakov Boro Park",
    "Bais Yaakov D'Ger",
    "Bais Yaakov D'Rav Meir",
    "Bais Yaakov Haramah",
    "Bais Yaakov Lower East Side",
    "Bais Yaakov Of Fallsburg",
    "Bais Yakov Vienna",
    "Beatrice J Stone Yavne Highschool (Hac)",
    "Bet Yaakov Of The Jersey Shore",
    "Beth Rivka France",
    "Bnei Zion",
    "Bnos Beis Yaakov",
    "Bnos Bina Lakewood Nj",
    "Bnos Chomesh Academy",
    "Bnos Malka Academy",
    "Bnos Menachem Moscow",
    "Bnos Sarah",
    "Bnos Yisroel Of Baltimore",
    "Chabad Hebrew Academy San Diego",
    "Chabad Lubavitch Of Greater Daytona",
    "Chabad Riga Day School",
    "Charlotte Jewish Day School",
    "Chaya Mushka High School Detroit",
    "Cheder Achei Temimim",
    "Cheder Chabad Jacksonville",
    "Cheder Chabad Of Kansas",
    "Cheder Chabad Pleasanton",
    "Cheder Detroit",
    "Cheder Eitz Chaim Lakewood",
    "Cheder Los Angeles",
    "Cheder Lubavitch Dallas",
    "Cheder Menachem Moscow",
    "Cheder Zichron Shmuel Monsey",
    "Cheider Amsterdam",
    "Cincinnati Hebrew Day School",
    "CMCH Atlanta",
    "Colombo Hebreo",
    "Darchai Torah, Far Rockaway, New York",
    "Derech Hatorah Rochester",
    "Desert Torah Academy Ohel Menachem",
    "Esformes Hebrew Academy",
    "Fuchs Mizrachi",
    "Gan Yisroel Boro Park",
    "Gibraltar Talmud Torah",
    "Hamilton Hebrew Academy",
    "Haor Beacon",
    "Hebrew Academy Indianapolis",
    "Hebrew Academy Of Arkansas",
    "Hebrew Academy Of Cleveland",
    "Hebrew Academy Of Tampa Bay",
    "Hebrew Academy-Nassau County",
    "Heichaltzu",
    "Hillel Academy Of Broome County",
    "Hillel Academy Of Dayton",
    "Hillel Academy Of Denver",
    "Hillel Academy Tampa",
    "Hillel Skolan",
    "Home School",
    "I. E. Lichtigfeld School",
    "Ivdu Speciel Ed",
    "Judische Schule Zurich",
    "Kayla'S Children Centre",
    "Leeds Menorah School",
    "London Community Hebrew Day School",
    "Louisville Jewish Day School",
    "Lubavitch Cheder Oholei Yosef Yitzchok Detroit",
    "Machon Bais Chaya Mushka Dnipro Ukraine",
    "Machon Chaya Mushka Kharkov",
    "Maimonides Hebrew Day School Albany",
    "Maimonides Hebrew Day School Florida",
    "Maimonides Jewish Day School Portland",
    "Manchester Mesivta",
    "Manhattan Day School",
    "Meor Manchester",
    "Mesivta Crown Heights",
    "Mesivta Detroit",
    "Miamonidies Hebrew Day School",
    "Mossad Oholei Yossef Yitschok Lubavitch - Brazil",
    "N.E. Miles Jewish Day School",
    "New England Hebrew Academy",
    "Ohaley Jinuj Panama",
    "Oholei Torah Winnipeg",
    "Oholei Yosef Yitzchok Boys Manchester Uk",
    "Oholei Yosef Yitzchok Girls Manchester Uk",
    "Oholey Jinuj Buenos Aires, Argentina",
    "Ohr David Brooklyn",
    "Ohr Rueven",
    "Ohr Torah Cincinnati",
    "Online Cheder",
    "Or Menachem Brazil Boys",
    "Or Menachem Brazil Girls",
    "Orlando Jewish Day School",
    "Politz Hebrew Academy Philadelphia",
    "Providence Hebrew Day School",
    "Regional Multicultural Magnet School",
    "Scheck Hillel Community School",
    "Scranton Hebrew Day School",
    "Shaarei Chinuch Day School",
    "Shaloh House, Brighton, Ma",
    "Sinai School",
    "Talmud Torah Tiferes Shloima",
    "Talmudical Academy Maryland",
    "Tashbar Lakewood",
    "Tehillas Chaya Sara",
    "The Cheder Of The Bay Area",
    "The Clifton Cheder",
    "The McClelland School",
    "Tiferes Doniel Zurich",
    "Tiferes Mordechai",
    "Torah Academy For Girls Ny",
    "Torah Academy Of Boston",
    "Torah Academy Of Minneapolis",
    "Torah Academy Space Coast",
    "Torah Day School Of Atlanta",
    "Torah Day School Of Dallas",
    "Torah Day School Of Houston",
    "Torah Day School Of Ottawa",
    "Torah Day School Of Phoenix",
    "Torah School Of Greater Washington",
    "Toras Shalom",
    "Tzivot Menachem",
    "Vittorio Polacco Rome",
    "Yeshiva Ketana Of Manhattan",
    "Yeshiva Ketana Of Waterbury",
    "Yeshiva M'Kor Baruch Of Passaic",
    "Yeshiva Of Greater Washington",
    "Yeshiva Tiferes Elimelech",
    "Yeshiva Torah Temimah",
    "Yesoday Hatorah School",
    "Yeshiva Ketana Ohr Reuven, Suffern, New York"
];

foreach ($schools as $school) {
    $sql = "insert into non_th_schools set school_name = '" . addslashes($school) . "'";
    if (! mysql_query($sql)) {
        echo "Error in qry: " . $sql . "<br />";
    }
}