<?php
	include "config.phtml";
	include "parameters.phtml";
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
<meta http-equiv="cache-control" content="public" />
<meta http-equiv="expires" content="1" />
<meta http-equiv="imagetoolbar" content="no" />
<meta http-equiv="content-language" content="en-US" />
<meta name="language" content="en"/>
<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
<title>Mashpia Mobile</title>
<script type="text/javascript" src="<?php print $sn; ?>/js/back-end/admin/jquery2.js"></script>
<script type="text/javascript" src="<?php print $sn; ?>/js/back-end/admin/jquery-ui2.js"></script>
<script type="text/javascript" src="<?php print $sn; ?>/js/back-end/admin/jquery.dump.js"></script>
<script type="text/javascript" src="<?php print $sn; ?>/js/mobile/llqrcode.js"></script>
<script src="<?php print $sn; ?>/js/mobile/front.js" type="text/javascript"></script>
<link href="<?php print $sn; ?>/css/mobile/front.css" rel="stylesheet" />
<script>
$(document).ready(function () {
	$('form').submit(function (e) {
		e.preventDefault();
		$.ajax({
			type : "POST",
			cache : false,
			url : '<?php echo $sn; ?>/hebrewschools/processbarcode2<?php print $strParamPath; ?>',
			dataType : "text",
			data: {
				mixBarCode : $('#barcode').val()
			},
			success : function(strResponse) {
				if (strResponse.match(/"success":"true"/)) {
					$('#barcode').css({
						'background-color' : 'green'
					}).animate({
						'background-color' : '#fff'
					},2000);
					$('#barcode').val('');
				} else {
					$('#barcode').css({
						'background-color' : 'red'
					}).animate({
						'background-color' : '#fff'
					},2000);
				}
			}
		});
	});
});
</script>
</head>
<body>
	<form>
	<div id="main_frame">
		<table id="main" cellpadding="0" cellspacing="0" border="0" width="100%" height="100%">
			<tr>
				<td style="vertical-align: top;height:1px;background:url('/images/ckids/bg_back_blue.jpg') repeat scroll 0 0 rgba(0, 0, 0, 0)">
					<table id="profile" cellpadding="0" cellspacing="0" border="0" width="100%" height="100%">
						<tr>
							<td width="100">
								<div style="width:80px;background-color: #fff;"><img src="<?php print $sn; ?>/imgs/v/src/<?php print $this->objUser->image_id; ?>/w/80/h/80" style="width:80px;height:80px;" /></div>
							</td>
							<td>
								<div style="color:#ffcb05;font-size:20pt;">
								<?php print $this->objUser->first_name; ?>
								<?php print $this->objUser->last_name; ?>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td>
					<div id="outframe" class="inherit_height">
						<div id="outdiv">

						</div>
					</div>
					<canvas style="display:none;" id="qr-canvas" width="800" height="600"></canvas>
					<div  style="display:none;" id="result"></div>
				</td>
			</tr>
			<tr>
				<td style="vertical-align: bottom;height:1px;">
					<div id="scanner_overlay" class="inherit_height2 scalefontmarker">
						<table cellpadding="0" cellspacing="0" border="0" width="100%" height="100%">
							<tr>
								<td style="text-align:center;vertical-align: middle;">
									<div>
										<input id="barcode" class="scalefont" type="text" />
									</div>
								</td>
							</tr>
						</table>
					</div>
					<img src="<?php print $sn; ?>/images/mobile/mobile-ckid-footer.png" style="width:100%;height:auto;vertical-align: bottom;" />
				</td>
			</tr>
		</table>
	</div>
	</form>
</body>
</html>