<?php
	include "config.phtml";
	include "parameters.phtml";
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
<meta http-equiv="cache-control" content="public" />
<meta http-equiv="expires" content="1" />
<meta http-equiv="imagetoolbar" content="no" />
<meta http-equiv="content-language" content="en-US" />
<meta name="language" content="en"/>
<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
<title>Mashpia Mobile</title>
<style type="text/css">
body{
    width:100%;
    text-align:center;
}
img{
    border:0;
}
#main{
    margin: 15px auto;
    background:white;
    overflow: auto;
	width: 100%;
}
#header{
    background:white;
    margin-bottom:15px;
}
#mainbody{
    background: white;
    width:100%;
}
#footer{
    background:white;
}
#v{
    width:320px;
    height:240px;
}
#qr-canvas{
    display:none;
}
#qrfile{
    width:320px;
    height:240px;
}
#mp1{
    text-align:center;
    font-size:35px;
}
#imghelp{
    position:relative;
    left:0px;
    top:-160px;
    z-index:100;
    font:18px arial,sans-serif;
    background:#f0f0f0;
	margin-left:35px;
	margin-right:35px;
	padding-top:10px;
	padding-bottom:10px;
	border-radius:20px;
}
.selector{
    margin:0;
    padding:0;
    cursor:pointer;
    margin-bottom:-5px;
}
#outdiv
{
    width:320px;
    height:240px;
	border: solid;
	border-width: 3px 3px 3px 3px;
}
#result{
    border: solid;
	border-width: 1px 1px 1px 1px;
	padding:20px;
	width:70%;
}

ul{
    margin-bottom:0;
    margin-right:40px;
}
li{
    display:inline;
    padding-right: 0.5em;
    padding-left: 0.5em;
    font-weight: bold;
    border-right: 1px solid #333333;
}
li a{
    text-decoration: none;
    color: black;
}

#footer a{
	color: black;
}
.tsel{
    padding:0;
}

</style>
<script type="text/javascript" src="<?php print $sn; ?>/js/back-end/admin/jquery2.js"></script>
<script type="text/javascript" src="<?php print $sn; ?>/js/back-end/admin/jquery-ui2.js"></script>
<script type="text/javascript" src="<?php print $sn; ?>/js/back-end/admin/jquery.dump.js"></script>
<script type="text/javascript" src="<?php print $sn; ?>/js/mobile/llqrcode.js"></script>
<script type="text/javascript" src="<?php print $sn; ?>/js/mobile/webqr.js"></script>
<link href="<?php print $sn; ?>/css/mobile/front.css" rel="stylesheet" />
</head>

<body>
<div id="main">
<div id="mainbody">
<div id="outdiv"></div>
<div id="result"></div>
</div>
</div>
<canvas id="qr-canvas" width="40" height="40"></canvas>
</body>

</html>