<?php
	include "config.phtml";
	include "parameters.phtml";
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
<meta http-equiv="cache-control" content="public" />
<meta http-equiv="expires" content="1" />
<meta http-equiv="imagetoolbar" content="no" />
<meta http-equiv="content-language" content="en-US" />
<meta name="language" content="en"/>
<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
<title>Mashpia Mobile</title>
<script type="text/javascript" src="<?php print $sn; ?>/js/back-end/admin/jquery2.js"></script>
<script type="text/javascript" src="<?php print $sn; ?>/js/back-end/admin/jquery-ui2.js"></script>
<script type="text/javascript" src="<?php print $sn; ?>/js/back-end/admin/jquery.dump.js"></script>
<script type="text/javascript" src="<?php print $sn; ?>/js/mobile/llqrcode.js"></script>
<script src="<?php print $sn; ?>/js/mobile/front.js" type="text/javascript"></script>
<script src="<?php print $sn; ?>/js/mobile/addbarcodereader.js" type="text/javascript"></script>
<link href="<?php print $sn; ?>/css/mobile/front.css" rel="stylesheet" />
<script>
$(document).ready(function () {
	$('form').submit(function (e) {
		e.preventDefault();
		$.ajax({
			type : "POST",
			cache : false,
			url : '<?php echo $sn; ?>/mobile/index<?php print $strParamPath; ?>',
			dataType : "text",
			data: {
				bar_code : $('#barcode').val()
			},
			success : function(strResponse) {
				if (strResponse == '{"success":"true"}') {
					window.location.href='<?php echo $sn; ?>/mobile/profile<?php print $strParamPath; ?>';
					$('#barcode').css({
						'background-color' : 'green'
					}).animate({
						'background-color' : '#fff'
					},'slow');
				} else {
					$('#barcode').css({
						'background-color' : 'red'
					}).animate({
						'background-color' : '#fff'
					},'slow');
				}
			}
		});
	});
});
</script>
</head>
<body>
	<audio id="audio" preload controls style="display:none">
		<source src="/media/beep.wav" type="audio/wav" />
	</audio>
	<form>
	<div id="main_frame">
		<table id="main" cellpadding="0" cellspacing="0" border="0" width="100%" height="100%">
			<tr>
				<td style="vertical-align: top;height:1px;">
					<img src="<?php print $sn; ?>/images/mobile/mobile-ckid-header2.png" style="width:100%;height:auto;vertical-align:top;" />
				</td>
			</tr>
			<tr>
				<td>
					<div id="outframe" class="inherit_height">
						<div id="outdiv">

						</div>
					</div>
					<canvas style="display:none;" id="qr-canvas" width="800" height="600"></canvas>
					<div  style="display:none;" id="result"></div>
				</td>
			</tr>
			<tr>
				<td style="vertical-align: bottom;height:1px;">
					<div id="scanner_overlay" class="inherit_height2 scalefontmarker">
						<table cellpadding="0" cellspacing="0" border="0" width="100%" height="100%">
							<tr>
								<td style="text-align:center;vertical-align: middle;">
									<div>
										<input id="barcode" class="scalefont" type="text" />
									</div>
								</td>
							</tr>
						</table>
					</div>
					<img src="<?php print $sn; ?>/images/mobile/mobile-ckid-footer.png" style="width:100%;height:auto;vertical-align: bottom;" />
				</td>
			</tr>
		</table>
	</div>
	</form>
</body>
</html>