<?php
	include "config.phtml";
	$user_session_data = new Zend_Session_Namespace('user_session_data');
	
	$strUrl = "";
	if (isset($this->intHost))
		$strUrl .= "host_id/" . $this->intHost . "/";
		
	if (isset($this->intNetwork))
		$strUrl .= "network_id/" . $this->intNetwork . "/";
		
	if (isset($this->intInstitution))
		$strUrl .= "institution_id/" . $this->intInstitution . "/";
?>

<div class="slider">
	
    <div class="col_title">
		<span>Add prize to <?php print ($user_session_data->institution_type == "School" ? "classes" : "bunks"); ?></span>
    </div>
	
    <div class="col_content">
		
        <div id="lists" class="module lists forms">
			
			<div class="module_content">
				
<?php
//var_dump($this->arrClasses);exit;
	if (!count($this->arrClasses))
    {
?>
				<div class="module" style="padding:5px;">There are no classes available to view.</div>
<?php
    }
    else
    {
?>
				<form name="form" id="form" method="post" action="">
					<ul>
<?php
		if (isset($this->boolTemplate))
		{
			if (!$this->objRoles->isRole('Teacher'))
			{
?>
						<li>
							<a class="link" href="<?php print $sn . "/store/prizeaddtemplates/" . $strUrl; ?>">
								<div class="icon"></div>
								<div class="title">Select all <?php print $user_session_data->institution_type == "School" ? "classes" : "bunks"; ?></div>
							</a>
						</li>
<?php
			}
			foreach ($this->arrClasses as $objClass)
			{
?>
						<li>
							<a class="link" href="<?php echo $sn; ?>/store/prizeaddtemplates/<?php echo $strUrl . "class_id/" . $objClass->class_id; ?>">
								<div class="icon"></div>
<?php
				if ($user_session_data->institution_type == "School")
				{
?>
								<div class="title"><?php echo ($user_session_data->institution_type == "School" ? "Grade" : "Bunk") . ": " . $objClass->grade . $objClass->sub; ?> <?php echo $objClass->teacher; ?></div>
<?php
				}
				else
				{
?>
								<div class="title"><?php echo ($user_session_data->institution_type == "School" ? "Grade" : "Bunk") . ": " . $objClass->sub; ?> <?php echo $objClass->teacher; ?></div>
<?php
				}
?>
							</a>
						</li>
<?php
			}
		}
		else
		{ // boolTemplate == false
			if (!$this->objRoles->isRole('Teacher'))
			{
?>
						<li>
							<a class="link" href="<?php print $sn . "/store/prize/" . $strUrl; ?>">
								<div class="icon"></div>
								<div class="title">Select all <?php print $user_session_data->institution_type == "School" ? "classes" : "bunks"; ?></div>
							</a>
						</li>
<?php
			}
			foreach ($this->arrClasses as $objClass)
			{
?>
						<li>
							<a class="link" href="<?php echo $sn; ?>/store/prize/<?php echo $strUrl . "class_id/" . $objClass->class_id; ?>">
								<div class="icon"></div>
<?php
				if ($user_session_data->institution_type == "School")
				{
?>
								<div class="title"><?php echo ($user_session_data->institution_type == "School" ? "Grade" : "Bunk") . ": " . $objClass->grade; ?> <?php echo $objClass->sub; ?> - <?php echo $objClass->teacher; ?></div>
<?php
				}
				else
				{
?>
								<div class="title"><?php echo ($user_session_data->institution_type == "School" ? "Grade" : "Bunk") . ": " . $objClass->sub; ?> - <?php echo $objClass->teacher; ?></div>
<?php
				}
?>
							</a>
						</li>
<?php
			}
		}
?>
					</ul>
				</form>
<?php
    }
?>
			</div>
			
		</div>
		
	</div>
	
</div>