<?php
	include "config.phtml";
	if(!isset($this->intUserId))
		$strUrl = $sn . "/store/prizeview/";
	else
		$strUrl = $sn . "/store/prizeviewbyuser/";
		
	if (isset($this->intHost))
		$strUrl .= "host_id/" . $this->intHost . "/";
	if (isset($this->intNetwork))
		$strUrl .= "network_id/" . $this->intNetwork . "/";
	if (isset($this->intInstitution))
		$strUrl .= "institution_id/" . $this->intInstitution . "/";
	if (isset($this->intUserId))
		$strUrl .= "user_id/" . $this->intUserId . "/";
?>
<div class="slider">
	<div class="col_title">
			<span>Prize Status</span>
	</div>
	<div class="col_content">

		<div id="lists" class="module lists forms">
			<div class="module_content">
				<ul>
					<li>
						<a class="link" href="<?php echo $strUrl; ?>status/active">
							<div class="icon"></div>
							<div class="title">Active prizes</div>
						</a>
					</li>
					<li>
						<a class="link" href="<?php echo $strUrl; ?>status/inactive">
							<div class="icon"></div>
							<div class="title">Inactive prizes</div>
						</a>
					</li>
				</ul>
			</div>
		</div>

	</div>
</div>