<?php
	include "config.phtml";
	include "parameters.phtml";
?>

<div class="slider" id="slider_prizeinstitutions">
	
	<div class="col_title">
		<span>Prize Institutions</span>
	</div>
	
	<div class="col_content">

<?php
	if (count($this->objInstitutions) == 0)
	{
?>
		<div class="module" style="padding:5px;">
			There are no Institutions available to display.
		</div>
<?php
	}
	else
	{
?>
			<div id="lists" class="module lists forms">
				
				<div class="module_content">
					
					<form name="campaignhosts" id="campaignhosts" method="post" action="">
						<ul>
								<li>
									<a class="link" href="<?php echo $sn . "/store/prizeview" . $strParamPath; ?>">
										<div class="icon"></div>
										<div class="title">> Skip to Prize List</div>
									</a>
								</li>
<?php
		foreach ($this->objInstitutions as $objInstitution)
		{
?>
							
								<li>
									<a class="link" href="<?php echo $sn . "/store/prizeview/institution_id/" . $objInstitution->institution_id . $strParamPath; ?>">
										<div class="icon"></div>
										<div class="title"><?php echo $objInstitution->name; ?></div>
									</a>
								</li>
<?php
		}
?>
							
						</ul>
					</form>
				</div>
			</div>		
<?php
	}
?>


	</div>
</div>