<?php
	include "config.phtml";
	include "parameters.phtml";
	$user_session_data = new Zend_Session_Namespace('user_session_data');
?>

<script>
	$(document).ready(function()
	{
		var list_item = "";
		var instchecklist = "";
		var action = "";

		//$(".slider:last .instchecklist input:checked").parent().addClass("selected");
		$(".slider:last .instchecklist input:checked").closest("li").find("#edit_prize").fadeIn();

		$(".slider:last .instchecklist .checkbox-select").click(function(event) {
			action = "install";
			$(".slider:last #action").val("install");
			list_item = $(this).parents('li');
			$(".slider:last #template_id").val(list_item.attr("id"));
			instchecklist = $(this).parents('.instchecklist');
			$('.slider:last #submit_button').trigger('click');
		});

		$(".slider:last .instchecklist .checkbox-deselect").click(function(event) {
			action = "uninstall";
			$(".slider:last #action").val("uninstall");
			list_item = $(this).parents('li');
			$(".slider:last #prize_id").val(list_item.attr("id"));
			instchecklist = $(this).parents('.instchecklist');
			$('.slider:last #submit_button').trigger('click');
		});					

		$('.slider:last #submit_button').click( function(e) {
			e.preventDefault();
			$.ajax({
				type : "POST",
				cache : false,
				//start: $("#processing_status").html('Loading...').fadeIn("slow"),
				url : '<?php print $sn;?>/store/prizeinstall',
				dataType : "text",
				data: $('.slider:last form').serialize(),
				success : function(response) {
					if (response.match(/^[0-9]+$/)) {
						if (action == "install") {
							$(list_item).attr("id", response);
							$(list_item).attr("name", response);
							$(instchecklist).addClass("selected");
							$(instchecklist).find(":checkbox").attr("checked","checked");
							$(list_item).css({ backgroundColor: '#9fe194' }).delay(500).animate({'background-color': '#eee'}, 500, function(){$(this).css({'background-color':''})});
							$(list_item).find('.progress').show().delay(500).fadeOut(500);	
							$(list_item).find('#edit_prize').fadeIn();
						} else {
							$(list_item).attr("id", response);
							$(list_item).attr("name", response);                                
							$(instchecklist).removeClass("selected");
							$(instchecklist).find(":checkbox").removeAttr("checked");
							$(list_item).css({ backgroundColor: '#e19494' }).delay(500).animate({'background-color': '#eee'}, 500, function(){$(this).css({'background-color':''})});
							$(list_item).find('.progress').show().delay(500).fadeOut(500);
							$(list_item).find('#edit_prize').fadeOut();
						}
					} else {
						$(".slider:last #processing_status").html(response).fadeIn("slow");
					}
				}
			});
		});
	});
</script>

<div class="slider">
	<div class="col_title">
		<span>Add / Remove Host Prizes</span>
	</div>
	<div class="col_content camper">
		<div class="module form" id="module-info">
			<div class="module_content list">
				<form>
					<input type="hidden" name="template_prize_id" id="template_id" value="" />
					<input type="hidden" name="prize_id" id="prize_id" value="" />
					<input type="hidden" name="action" id="action" value="" />                                            
					<ul>
<?php
	foreach ($this->arrPrizes as $objPrize)
	{
		if ($objPrize->template_prize_id) {
			$selected = " selected ";
			$checked = " checked ";
		} else {
			
			$selected = "";
			$checked = "";
		}
		$prize_id = $objPrize->prize_id;
?>
						<li name="<?php print $prize_id; ?>" id="<?php print $prize_id; ?>">
							<span class="action">
								<span class="instchecklist<?php print $selected; ?>">
									<input type="checkbox" class="checkbox<?php print $checked; ?>"<?php print $checked; ?>>
									<span class="install">
										<a class="button checkbox-select" href="#" >
											<span class="icon"></span>Install
										</a>
									</span>
									<span class="uninstall">
										<a class="button checkbox-deselect" href="#">
											<span class="icon"></span>Uninstall
										</a>
										<a id="edit_prize" class="button link" style="display:none" title="Edit Prize" href="<?php print $sn . "/store/prize/prize_id/" . $prize_id . $strParamPath; ?>">
											Edit Prize
										</a>
									</span>
									<span class="progress">Progress</span>
								</span>
						    </span>
						    <span class='icon bullet'></span>
						    <span class='label'>
								<span class='label title'><?php print $objPrize->prize_type; ?> </span> <?php print $objPrize->prize_name; ?>
							</span>
						    <div class='clear'></div>
						</li>
<?php
	}
?>
						<div id="processing_status"></div>
						<li>
							<span>
								<a href="#" name="submit_button" id="submit_button" title="Save" class="button submit" style="display:none;">Save</a>
							</span>
							<div class="clear"></div>
						</li>
					</ul>
    			</form>
			</div>
		</div>
	</div>
</div>