<?php
	include "config.phtml";
	$strUrl = "";
	if ($this->intPrize)
		$strUrl .= "prize_id/" . $this->intPrize . "/";
?>
<div class="slider">
	<div class="col_title">
		<span>Rules Hosts</span>
	</div>
	<div class="col_content">
		<div id="lists" class="module lists forms">
			<div class="module_content">
<?php
	if (!count($this->arrInstitutions))
	{
?>
				<div class="module" style="padding:5px;">There are no hosts available to view.</div>
<?php
	} else {
?>
				<form name="form" id="form" method="post" action="">
					<ul>
<?php
		foreach ($this->arrInstitutions as $objInstitution)
		{
?>
						<li>
							<a class="link" href="<?php echo $sn . "/store/rulesaddnetworks/" . $strUrl . "host_id/" . $objInstitution->institution_id; ?>">
								<div class="icon"></div>
								<div class="title"><?php echo $objInstitution->name; ?></div>
							</a>
						</li>
<?php
		}
?>
					</ul>
				</form>
<?php
	}
?>
			</div>
		</div>
	</div>
</div>