<?php
	include "config.phtml";
	$strUrl = "";
	if ($this->intPrize)
		$strUrl .= "prize_id/" . $this->intPrize . "/";
	if (isset($this->intHost))
		$strUrl .= "host_id/" . $this->intHost . "/";
	if (isset($this->intNetwork))
		$strUrl .= "network_id/" . $this->intNetwork . "/";
?>
<div class="slider">
	<div class="col_title">
		<span>Rules Institutions</span>
	</div>
	<div class="col_content">
		<div id="lists" class="module lists forms">
			<div class="module_content">
<?php
	if (!count($this->arrInstitutions))
	{
?>
				<div class="module" style="padding:5px;">There are no institutions available to view.</div>
<?php
	} else {
?>
				<form name="form" id="form" method="post" action="">
					<ul>
<?php
		if (
			isset($this->intNetwork)
			&& $this->objRoles->isAllowed('Network Administrator')
		) {
?>
						<li>
							<a class="link" href="<?php print $sn . "/store/rules/" . $strUrl; ?>">
								<div class="icon"></div>
								<div class="title">Select this network</div>
							</a>
						</li>
<?php
		}
		foreach ($this->arrInstitutions as $objInstitution)
		{
?>
						<li>
							<a class="link" href="<?php echo $sn; ?>/store/rules/<?php echo $strUrl . "institution_id/" . $objInstitution->institution_id; ?>">
								<div class="icon"></div>
								<div class="title"><?php echo $objInstitution->name; ?></div>
							</a>
						</li>
<?php
		}
?>
					</ul>
				</form>
<?php
	}
?>
			</div>
		</div>
	</div>
</div>