<?php
	include("config.phtml");

	$currency = "";
	if ($this->objPrize)
		$currency = $this->objPrize->currency;
?>
<script>
	$(document).ready(function()
	{
            var list_item = "";
            var checklist = "";
            var action = "";
            
	    $(".checklist input:checked").parent().addClass("selected");
					
	    $(".checklist .checkbox-select").click(function(event) {
			action = "enroll";
			$("#action").val("enroll");
			list_item = $(this).parents('li');
			$("#campaign_id").val(list_item.attr("id"));
			$("#lines_ahead").val(list_item.find(".lines_ahead").val());
			$("#ladder").val(list_item.find(".ladder_options").val());
			list_item.find(".enrollmentoptions").fadeOut("slow");
			checklist = $(this).parents('.checklist');
			$('#submit_button').trigger('click');
		});
					
	    $(".checklist .checkbox-deselect").click(function(event) {
			action = "unenroll";
			$("#action").val("unenroll");
			list_item = $(this).parents('li');
			$("#campaign_id").val(list_item.attr("id"));
			$("#lines_ahead").val(list_item.find(".lines_ahead").val());
			$("#ladder").val(list_item.find(".ladder_options").val());
			list_item.find(".enrollmentoptions").fadeIn("slow");
			checklist = $(this).parents('.checklist');
			$('#submit_button').trigger('click');
		});					
        
		$('#submit_button').click( function(e) {
			e.preventDefault();
                
			$.ajax({
				type : "POST",
				cache : false,
				url : '<?php print $sn;?>/administration/campaignenrollmentlist/user_id/<?php print $this->user_id;?>/',
				dataType : "text",
				data: $('#form_campaign_install_001').serialize(),
				success : function(response) {
					if (response.match(/^[0-9]+$/)) {
						if (action == "enroll") {
							$(checklist).addClass("selected");
							$(checklist).find(":checkbox").attr("checked","checked");
							$(list_item).css({ backgroundColor: '#9fe194' }).delay(500).animate({'background-color': '#eee'}, 500, function(){$(this).css({'background-color':''})});
							$(list_item).find('.progress').show().delay(500).fadeOut(500);	
						} else {                             
							$(checklist).removeClass("selected");
							$(checklist).find(":checkbox").removeAttr("checked");
							$(list_item).css({ backgroundColor: '#e19494' }).delay(500).animate({'background-color': '#eee'}, 500, function(){$(this).css({'background-color':''})});
							$(list_item).find('.progress').show().delay(500).fadeOut(500);								
						}
					} else {
						$("#slider_campaignenrollmentlist #processing_status").html(response).fadeIn("slow");
					}
				}
			});
	    });
		
	});
</script>

<div class="slider" id="slider_campaignenrollmentlist">
	<div class="col_title">
		<span>Enroll / Unenroll User Campaigns</span>
	</div>
	<div class="col_content camper">
		<div class="module form" id="module-info">
			<div class="module_content list">
				<form enctype="multipart/form-data" name="form_campaign_install_001" id="form_campaign_install_001" method="post" action="">
					<input type="hidden" name="campaign_id" id="campaign_id" value="" />
					<input type="hidden" name="action" id="action" value="" />
					<input type="hidden" name="lines_ahead" id="lines_ahead" value="" />
					<input type="hidden" name="ladder" id="ladder" value="" />
					
					<ul>
<?php
	foreach ($this->arrCampaigns as $objCampaign)
	{
		$campaign_id = $objCampaign->campaign_id;
		if ($objCampaign->boolEnrolled) {
			$selected = " selected ";
			$checked = " checked ";
		} else {
			$selected = "";
			$checked = "";
		}
?>
						<li name="<?php print $campaign_id; ?>" id="<?php print $campaign_id; ?>">
							<span class="action">
								<span class="checklist<?php print $selected; ?>">
									<input type="checkbox" class="checkbox<?php print $checked; ?>">
									<span class="install">
										<a class="button checkbox-select" href="#" >
											<span class="icon"></span>Enroll
										</a>
									</span>
									<span class="uninstall">													
										<a name="a_uninstall" class="button checkbox-deselect" title="Unenroll" href="#">
											<span class="icon"></span>Unenroll
										</a>
									</span>
									<span class="progress">Progress</span>
								</span>
						    </span>
						    <span class='icon bullet'></span>
						    <span class='label'>
								<span class='label title'><?php print $objCampaign->campaign_type; ?> </span> <?php print $objCampaign->campaign_name; ?>
								<span class='enrollmentoptions'<?php if ($objCampaign->boolEnrolled) print " style='display:none'"; ?>>
								<nobr>Ladder: <select class="ladder_options">
<?php
		foreach ($objCampaign->arrLadders as $objLadder)
		{
			print "<option value='" . $objLadder->ladder . "'>Quota " . $objLadder->velocity . "</option>";
		}
?>
								</select></nobr>
								<nobr>Lines already knows: <input type="text" class="lines_ahead" value="0" /></nobr>
								</span>
							</span>
						    <div class='clear'></div>
						</li>
<?php
	}
?>
						<div id="processing_status"><?php if ($this->message){ echo $this->message . "<br>"; }?></div>
						<li>
							<span>
								<a href="#" name="submit_button" id="submit_button" title="Save" class="button submit" style="display:none;">Save</a>
							</span>
							<div class="clear"></div>
						</li>
					</ul>
    			</form>
			</div>
		</div>
	</div>
</div>