<?php
	include "config.phtml";
	include "parameters.phtml";
?>

<div class="slider" id="ranksnetworks">
	<div class="col_title">
		<span>Ranks Networks</span>
	</div>	
	<div class="col_content">		
<?php
	if (count($this->objNetworks) == 0)
	{
?>
			<div class="module" style="padding:5px;">
				There are no Networks available to display.
			</div>
<?php
	}
	else
	{
?>
			<div id="lists" class="module lists forms">				
				<div class="module_content">					
					<form name="ranksnetworks" id="ranksnetworks" method="post" action="">
						<ul>							
<?php
		if (count($this->objNetworks) > 1)
		{
?>
							<li>
								<a class="link" href="<?php echo $sn . '/ranks/ranksinstitutions' . $strParamPath; ?>">
									<div class="icon"></div>
									<div class="title">> Skip to Institutions List</div>
								</a>
							</li>
<?php
		}
?>								
							<li>
								<a class="link" href="<?php echo $sn . "/ranks/rankslist" . $strParamPath; ?>">
									<div class="icon"></div>
									<div class="title">> Skip to Ranks List</div>
								</a>
							</li>								
<?php
		foreach ($this->objNetworks as $objNetwork)
		{
?>
							<li>
								<a class="link" href="<?php echo $sn . "/ranks/ranksinstitutions/network_id/" . $objNetwork->institution_id . $strParamPath; ?>">
									<div class="icon"></div>
									<div class="title"><?php echo $objNetwork->name; ?></div>
								</a>
							</li>						
<?php
		}
?>							
						</ul>
					</form>					
				</div>				
			</div>
<?
	}
?>
	</div>
</div>