<?php
	include "config.phtml";
	include "parameters.phtml";
?>

<script>
	$(document).ready(function()
	{
		$('#slide_ranksadd a.submit').click( function(e) {
			e.preventDefault();
			$.ajax({
				type : "POST",
				cache : false,
				start: $("#processing_status").html('Loading...').fadeIn("slow"),
				url : '<?php echo $sn . "/ranks/ranksadd" . $institution_string; ?>',
				dataType : "text",
				data: $('#form_ranksadd').serialize(),
				success : function(response) {
					if (response.match(/^[0-9]+$/)) {
						$("#processing_status").html("Save successful.").fadeIn("slow").delay(2000).fadeOut("slow");
					} else {
						$("#processing_status").html(response).fadeIn("slow");
					}
				}
			});
		});
	});
</script>

<div class="slider" id="slide_ranksadd">
	<div class="col_title"><span>Add New Rank</span></div>	
	<div class="col_content camper">
		<div class="module form" id="module-info">
			<div class="module_content list">
				
				<form name="form_ranksadd" id="form_ranksadd" method="post" action="">
					<ul>
						<li>
							<span class="label">Rank Name:</span>
							<span class="input"><input type="text" class="required" id="rank_name" name="rank_name" value="<?php echo $this->rank_name; ?>" size="25" minlength="2" /></span>
							<div class="clear"></div>
						</li>
                        <li>
							<span class="label">Rank medal color:</span>
							<span class="input"><input type="text" class="required" id="rank_color" name="rank_color" value="<?php echo $this->rank_color; ?>" size="25" minlength="2" /></span>
							<div class="clear"></div>
						</li>
                        <li>
							<span class="label">How many medals for this rank:</span>
							<span class="input"><input type="text" class="required" id="rank_medals" name="rank_medals" value="<?php echo $this->rank_medals; ?>" size="25" minlength="2" /></span>
							<div class="clear"></div>
						</li>
        				<div id="processing_status"><?php if ($this->message){ echo $this->message . "<br>"; }?></div>
						<li>
							<span><a href="#" title="Save" class="button submit">Save</a></span>							
							<div class="clear"></div>							
						</li>
					</ul>
				</form>
			</div>
		</div>
	</div>
</div>