<?php
	$user_session_data = new Zend_Session_Namespace('kiosk_user_session_data');
	$objPoints = new Points();
	$intUserPoints = $objPoints->user_points_sum(array(
		"user_id" => $user_session_data->user_id
	));
?>
<script language="javascript">
	function add_to_miles (intValue)
	{
		$("#total_points").html($("#total_points").html() * 1 + intValue);
	}
</script>
<div class="padding_top padding_left member_info_box">
	<div class="member_photo">
		<div class="member_photo_img">
			<IMG SRC='<?php print WEB_ROOT . "images/show-image/image_id/" . $this->objUser->image_id; ?>' WIDTH='150' HEIGHT='150'  ALT='' />
		</div>
		<div class="member_photo_cover"></div>
		<div class="member_badge"></div>
	</div>
	<div class="member_info">
		<ul>
			<li class="member_name"><?=$user_session_data->first_name?> <?=$user_session_data->last_name?></li>
			<li><label>Bunk: </label> <span><?php //print $user_session_data->grade?> <?php print $user_session_data->sub?></span></li>
			<li><label>Counselor:</label> <span><?=$user_session_data->teacher_name?></span></li>
			<li><label>Bunk Average:</label> <span><?=$user_session_data->platoon_avg_points?></span></li>
			<li><label>Base Average:</label> <span><?=$user_session_data->base_avg_points?></span></li>
			<li><label>Total Miles:</label> <span id="total_points"><?php print intval($intUserPoints); ?></span></li>
			<!--<li><label>5771 Miles:</label> <span></span></li>-->
		</ul>
	</div>
	<div class="clear"></div>
</div>