<?php
	include "config.phtml";
	include "parameters.phtml";
?>
<script language="javascript">
function eKeyPress(e)
{

}
$(document).ready(function()
{
	var objTimeout = false;
	var fnChange = function (e) {
		var charCode = (e.which) ? e.which : e.keyCode;
		if (charCode == 13) {
			e.preventDefault();
			if ($(this).find('.submit').length)
				$(this).find('.submit').click();
			else
				$(this).submit();
		}
		window.clearTimeout(objTimeout);
		objTimeout = window.setTimeout(function () {
			var arrData = $('body').data("reg_data");
			if (!arrData)
				arrData = {};
			var arrNewData = $('.slider:last form').serializeArray();
			for (var intItr in arrNewData)
			{
				arrData[arrNewData[intItr]["name"]] = arrNewData[intItr]["value"];
			}
			$('body').data("reg_data", arrData);
		}, 100);
	};
	$('.slider:last form').keyup(fnChange);
	$('.slider:last form').change(fnChange);
	$('.slider:last a.submit').click(function (e) {
		$('.slider:last form').submit();
	});
	$('.slider:last form').submit(function(e) {
		e.preventDefault();
		$(".slider:last .processing_status").fadeOut();
		$.ajax({
			type : "POST",
			cache : false,
			start: $(".slider:last #processing_status").html('Loading...').fadeIn(),
			url : '<?php echo $sn . "/registration/administrator" . $strParamPath; ?>',
			dataType : "text",
			data: $('.slider:last form').serialize(),
			success : function(strResponse) {
				try {
					var arrResponse = jQuery.parseJSON(strResponse);
				} catch(e) {
					$(".slider:last #processing_status").html('Sorry, there was an error: VU-E101-3RR3RE');
					alert("Sorry, there was an error: VA-J101-3RR3RE");
					alert(strResponse);
					return;
				}
				if (typeof(arrResponse) != "object") {
					$(".slider:last #processing_status").html('Sorry, there was an error: VU-E102-SDF8BX');
					alert("Sorry, there was an error: VA-J102-SDF8BX");
					return;
				} else {
					$(".slider:last #processing_status").fadeOut();
					if (arrResponse["error"]) {
						if (typeof(arrResponse["error"]) != "object") {
							$(".slider:last #processing_status").html(arrResponse["error"]);
						} else {
							for (strField in arrResponse["error"])
							{
								//alert($.dump($(".slider:last #" + strField).closest("li").html()));return;
								$(".slider:last #" + strField).closest("li").next().html(arrResponse["error"][strField]).fadeIn();
							}
						}
					} else if (arrResponse["success"] == "true") {
						var strURL = '<?php print $sn . "/registration/institution" . $strParamPath; ?>';
						slideURL(strURL);
					} else {
						alert("Sorry, there was an error: VA-J103-DS7DDS");
						//alert($.dump(arrResponse));
					}
				}
			}
		});
	});
});
</script>
<div class="slider" id="registration_administrator">
	<div class="col_title"><span>Administrator Information</span></div>
	<div class="col_content camper">
		<div class="module message" style="text-align: left">
			Create your new administrator account.
		</div>
		<div class="module form">
			<div class="module_content list">
				<form name="registration_administrator"  id="registration_administrator">
					<input type="hidden" id="registration_administrator_data" value="" />
					<ul>
						<li>
							<span class="label">First name: *</span>
							<span class="input"><input autocomplete="off" type="text" class="required" id="administrator_first_name" name="administrator_first_name" value="" size="25" minlength="2" /></span>
							<div class="clear"></div>
						</li>
						<div class="processing_status"></div>
						<li>
							<span class="label">Last name:*</span>
							<span class="input"><input autocomplete="off" type="text" class="required" id="administrator_last_name" name="administrator_last_name" value="" size="25" minlength="2" /></span>
							<div class="clear"></div>
						</li>
						<div class="processing_status"></div>
						<li>
							<span class="label">Email: *</span>
							<span class="input"><input autocomplete="off" type="text" class="required" id="administrator_email" name="administrator_email" value="" size="25" minlength="2" /></span>
							<div class="clear"></div>
						</li>
						<div class="processing_status"></div>
						<li>
							<span class="label">Cell phone: *</span>
							<span class="input"><input autocomplete="off" type="text" id="administrator_cell_phone" name="administrator_cell_phone" value="" size="25" minlength="2" /></span>
							<div class="clear"></div>
						</li>
						<div class="processing_status"></div>
						<li>
							<span class="label">Home phone:</span>
							<span class="input"><input autocomplete="off" type="text" id="administrator_phone_number" name="administrator_phone_number" value="" size="25" minlength="2" /></span>
							<div class="clear"></div>
						</li>
						<div class="processing_status"></div>
						<li>
							<span class="label">Address:</span>
							<span class="input"><input autocomplete="off" type="text" id="administrator_address" name="administrator_address" value="" size="25" minlength="2" /></span>
							<div class="clear"></div>
						</li>
						<div class="processing_status"></div>
						<li>
							<span class="label">City:</span>
							<span class="input"><input autocomplete="off" type="text" id="administrator_city" name="administrator_city" value="" size="25" minlength="2" /></span>
							<div class="clear"></div>
						</li>
						<div class="processing_status"></div>
						<li>
							<span class="label">Zip/Postal Code:</span>
							<span class="input"><input autocomplete="off" type="text" id="administrator_postal" name="administrator_postal" value="" size="25" minlength="2" /></span>
							<div class="clear"></div>
						</li>
						<div class="processing_status"></div>
						<li>
							<span class="label">State:</span>
							<span class="input"><input autocomplete="off" type="text" id="administrator_state" name="administrator_state" value="" size="25" minlength="2" /></span>
							<div class="clear"></div>
						</li>
						<div class="processing_status"></div>
						<li>
							<span class="label">Country:</span>
							<span class="input"><input autocomplete="off" type="text" id="administrator_country" name="administrator_country" value="" size="25" minlength="2" /></span>
							<div class="clear"></div>
						</li>
						<div class="processing_status"></div>
						<div id="processing_status" style="padding:4px"></div>
						<li>
							<span><a href="#" title="Next" class="button submit">Next</a></span>
							<div class="clear"></div>
						</li>
					</ul>
				</form>
			</div>
		</div>
	</div>
</div>