<?php
	include "public_header.phtml";
	include "config.phtml";
	include "parameters.phtml";
?>
</head>
	<body>
		<div id="wrapper">
			<div id="nav">
				<div class="col_title_bg"></div>

				<div class="col_title">Menu</div>
<?php
	include "menus/menu_registration.phtml";
?>
			</div>
			<div id="content">
				<div class="col_title_bg"></div>
				<div class="slider_container">
<?php
	include "login.phtml";
?>
				</div>
			</div>
		</div>
	</body>
</html>