<?php
	include "config.phtml";
	include "parameters.phtml";
?>
<script language="javascript">
function shipping_to_billing()
{
	$("#registration_payment #shipping_first_name").val($("#registration_payment #billing_first_name").val());
	$("#registration_payment #shipping_last_name").val($("#registration_payment #billing_last_name").val());
	$("#registration_payment #shipping_phone_number").val($("#registration_payment #billing_phone_number").val());
	$("#registration_payment #shipping_address").val($("#registration_payment #billing_address").val());
	$("#registration_payment #shipping_city").val($("#registration_payment #billing_city").val());
	$("#registration_payment #shipping_postal").val($("#registration_payment #billing_postal").val());
	$("#registration_payment #shipping_country").val($("#registration_payment #billing_country").val());
	$("#registration_payment #shipping_state").val($("#registration_payment #billing_state").val());
}

function administrator_to_shipping()
{
	var arrData = $('body').data("reg_data");
	$("#registration_payment #billing_first_name").val(arrData["administrator_first_name"]);
	$("#registration_payment #billing_last_name").val(arrData["administrator_last_name"]);
	$("#registration_payment #billing_phone_number").val(arrData["administrator_phone_number"]);
	$("#registration_payment #billing_address").val(arrData["administrator_address"]);
	$("#registration_payment #billing_city").val(arrData["administrator_city"]);
	$("#registration_payment #billing_postal").val(arrData["administrator_postal"]);
	$("#registration_payment #billing_state").val(arrData["administrator_state"]);
	$("#registration_payment #billing_country").val(arrData["administrator_country"]);
}

$(document).ready(function()
{
	var objTimeout = false;
	$('.slider:last form').keyup(function (e) {
		var charCode = (e.which) ? e.which : e.keyCode;
		if (charCode == 13) {
			e.preventDefault();
			if ($(this).find('.submit').length)
				$(this).find('.submit').click();
			else
				$(this).submit();
		}
		window.clearTimeout(objTimeout);
		objTimeout = window.setTimeout(function () {
			var arrData = $('body').data("reg_data");
			if (!arrData)
				arrData = {};
			var arrNewData = $('.slider:last form').serializeArray();
			for (var intItr in arrNewData)
			{
				arrData[arrNewData[intItr]["name"]] = arrNewData[intItr]["value"];
			}
			$('body').data("reg_data", arrData);
		}, 100);
	});

	var arrRegData = $('body').data("reg_data");
	for (var strKey in arrRegData)
	{
		$(".slider:last #" + strKey).val(arrRegData[strKey]);
	}

	$(".slider:last #to_be_charged").html(parseInt(kiosk_accessories_sum()) + 250);

	$('.slider:last form a.submit').click(function(e) {
		$(".slider:last .processing_status").fadeOut();
		$.ajax({
			type : "POST",
			cache : false,
			start: $(".slider:last #processing_status").html('Loading...').fadeIn(),
			url : '<?php echo $sn . "/registration/payment" . $strParamPath; ?>',
			dataType : "text",
			data: $('.slider:last form').serialize(),
			success : function(strResponse) {
				try {
					var arrResponse = jQuery.parseJSON(strResponse);
				} catch(e) {
					$(".slider:last #processing_status").html('Sorry, there was an error: VU-E101-3RR3RE');
					alert("Sorry, there was an error: VI-J101-SDF88D");
					alert(strResponse);
					return;
				}
				if (typeof(arrResponse) != "object") {
					$(".slider:last #processing_status").html('Sorry, there was an error: VU-E102-SDF8BX');
					alert("Sorry, there was an error: VI-J102-ASD9S9");
					return;
				} else {
					if (arrResponse["error"]) {
						if (typeof(arrResponse["error"]) != "object") {
							$(".slider:last #processing_status").html('Error: ' + arrResponse["error"]);
						} else {
							$(".slider:last #processing_status").fadeOut();
							for (strField in arrResponse["error"])
							{
								//alert($.dump($(".slider:last #" + strField).closest("li").html()));return;
								$(".slider:last #" + strField).closest("li").next().html(arrResponse["error"][strField]).fadeIn();
							}
						}
					} else if (arrResponse["success"] == "true") {
						$(".slider:last #processing_status").fadeOut();
						var strURL = '<?php print $sn . "/registration/confirm" . $strParamPath; ?>';
						slideURL(strURL);
					} else {
						$(".slider:last #processing_status").html("Sorry, there was an error: VI-J103-99DS0S");
						//alert($.dump(arrResponse));
					}
				}
			}
		});
	});
});
</script>

<div class="slider" id="registration_payment">
	<div class="col_title"><span>Billing Information</span></div>
	<div class="col_content camper">
		<form name="registration_payment" id="registration_payment" method="post" action="">
			<input type="hidden" name="registration_payment_data" value="" />
			<h2>Billing Information</h2>
			<div class="module form">
				<div class="module_content list">
					<ul>
						<li>
							<span class="input" style="padding:4px"><a href="#" onclick="administrator_to_shipping()" style="text-decoration:underline;color:#005A8C">Use Administration Information</a></span>
							<div class="clear"></div>
						</li>
						<li>
							<span class="label">First Name: *</span>
							<span class="input"><input autocomplete="off" type="text" name="billing_first_name" id="billing_first_name" class="required" value="" /></span>
							<div class="clear"></div>
						</li>
						<div class="processing_status"></div>
						<li>
							<span class="label">Last Name: *</span>
							<span class="input"><input autocomplete="off" type="text" name="billing_last_name" id="billing_last_name" value="" /></span>
							<div class="clear"></div>
						</li>
						<div class="processing_status"></div>
						<li>
							<span class="label">Phone Number:</span>
							<span class="input"><input autocomplete="off" type="text" name="billing_phone_number" id="billing_phone_number" value="" /></span>
							<div class="clear"></div>
						</li>
						<div class="processing_status"></div>
						<li>
							<span class="label">Address: *</span>
							<span class="input"><input autocomplete="off" type="text" name="billing_address" id="billing_address" value="" /></span>
							<div class="clear"></div>
						</li>
						<div class="processing_status"></div>
						<li>
							<span class="label">City:</span>
							<span class="input"><input autocomplete="off" type="text" name="billing_city" id="billing_city" value="" /></span>
							<div class="clear"></div>
						</li>
						<div class="processing_status"></div>
						<li>
							<span class="label">Postal/Zip Code: *</span>
							<span class="input"><input autocomplete="off" type="text" name="billing_postal" id="billing_postal" value="" /></span>
							<div class="clear"></div>
						</li>
						<div class="processing_status"></div>
						<li>
							<span class="label">State: *</span>
							<span class="input"><input autocomplete="off" type="text" name="billing_state" id="billing_state" value="" /></span>
							<div class="clear"></div>
						</li>
						<div class="processing_status"></div>
						<li>
							<span class="label">Country:</span>
							<span class="input"><input autocomplete="off" type="text" name="billing_country" id="billing_country" value="" /></span>
							<div class="clear"></div>
						</li>
						<div class="processing_status"></div>
					</ul>
				</div>
			</div>
			<h2>Shipping Information</h2>
			<div class="module form">
				<div class="module_content list">
					<ul>
						<li>
							<span class="input" style="padding:4px"><a href="#" onclick="shipping_to_billing();" style="text-decoration:underline;color:#005A8C">Use Billing Information</a></span>
							<div class="clear"></div>
						</li>
						<li>
							<span class="label">First Name:</span>
							<span class="input"><input autocomplete="off" type="text" name="shipping_first_name" id="shipping_first_name" value="" /></span>
							<div class="clear"></div>
						</li>
						<div class="processing_status"></div>
						<li>
							<span class="label">Last Name:</span>
							<span class="input"><input autocomplete="off" type="text" name="shipping_last_name" id="shipping_last_name" value="" /></span>
							<div class="clear"></div>
						</li>
						<div class="processing_status"></div>
						<li>
							<span class="label">Phone Number:</span>
							<span class="input"><input autocomplete="off" type="text" name="shipping_phone_number" id="shipping_phone_number" value="" /></span>
							<div class="clear"></div>
						</li>
						<div class="processing_status"></div>
						<li>
							<span class="label">Address: *</span>
							<span class="input"><input autocomplete="off" type="text" name="shipping_address" id="shipping_address" value="" /></span>
							<div class="clear"></div>
						</li>
						<div class="processing_status"></div>
						<li>
							<span class="label">City: *</span>
							<span class="input"><input autocomplete="off" type="text" name="shipping_city" id="shipping_city" value="" /></span>
							<div class="clear"></div>
						</li>
						<div class="processing_status"></div>
						<li>
							<span class="label">Postal/Zip Code: *</span>
							<span class="input"><input autocomplete="off" type="text" name="shipping_postal" id="shipping_postal" value="" /></span>
							<div class="clear"></div>
						</li>
						<div class="processing_status"></div>
						<li>
							<span class="label">State: *</span>
							<span class="input"><input autocomplete="off" type="text" name="shipping_state" id="shipping_state" value="" /></span>
							<div class="clear"></div>
						</li>
						<div class="processing_status"></div>
						<li>
							<span class="label">Country: *</span>
							<span class="input"><input autocomplete="off" type="text" name="shipping_country" id="shipping_country" value="" /></span>
							<div class="clear"></div>
						</li>
						<div class="processing_status"></div>
					</ul>
				</div>
			</div>
			<h2>Credit Card Information</h2>
			<div class="module form">
				<div class="module_content list">
					<ul>
						<div class="processing_status"></div>
						<li>
							<span class="label">Credit Card * number:</span>
							<span class="input"><input autocomplete="off" type="text" name="creditcard_number" id="creditcard_number" class="required" value="" /></span>
							<div class="clear"></div>
						</li>
						<div class="processing_status"></div>
						<li>
							<span class="label">Expiration date: *</span>
							<span class="input">
								<select name="creditcard_expiration_month" id="creditcard_expiration_month">
								<?php
									$current_time_m = date('m');
									for ($i = 1; $i <= 12; $i++)
									{
										echo "<option value='$i'";
										if ($i == $current_time_m)
										{
											echo " selected='selected'";
										}
										$month_text = date("F", mktime(0, 0, 0, $i+1, 0, 0, 0));
										echo ">$month_text</option>";
									}
								?>
								</select>
								<select name="creditcard_expiration_year" id="creditcard_expiration_year">
								<?php
									$year = date('Y')-1;
									for($i=0; $i < 6; $i++)
									{
										$year++;
								?>
									<option value="<?php echo $year;?>"><?php echo $year;?></option>
								<?php
									}
								?>
								</select>
							</span>
							<div class="clear"></div>
						</li>
						<div class="processing_status"></div>
						<li>
							<span class="label">CCV: *</span>
							<span class="input"><input autocomplete="off" type="text" name="creditcard_ccv" id="creditcard_ccv" value="" class="required" width="50px"/></span>
							<div class="clear"></div>
						</li>
						<div class="processing_status"></div>
					</ul>
				</div>
			</div>
			<!--h2>Authorization</h2>
			<div class="module message">
				There is a $250 fee to register your Hebrew School for the year 5773. This comes with free registration for 25 Students. After that you will be charged $10 per student registered. Registration charges recur on a yearly basis.
			</div-->
			<div class="module form">
				<div class="module_content list">
					<ul>
						<div id="processing_status" style="padding:4px"></div>
						<li>
							<span><a href="#" title="Next" class="button submit">Next</a></span>
							<div class="clear"></div>
						</li>
					</ul>
				</div>
			</div>
		</form>
	</div>
</div>