<div class="slider">
	<div class="col_title">
		<span>HTML / Sliders</span>
	</div>
	<div class="col_content">
		<div class="module_collection">
			<p>
				The code used to build a page (also know as a slider) always starts
				with a slider div:
				<pre class="brush: php; html-script: true;"><div class="slider"></pre>
				The content always goes in a div named col_content:
				<pre class="brush: php; html-script: true;"><div class="col_content"></pre>
				The headline above the slider always goes in a span under the div named col_title:
				<pre class="brush: php; html-script: true;">
<div class="col_title">
	<span>Slider Title</pre>
				Here is a full example that can be copy pasted directly and will
				function just like a normal slider:
			</p>
			<pre class="brush: php;  html-script: true;">
&nbsp;
<div class="slider">
	<div class="col_title">
		<span>Slider Title</span>
		<div class="title_help info" title="Information about this slider accessed through a small question mark to the right of the slider headline."></div>
	</div>
	<div class="col_content">
		The contents of the slider
	</div>
</div>
			</pre>
		</div>
	</div>
</div>
<script>
SyntaxHighlighter.highlight();
</script>