<div class="slider">
	<div class="col_title">
		<span>HTML / Sliders</span>
	</div>
	<div class="col_content">
		<div class="module_collection">
			<h2>Headline</h2>
			<pre class="brush: php;  html-script: true;">
&nbsp;
<h2>Headline</h2>
&nbsp;
</pre>

&nbsp;
			<h4>
				Left aligned headline: &nbsp;
				<div title="Right aligned helper info." class="help_icon info"></div>
			</h4>
			<pre class="brush: php;  html-script: true;">
&nbsp;
<h4>
	Left aligned headline: &nbsp;
	<div title="Right aligned helper info." class="help_icon info"></div>
</h4>
&nbsp;
</pre>
&nbsp;
			<div class="module lists">
				<div class="module_content">
					<ul>
						<li>
							Add this box when you need to display some information
							that should be visible at all times unlike help icons.
						</li>
						<li>
							Add more LI tags to the UL list to create sections if needed.
						</li>
					</ul>
				</div>
			</div>


		</div>
	</div>
</div>
<script>
SyntaxHighlighter.highlight();
</script>