<?php
	include "config.phtml";
	include "parameters.phtml";
	$objUserSession = new Zend_Session_Namespace("user_session_data");
?>
<script language="javascript">
$(document).ready(function()
{
	$(this).delay(1).queue(function () {
		$(this).dequeue();
		$('.slider:last input[type=checkbox]').iphoneStyle({});
		$('.slider:last form.email_admins input[type=checkbox]').bind('didchange', function () {
			$.ajax({
				type : "POST",
				cache : false,
				url : '<?php echo $sn . "/settings/notifications" . $strParamPath; ?>',
				dataType : "text",
				data: $('.slider:last form').serialize(),
				success : function(strResponse) {
					try {
						var arrResponse = jQuery.parseJSON(strResponse);
					} catch(e) {
						$.alert(strResponse);
						$(".slider:last .processing_status").html('<?php print text("Sorry, there was an error"); ?>: VU-rp01-3RR3RE');
						return;
					}
					if (typeof(arrResponse) != "object") {
						$.alert(strResponse);
						$(".slider:last .processing_status").html('<?php print text("Sorry, there was an error"); ?>: VU-rp102-SDF8BX');
						return;
					} else {
						$(".slider:last .processing_status").fadeOut();
						if (arrResponse.success) {
							$(".slider:last .processing_status").html("Saved.").delay(1000).fadeOut("slow");
						} else {
							$(".slider:last .processing_status").html('<?php print text('Sorry, there was an error'); ?>: VU-rp103-sdf98s').fadeIn("slow");
						}
					}
				}
			});
		});
	});
});
</script>
<div class="slider">
	<style>
		.processing_status {
			color: black;
		}
	</style>
	<div class="col_title">
		<span><?php print text("Event Notifications"); ?></span>
		<div class="title_help info" title="<?php print text('Set up notifications on events in the system.'); ?> "></div>
	</div>
	<div class="col_content">
		<h2><?php print text("Email all admins when:"); ?></h2>
		<div class="module form">
			<div class="module_content lists">
				<form class="email_admins">
					<ul>
						<li>
							<span class="label" style="width:380px"><?php print text("A [|student|] checked out a prize from the store"); ?></span>
							<span class="input" style="margin: 4px 0px 0px 1px;">
								<input type="checkbox" name="kiosk__store_admin_notifications" value="1"<?php print $this->arrUserOptions["kiosk"]["store_admin_notifications"] ? " checked=\"checked\"" : ""; ?> />
							</span>
							<div class="clear"></div>
						</li>
						<div class="processing_status"></div>
					</ul>
				</form>
			</div>
		</div>
	</div>
</div>