<?php
include "config.phtml";
include "parameters.phtml";
$objRoles = new Roles();
?>
		<script>
			var function_name;
            $(document).ready(function() {
				$('#overlay').css({
					width: 650,
					left:$(document).width()/2-650/2
				});
				$('.editable').editable(function(value, settings) {
						return(value);
					},
					{
						indicator : '<img src="images/ajax-loader-sm.gif"/>',
						submit:'<img onclick="hide_editable(this);" src="images/bullet_disk.png"/>',
						onblur:'ignore',
						width:'auto',
						height:'auto',
						style:'inherit',
						tooltip: 'Click to edit...'
					}
				);

                $(".checklist input:checked").parent().addClass("selected");

				//**************************************//
				// ***** Assign a task to a group ***** //

				$(".edit a, .edit_row input[type='text']").die().live('click',
                    function(event) {
                        event.preventDefault();
                        $(this).parents('li').addClass("editing");
                    }
                );
				$(".edit a, .edit_row input").die().live('click', function () {
					$(this).parents('li').addClass("editing");
				});

                $(".save a").die().live('click',
                    function(event) {
						var checklist = $(this).closest('.checklist');
						var list_item = $(this).closest('li');
						//$.alert(list_item);
						var id = $(list_item).attr("id");

                        event.preventDefault();
                        $(this).parents('li').removeClass("editing");

						var task_name;
						var points;
						if (!id) {
							var input_one = $(list_item).find('input').get(1);
							var input_two = $(list_item).find('input').get(2);
							var input_three = $(list_item).find('input').get(3);
							var input_four = $(list_item).find('input').get(4);
							function_name = "add_camp_task";
						} else {
							var info = id.split("_");
							var camp_task_id = info[1];
							var input_one = $(list_item).find('input').get(0);
							var input_two = $(list_item).find('input').get(1);
							var input_three = $(list_item).find('input').get(2);
							var input_four = $(list_item).find('input').get(3);
							function_name = "update_task";
						}
						task_name = input_one.value;
						points = input_two.value;
						is_checkbox = $(input_three).attr('checked');
						is_locked = $(input_four).attr('checked');
						var strURL = '<?php echo $sn . "/incrementals/taskmanager' + (id ? '/task/' + id : '') + '" . $strParamPath; ?>';
						$.ajax({
							type : "POST",
							cache : false,
							//start: $("#slider_bookeditor #loading_status").html('Loading...').fadeIn("slow"),
							url : strURL,
							dataType : "text",
							data: {
								"job" : function_name,
								"task_name" : task_name,
								"points" : points,
								"is_checkbox" : is_checkbox,
								"is_locked" : is_locked
							},
							success : function(strResponse) {
								if (strResponse == "saved") {
									// Saved!
								} else if (strResponse.match(/^(_?)[0-9]+$/)) {
									var new_id = "cti_" + strResponse;
									$(list_item).attr("id", new_id);
									$(checklist).find(":checkbox").attr("id", strResponse);
									window.parent.popout_change_total(1);
									$(checklist).addClass("selected");
									$(checklist).find(":checkbox").attr("checked","checked");
								}
								else
								{
									alert("Sorry, there was an error: VI-TM103-SD7FDD");
									alert(strResponse);
								}
							}
						});
                    }
                );

				var fnDelete = function(objThis) {
					var intItemId = $(objThis).parents('li').attr("id").split("_")[1];
					if (!intItemId)
					{
						$(objThis).parents('li').slideUp();
					}

					var strURL = '<?php echo $sn . "/incrementals/taskmanager/task/' + intItemId + '" . $strParamPath; ?>';
					$.ajax({
						type : "POST",
						cache : false,
						url : strURL,
						dataType : "text",
						data: {
							"job" : "delete_task"
						},
						success : function(strResponse) {
							if (strResponse == "1") {
								$(objThis).parents('li').slideUp();
								window.parent.popout_change_total(-1);
								$('.inactive_num').html($('.inactive_num').html()*1+1);
							}
							else
							{
								alert("Sorry, there was an error: VI-TM102-DG5Y5Y");
								alert(strResponse);
							}
						}
					});
				};

				$(".delete a").die().live('click', function (event) {
					event.preventDefault();
					fnDelete(this);
					$('.inactive_num').html($('.inactive_num').html()*1+1);
				});
				$(".checklist .checkbox-deselect").die().live('click', function (event) {event.preventDefault();fnDelete(this);});

                $("a.add_new_row").click(
                    function(event) {
                        event.preventDefault();
						var add_row_li = $(this).parents('li');
						var sample_row_data = $(this).parents('ul').find('.sample_row').html();
						$(add_row_li).before(sample_row_data);
						$(add_row_li).prev().find('input[type="text"]').first().click().val('').focus();
						$(add_row_li).prev().find('select.select').resetSS();
                    }
                );
				$('.reactivate').die().live('click', function () {
					var parent = this;
					var intTask = $(this).parent().find('input').attr('id');
					var strURL = '<?php echo $sn . "/incrementals/taskmanager/task/' + intTask + '" . $strParamPath; ?>';
					$.ajax({
						type : "POST",
						cache : false,
						url : strURL,
						dataType : "text",
						data: {
							"job" : "reactivate"
						},
						success : function(strResponse) {
							$(parent).closest('li').slideUp();
							window.parent.popout_change_total(1);
							$('.active_num').html($('.active_num').html()*1+1);
						}
					});
				});
				// Activate
                $(".checklist .checkbox-select").die().live('click',
                    function(event) {
						var list_item = $(this).parents('li');
						var checklist = $(this).parents('.checklist');
						$(list_item).css({ backgroundColor: '#9fe194' }).delay(500).animate({'background-color': '#eee'}, 500, function(){$(this).css({'background-color':''})});
						var intItemId = $(this).parents('li').attr("id").split("_")[1];
						var strURL = '<?php echo $sn . "/incrementals/taskmanager/task/' + intItemId + '" . $strParamPath; ?>';
						var input_one = $(list_item).find('input').get(0);
						var task_name = input_one.value;
						var input_two = $(list_item).find('input').get(1);
						var points = input_two.value;
						$.ajax({
							type : "POST",
							cache : false,
							url : strURL,
							dataType : "text",
							data: {
								"job" : "install_host_task",
								"task_name" : task_name,
								"points" : points
							},
							success : function(strResponse) {
								if (strResponse.match(/^[0-9]+$/)) {
									var new_id = "cti_" + strResponse;
									$(list_item).attr("id", new_id);
									$(checklist).removeClass("selected");
									$(checklist).addClass("selected");
									$(checklist).find(":checkbox").attr("checked","checked");
									$(checklist).find(":checkbox").attr("id", strResponse);
									window.parent.popout_change_total(1);
								}
								else
								{
									alert("Sorry, there was an error: VI-TM101-SDF7DD");
									alert(strResponse);
								}
							}
						});
                    }
                );

				$('select.select').sSelect();

				$('.link.inactive_tasks').click(function () {
					var strURL = '<?php print $sn; ?>/incrementals/taskmanager/inactive/1<?php print $strParamPath; ?>';
					$.ajax({
						type : "GET",
						cache : false,
						url : strURL,
						dataType : "text",
						success : function(strResponse) {
							$('#overlay .content').html(strResponse);
						}
					});
				});
				$('.link.active_tasks').click(function () {
					var strURL = '<?php print $sn; ?>/incrementals/taskmanager<?php print $strParamPath; ?>';
					$.ajax({
						type : "GET",
						cache : false,
						url : strURL,
						dataType : "text",
						success : function(strResponse) {
							$('#overlay .content').html(strResponse);
						}
					});
				});
            });
			// <?php print $this->campaign_id; ?>
		</script>

			<div class="slider">
                <div class="col_title"><?php print $this->objCampaign->campaign_name; ?></div>
				<div class="col_content">
					<div id="lists" class="module lists forms" style="margin-bottom:10px;">
						<div class="module_content">
							<ul>
								<li>
									Add or edit the task name you would like to appear on your point cards and on your point grid.
								</li>
								<li>
									Decide how many points the task should be worth.
								</li>
								<li>
									Decide if you want to be able to edit the point value when you print cards or enter the points in the grid or if the task point value should be locked.
								</li>
								<li>
									Click on the disk to save your changes.
								</li>
							</ul>
						</div>
					</div>
					<div class="module">
						<div class="module_content">
							<div class="list">
								<ul>
<?php
	if (count($this->arrTasks))
	{
		foreach ($this->arrTasks as $objTask)
		{
?>

									<li id="cti_<?php print $objTask->task_id; ?>" class="edit_row">
										<form>
											<span class="icon bullet"></span>
											<span class="label">
												<span class="label title"><?php
			if ($objTask->class_id > 0)
			{
				print "Teacher ";
			}
			else if ($objTask->campaign_id == $this->campaign_id && $objTask->installed_task_id)
			{
				print "Host "; // installed
			}
			else if ($objTask->campaign_id == $this->campaign_id && !$objTask->installed_task_id)
			{
				print "";
			}
			else
			{
				print "Host "; // uninstalled
			}
?><?php print $this->boolInactive ? 'Inactive ' : ''; ?>Task</span>
<?php
			if ($objRoles->isRole("Teacher") && $objTask->class_id < 1)
			{
				print $objTask->task_name;
			}
			else
			{
				print '<input type="text" name="task" value="' . $objTask->task_name . '" />';
			}
?>
											</span>
											<span class="label points">
												<span class="label title">Points</span>
<?php
			if ($objRoles->isRole("Teacher") && $objTask->class_id < 1)
			{
				print $objTask->points;
			}
			else
			{
				print '<input type="text" name="points" value="' . $objTask->points . '" />';
			}
?>
											</span>
											<span class="label is_checkbox">
												<span class="label title">Lock Grid Points</span>
<?php
			if ($objRoles->isRole("Teacher") && $objTask->class_id < 1)
			{
				print $objTask->is_checkbox ? 'Yes' : 'No';
			}
			else
			{
				print '<input class="is_checkbox" type="checkbox" name="is_checkbox" ' . ($objTask->is_checkbox ? 'checked="true"' : ''). ' />';
			}
?>
											</span>
											<span class="label is_locked">
												<span class="label title">Lock Card Points</span>
<?php
			if ($objRoles->isRole("Teacher") && $objTask->class_id < 1)
			{
				print $objTask->is_locked ? 'Yes' : 'No';
			}
			else
			{
				print '<input class="is_locked" type="checkbox" name="is_locked" ' . ($objTask->is_locked ? 'checked="true"' : ''). ' />';
			}
?>
											</span>
<?php
			if (!$objRoles->isRole("Teacher") || $objTask->class_id > 0)
			{
?>
											<span class="action">
                                                <span class="checklist ">
                                                    <input type="checkbox" id="<?php print $objTask->task_id; ?>" class="checkbox" <?php print $objTask->campaign_id == $this->campaign_id ? "checked " : ""; ?>/>
<?php
				if (!$this->boolInactive)
				{
?>
                                                    <span class="activate">
														<a title="Activate" class="buttonHover checkbox-select">
															<span class="icon activate"></span>
															Activate
														</a>
													</span>
                                                    <span class="deactivate">
														<a title="Deactivate" class="buttonHover checkbox-deselect">
															<span class="icon deactivate"></span>
															Deactivate
														</a>
													</span>
                                                    <span class="edit">
														<a title="Edit">
															<span class="icon"></span>
															Edit
														</a>
													</span>
                                                    <span class="save">
														<a title="Save">
															<span class="icon"></span>
															Save
														</a>
													</span>
                                                    <span class="delete">
														<a title="Delete">
															<span class="icon"></span>
															Delete
														</a>
													</span>
<?php
				}
				else
				{
?>
                                                    <span class="activate reactivate">
														<a title="Reactivate" class="buttonHover">
															<span class="icon activate"></span>
															Reactivate
														</a>
													</span>
<?php
				}
?>
                                                </span>
											</span>
<?php
			}
?>
										</form>
									</li>
<?php
		}
	}
?>
<?php
	if (!$this->boolInactive)
	{
?>
									<!-- ********** ADD NEW TASK ********** -->
									<li>
										<span class="icon add"></span>
										<span class="label"><a href="#" class="add_new_row">Add New Task</a></span>
									</li>
									<li>
										<span class="icon delete"></span>
										<a class="link inactive_tasks" href="#">
											<div class="icon"></div>
											<div class="title"><span class="inactive_num"><?php print count($this->arrCampTasksInactive); ?></span> Inactive Task(s)</div>
										</a>
									</li>
<?php
	}
	else
	{
?>
									<li style="padding-left:26px">
										<a class="link active_tasks" href="#">
											<div class="icon"></div>
											<div class="title"><span class="active_num"><?php print count($this->arrCampTasksInactive); ?></span> Active Task(s)</div>
										</a>
									</li>
<?php
	}
?>

										<div class="sample_row">
											<li class="edit_row">
												<form>

													<span class="action">
														<span class="checklist">
															<input type="checkbox" id="new_row" class="checkbox" checked />
															<span class="activate"><a href="#" title="Add" class="buttonHover checkbox-select"><span class="icon activate"></span>Activate</a></span>
															<span class="deactivate"><a href="#" title="Remove" class="buttonHover checkbox-deselect"><span class="icon deactivate"></span>Deactivate</a></span>
															<span class="edit"><a href="#" title="Edit"><span class="icon"></span>Edit</a></span>
															<span class="save"><a href="#" title="Save"><span class="icon"></span>Save</a></span>
															<span class="delete"><a href="#" title="Delete"><span class="icon"></span>Delete</a></span>
															<span class="progress">Progress</span>
														</span>
													</span>


													<span class="icon bullet">
													</span>

													<span class="label">
														<span class="label title">Task</span>
														<input type="text" name="task" value="Enter Name" />

													</span>

													<span class="label points">
														<span class="label title">Points</span>
														<input type="text" name="points" value="0" />
													</span>
													<span class="label is_checkbox" style="width:90px">
														<span class="label title" style="width:90px">Lock Grid Points</span>
														<input type="checkbox" name="checkbox" class="is_checkbox" value="0" />
													</span>
													<span class="label is_locked" style="width:90px">
														<span class="label title">Lock Card Points</span>
														<input type="checkbox" name="checkbox" class="is_locked" value="0" />
													</span>
												</form>
											</li>


									</div>
									<!-- ********** ADD NEW TASK ********** -->
								</ul>


							</div>

						</div>

					</div>

				</div>

			</div> <!-- <div class="slider"> -->
