<?php 
include "config.phtml";
include "parameters.phtml";	
?>

<div class="slider">
	
	<div class="col_title">
		<span>Images</span>
	</div>
	
	<div class="col_content">
		
		<div id="lists" class="module lists forms">
			
			<div class="module_content">
				
				<ul>
					
<?php if ($this->objRoles->isAllowed('Super Administrator')) : ?>
					<li>
						<a class="link" href="<?php echo $sn; ?>/images/imageshosts">
							<div class="icon"></div>
							<div class="title">View Images by Hosts</div>
						</a>
					</li>
					<li>
						<a class="link" href="<?php echo $sn; ?>/images/imagesnetworks">
							<div class="icon"></div>
							<div class="title">View Images by Networks</div>
						</a>
					</li>
					<li>
						<a class="link" href="<?php echo $sn; ?>/images/imagesinstitutions">
							<div class="icon"></div>
							<div class="title">View Images by Institutions</div>
						</a>
					</li>
					<li>
						<a class="link" href="<?php echo $sn; ?>/images/imageslist">
							<div class="icon"></div>
							<div class="title">View All Images</div>
						</a>
					</li>
					<li>
						<a class="link" href="<?php echo $sn; ?>/images/imagesaddhosts">
							<div class="icon"></div>
							<div class="title">Add New Image</div>
						</a>
					</li>
<?php elseif ($this->objRoles->isAllowed('Host Administrator')) : ?>
					
					<li>
						<a class="link" href="<?php echo $sn; ?>/images/imagesnetworks<?php echo $institution_string; ?>">
							<div class="icon"></div>
							<div class="title">View Images by Networks</div>
						</a>
					</li>
					<li>
						<a class="link" href="<?php echo $sn; ?>/images/imagesinstitutions<?php echo $institution_string; ?>">
							<div class="icon"></div>
							<div class="title">View Images by Institutions</div>
						</a>
					</li>
					<li>
						<a class="link" href="<?php echo $sn; ?>/images/imageslist<?php echo $institution_string; ?>">
							<div class="icon"></div>
							<div class="title">View All Images</div>
						</a>
					</li>
					<li>
						<a class="link" href="<?php echo $sn; ?>/images/imagesaddnetworks<?php echo $institution_string; ?>">
							<div class="icon"></div>
							<div class="title">Add New Image</div>
						</a>
					</li>					
<?php elseif ($this->objRoles->isAllowed('Network Administrator')) : ?>
					<li>
						<a class="link" href="<?php echo $sn; ?>/images/imagesinstitutions<?php echo $institution_string; ?>">
							<div class="icon"></div>
							<div class="title">View Images by Institutions</div>
						</a>
					</li>
					<li>
						<a class="link" href="<?php echo $sn; ?>/images/imageslist<?php echo $institution_string; ?>">
							<div class="icon"></div>
							<div class="title">View All Images</div>
						</a>
					</li>
					<li>
						<a class="link" href="<?php echo $sn; ?>/images/imagesadd<?php echo $institution_string; ?>">
							<div class="icon"></div>
							<div class="title">Add New Image</div>
						</a>
					</li>					
<?php elseif ($this->objRoles->isAllowed('Institution Administrator')) : ?>
					<li>
						<a class="link" href="<?php echo $sn; ?>/images/imageslist<?php echo $institution_string; ?>">
							<div class="icon"></div>
							<div class="title">View All Images</div>
						</a>
					</li>
					<
					<li>
						<a class="link" href="<?php //echo $sn; ?>/images/imagesadd<?php //echo $institution_string; ?>">
							<div class="icon"></div>
							<div class="title">Add New Image</div>
						</a>
					</li>
					
<?php endif; ?>

				</ul>
				
			</div>
			
		</div>
		
	</div>
	
</div>