<?php include "config.phtml"; ?>
<div class="slider">
	<div class="col_title">
			<span>Users</span>
	</div>
	<div class="col_content">
		
		<div id="lists" class="module lists forms">
			<div class="module_content">
				<ul>
					<li>
						<a class="link" href="<?php echo $sn; ?>/administration/userslist/status/active">
							<div class="icon"></div>
							<div class="title">Active users</div>
						</a>
					</li>
					<li>
						<a class="link" href="<?php echo $sn; ?>/administration/userslist/status/inactive">
							<div class="icon"></div>
							<div class="title">Inactive users</div>
						</a>
					</li>
				</ul>
			</div>
		</div>
		
	</div>
</div>