<?php
	include "config.phtml";
	include "parameters.phtml";
?>

<div class="slider" id="ranksprintinstititutions">	
	<div class="col_title">
		<span>Print Rank Cards Institutions</span>
	</div>	
	<div class="col_content">
<?php
	if (count($this->objInstitutions) == 0)
	{
?>
		<div class="module" style="padding:5px;">
			There are no Institutions available to display.
		</div>
<?php
	}
	else
	{
?>
        <div id="lists" class="module lists forms">				
            <div class="module_content">					
                <form name="ranksprintinstititutions" id="ranksprintinstititutions" method="post" action="">
                    <ul>
<?php
		foreach ($this->objInstitutions as $objInstitution)
		{
?>
                        <li>
                            <a class="link" href="<?php echo $sn . "/ranks/ranksprintclasses/institution_id/" . $objInstitution->institution_id . $strParamPath; ?>">
                                <div class="icon"></div>
                                <div class="title"><?php echo $objInstitution->name; ?></div>
                            </a>
                        </li>
<?php
		}
?>
                    </ul>
                </form>
            </div>
        </div>		
<?php
	}
?>
    </div>
</div>