<?php
	include "config.phtml";
	include "parameters.phtml";
	$objUserSession = new Zend_Session_Namespace("user_session_data");
?>
<script language="text/javascript">
$(document).ready(function() {
	$(this).delay(1).queue(function () {
		$(this).dequeue();
		$('.slider:last input:[type="checkbox"]').iphoneStyle({});
		$(".slider:last input.datepicker").datepicker();
	});
	$("#taskedit .cb-enable").click(function(){
		var parent = $(this).closest('.switch');
		$('.cb-disable',parent).removeClass('selected');
		$(this).addClass('selected');
		$('.checkbox',parent).attr('checked', true);
	});
	$("#taskedit .cb-disable").click(function(){
		var parent = $(this).closest('.switch');
		$('.cb-enable',parent).removeClass('selected');
		$(this).addClass('selected');
		$('.checkbox',parent).attr('checked', false);
	});
	$("#taskedit .switch input:checked").closest('label').addClass("selected");
 	$("#taskedit .save").bind('click', function () {
		$('#taskmanager3').attr('do_refresh', 'true');
		$.ajax({
			type : "POST",
			cache : false,
			url : '<?php echo $sn . "/incrementals/taskedit/task_save/true" . $strParamPath; ?>',
			dataType : "text",
			data: $(this).closest("form").serialize(),
			success : function(strResponse) {
				//alert(strResponse);
				try {
					var arrResponse = jQuery.parseJSON(strResponse);
				} catch(e) {
					$(this).closest(".module_content").find(".processing_status").html('Sorry, there was an error: VU-IDC101-SDF8DS');
					$.alert(strResponse);
					return;
				}
				if (typeof(arrResponse) != "object") {
					$(this).closest(".module_content").find(".processing_status").html('Sorry, there was an error: VU-IDC102-S9D9DD');
					$.alert();
					return;
				} else {
					if (arrResponse["error"]) {
						if (typeof(arrResponse["error"]) != "object") {
							$(".slider:last #processing_status").html(arrResponse["error"]).fadeIn("fast");
						} else {
							for (var strField in arrResponse["error"])
							{
								//alert($.dump($(".slider:last #" + strField).closest("li").html()));return;
								$(".slider:last #" + strField).closest("li").next().html(arrResponse["error"][strField]).fadeIn();
							}
						}
					} else if (arrResponse["success"] == "true") {
						if (arrResponse["success"] == "true")
						{
							if (arrResponse["intTask"])
							{
								slideRefresh('<?php print $sn . '/incrementals/taskedit/task_id/'; ?>' + arrResponse["intTask"]);
							}
							//$(this).closest(".module_content").find(".processing_status").fadeOut();
							$(".slider:last #processing_status").html("Saved").fadeIn("fast").delay(2000).fadeOut("slow");
						}

					} else {
						alert("Sorry, there was an error: VI-J103-99DS0S");
						$.alert(strResponse);
					}
				}
			}
		});
	});
});
</script>
<div class="slider" id="taskedit">
	<style type="text/css">
		#taskedit #processing_status {
			padding:4px 10px;
		}
		.cb-enable, .cb-disable, .cb-enable span, .cb-disable span { background: url(<?php print $sn; ?>/images/back-end/admin/switch2.gif) repeat-x; display: block; float: left; }
		.cb-enable span, .cb-disable span { line-height: 30px; display: block; background-repeat: no-repeat; }
		.cb-enable span { background-position: left -90px; padding: 0 10px; }
		.cb-disable span { background-position: right -180px;padding: 0 10px; }
		.cb-disable.selected { background-position: 0 -30px;  }
		.cb-disable.selected span { background-position: right -210px; color: #fff; }
		.cb-enable.selected { background-position: 0 -60px; }
		.cb-enable.selected span { background-position: left -150px; color: #fff; }

		.cb-enable, .cb-disable { font-family: Arial, Sans-serif; font-weight: bold; text-shadow: none; }
		.field { width: 100%; float: left;  }
		.switch input { display: none; }
		.switch label { cursor: pointer; }
	</style>
	<div class="col_title"><span><?php print text("Task Editor"); ?></span></div>
	<div class="col_content camper">
		<form>
			<h2 style="margin-top:-2px"><span style="font-weight:normal;">Campaign</span>&nbsp;&nbsp;<?php print $this->objCampaign->campaign_name; ?></h2>
			<div class="module form lists">
				<div class="module_content list">
					<ul>
<?php
	if (@$this->objTask->start_date == "0000-00-00")
		$this->objTask->start_date = '';
	if (@$this->objTask->end_date == "0000-00-00")
		$this->objTask->end_date = '';
	if (preg_match('/^([0-9]{4})-([0-9]{2})-([0-9]{2})$/', @$this->objTask->start_date, $arrDateMatch))
	{
		list($strSource, $intYear, $intMonth, $intDay) = $arrDateMatch;
		$this->objTask->start_date = $intMonth . '/' . $intDay . '/' . $intYear;
	}
	if (preg_match('/^([0-9]{4})-([0-9]{2})-([0-9]{2})$/', @$this->objTask->end_date, $arrDateMatch))
	{
		list($strSource, $intYear, $intMonth, $intDay) = $arrDateMatch;
		$this->objTask->end_date = $intMonth . '/' . $intDay . '/' . $intYear;
	}
?>
						<li style="display: list-item;">
							<h3><?php print $this->objTask ? 'Edit Task Details' : 'New Task'; ?></h3>
						</li>
<?php
	if(0 && $this->objRoles->isAllowed('Super Administrator'))
	{
?>
						<li id="checklist_schooltypes">
							<input type="hidden" name="school_types" value="<?php print $this->strTaskSchoolTypes; ?>" />
							<a class="link" href="<?php print $sn . "/checklist/schooltypes" . $strParamPath; ?>">
								<div class="icon"></div>
								<div class="title"><?php print text('[|School|] Types'); ?> (<?php
		if (
			count($this->arrPrizeSchoolTypes) == count($arrTemplateTypes)
			|| count($this->arrPrizeSchoolTypes) == 0
		) {
			print "All";
		}
		else
		{
			print count($this->arrPrizeSchoolTypes);
		}
?>)</div>
							</a>
						</li>
<?php
	}
?>
						<li>
							<span class="label"><?php print text("Task Name"); ?>: *</span>
							<span class="input"><input type="text" class="required" name="task_name" value="<?php echo @$this->objTask->task_name; ?>" minlength="2" /></span>
							<div class="clear"></div>
						</li>
						<div class="processing_status"></div>
						<li>
							<span class="label"><?php print text("[|Points|]"); ?>:</span>
							<span class="input"><input style="width:140px" type="text" class="required" name="points" value="<?php echo @$this->objTask->points; ?>" minlength="2" /></span>
							<div class="help info" title="<?php print text("Info"); ?>"></div>
						</li>
						<div class="processing_status"></div>
						<li>
							<span class="label"><?php print text("Min. [|Points|]"); ?>:</span>
							<span class="input"><input style="width:140px" type="text" class="required" name="min_points" value="<?php echo !empty($this->objTask->min_points) ? $this->objTask->min_points : 0; ?>" minlength="2" /></span>
							<div class="help info" title="<?php print text("Info"); ?>"></div>
						</li>
						<div class="processing_status"></div>
						<li>
							<span class="label"><?php print text("Max. [|Points|]"); ?>:</span>
							<span class="input"><input style="width:140px" type="text" class="required" name="max_points" value="<?php echo !empty($this->objTask->max_points) ? $this->objTask->max_points : 0; ?>" minlength="2" /></span>
							<div class="help info" title="<?php print text("Info"); ?>"></div>
						</li>
						<div class="processing_status"></div>
						<li>
							<span class="label"><?php print text("Start Date"); ?>:</span>
							<span class="input"><input placeholder="mm/dd/yyyy" style="width:140px" type="text" class="required datepicker" name="start_date" value="<?php echo @$this->objTask->start_date; ?>" /></span>
							<div class="help info" title="<?php print text("Info"); ?>"></div>
						</li>
						<div class="processing_status"></div>
						<li>
							<span class="label"><?php print text("End Date"); ?>:</span>
							<span class="input"><input placeholder="mm/dd/yyyy" style="width:140px" type="text" class="required datepicker" name="end_date" value="<?php echo @$this->objTask->end_date; ?>" /></span>
							<div class="help info" title="<?php print text("Info"); ?>"></div>
						</li>
						<div class="processing_status"></div>
						<li>
							<span class="label"><?php print text("Grid [|Points|]"); ?>:</span>
							<span class="input"><div style="margin-top:3px"><input type="checkbox" <?php echo !@$this->objTask || @$this->objTask->is_grid ? 'checked="checked"' : ''; ?> class="required" name="is_grid" value="1" minlength="2" /></div></span>
							<div class="help info" title="<?php print text("Info"); ?>"></div>
						</li>
						<div class="processing_status"></div>
						<li>
							<span class="label"><?php print text("Grid [|Points|] Locked"); ?>:</span>
							<span class="input"><div style="margin-top:3px"><input type="checkbox" <?php echo @$this->objTask->is_checkbox ? 'checked="checked"' : ''; ?> class="required" name="is_checkbox" value="1" minlength="2" /></div></span>
							<div class="help info" title="<?php print text("Info"); ?>"></div>
						</li>
						<div class="processing_status"></div>
						<li>
							<span class="label"><?php print text("Card [|Points|]"); ?>:</span>
							<span class="input"><div style="margin-top:3px"><input type="checkbox" <?php echo !@$this->objTask || @$this->objTask->is_card ? 'checked="checked"' : ''; ?> class="required" name="is_card" value="1" minlength="2" /></div></span>
							<div class="help info" title="<?php print text("Info"); ?>"></div>
						</li>
						<div class="processing_status"></div>
						<li>
							<span class="label"><?php print text("Card [|Points|] Locked"); ?>:</span>
							<span class="input"><div style="margin-top:3px"><input type="checkbox" <?php echo @$this->objTask->is_locked ? 'checked="checked"' : ''; ?> class="required" name="is_locked" value="1" minlength="2" /></div></span>
							<div class="help info" title="<?php print text("Info"); ?>"></div>
						</li>
						<div class="processing_status"></div>
						<li>
							<span class="label" style="padding:12px 0 0 0;">Task Status:</span>
							<span class="input field switch" style="padding:6px 0 9px 0;">
								<label for="radio1" class="cb-enable"><span>Activated</span><input type="radio" id="radio1" value="1" name="is_active" <?php print !$this->objTask || $this->objTask->is_active ? "checked='checked'" : ''; ?> /></label>
								<label for="radio2" class="cb-disable"><span>Deactivated</span><input type="radio" id="radio2" value="0" name="is_active" <?php print @$this->objTask->is_active == "0" ? "checked='checked'" : ''; ?> /></label>
							</span>
							<div class="clear"></div>
						</li>
						<div id="processing_status"></div>
						<li style="padding:8px">
							<span><a class="button submit save"><?php print text("Save"); ?></a></span>
							<div class="clear"></div>
						</li>
					</ul>
				</div>
			</div>
		</form>
	</div>
</div>