<?php
	include "config.phtml";
	$user_session_data = new Zend_Session_Namespace('user_session_data');
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
   "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<META HTTP-EQUIV="PRAGMA" CONTENT="NO-CACHE">
<title>Mashpia.com</title>

<link rel="stylesheet" type="text/css"	href="<?php echo $sn; ?>/css/back-end/admin/reset.css" />
<link rel="stylesheet" type="text/css"	href="<?php echo $sn; ?>/css/back-end/admin/styles.css" />
<link rel="stylesheet" type="text/css"	href="<?php echo $sn; ?>/css/back-end/admin/print.css" media="print" />
<link rel="stylesheet" type="text/css"	href="<?php echo $sn; ?>/css/back-end/admin/theme.css" />
<link rel="stylesheet" type="text/css"	href="<?php echo $sn; ?>/css/back-end/uploader.css" />
<script type="text/javascript" src="<?php echo $sn; ?>/js/back-end/admin/jquery3.js"></script>
<script type="text/javascript" src="<?php echo $sn; ?>/js/back-end/admin/jquery-ui2.js"></script>
<script type="text/javascript" src="<?php echo $sn; ?>/js/back-end/admin/jquery.tools.js"></script>
<script type="text/javascript" src="<?php echo $sn; ?>/js/back-end/admin/jquery.editableText.js"></script>
<script type="text/javascript" src="<?php echo $sn; ?>/js/back-end/admin/jquery.blockui.js"></script>
<!--script type="text/javascript" src="<?php echo $sn; ?>/js/back-end/admin/jquery.validate.js"></script-->
<script type="text/javascript" src="<?php echo $sn; ?>/js/back-end/admin/jquery.form.js"></script>
<!--script type="text/javascript" src="<?php echo $sn; ?>/js/back-end/admin/jquery.color.min.js"></script-->
<script type="text/javascript" src="<?php echo $sn; ?>/js/back-end/admin/jquery.styleselect.js"></script>
<script type="text/javascript" src="<?php echo $sn; ?>/js/back-end/admin/jquery.jeditable.min.js"></script>
<script type="text/javascript" src="<?php echo $sn; ?>/js/back-end/admin/jquery.dump.js"></script>
<script type="text/javascript" src="<?php echo $sn; ?>/js/back-end/admin/jquery.maskedinput.js"></script>
<script type="text/javascript" src="<?php echo $sn; ?>/js/back-end/admin/jquery.nodesearch.js"></script>
<script type="text/javascript" src="<?php print $sn . '/js/back-end/admin/ckeditor/ckeditor.js'; ?>"></script>
<script type="text/javascript" src="<?php print $sn . '/js/back-end/admin/ckeditor/styles.js'; ?>"></script>
<script type="text/javascript" src="<?php echo $sn; ?>/js/back-end/admin/jquery.iphone-style-checkbox.js"></script>
<link rel="stylesheet" type="text/css"	href="<?php echo $sn; ?>/css/back-end/admin/jquery.iphone-style-checkbox.css" />

<script type="text/javascript" src="<?php echo $sn; ?>/js/back-end/admin/scripts.js"></script>

<script src="<?php echo $sn; ?>/js/back-end/uploader/swfupload.js" type="text/javascript"></script>
<script src="<?php echo $sn; ?>/js/back-end/uploader/swfupload.queue.js" type="text/javascript"></script>
<script src="<?php echo $sn; ?>/js/back-end/uploader/fileprogress.js" type="text/javascript"></script>
<script src="<?php echo $sn; ?>/js/back-end/uploader/handlers.js" type="text/javascript"></script>

<!--script src="<?php echo $sn; ?>/js/back-end/admin/fullcal/_loader.js" type="text/javascript"></script-->

<script type="text/javascript" src="<?php echo $sn; ?>/js/back-end/admin/jquery.toChecklist.min.js"></script>
<link type="text/css" rel="stylesheet" href="<?php echo $sn; ?>/css/back-end/admin/jquery.toChecklist.min.css">
<!-- ins: <?php print $user_session_data->institution_id; ?> u: <?php print $user_session_data->user_id; ?> -->

<script src="<?php print WEB_ROOT; ?>/js/back-end/admin/jquery.handsontable.full.js" type="text/javascript"></script>
<link href="<?php print WEB_ROOT; ?>/css/back-end/admin/jquery.handsontable.full.css" rel="stylesheet" type="text/css" />