<?php //include "config.phtml"; ?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <title>Mashpia.com</title>

        <link rel="stylesheet" type="text/css" href="<?php echo $sn; ?>/css/back-end/kiosk/styles_reset.css">
        <link rel="stylesheet" type="text/css" href="<?php echo $sn; ?>/css/back-end/kiosk/styles_kiosk.css">
        <link rel="stylesheet" type="text/css" href="<?php echo $sn; ?>/css/back-end/kiosk/reset.css">
        <link rel="stylesheet" type="text/css" href="<?php echo $sn; ?>/css/back-end/kiosk/style.css">

        <script type="text/javascript" src="<?php echo $sn; ?>/js/back-end/kiosk/jquery.js"></script>
        <script type="text/javascript" src="<?php echo $sn; ?>/js/back-end/kiosk/jquery-ui.js"></script>
        <script type="text/javascript" src="<?php echo $sn; ?>/js/back-end/kiosk/jquery.tools.js"></script>
        <script type="text/javascript" src="<?php echo $sn; ?>/js/back-end/kiosk/mashpia.js"></script>
        <script type="text/javascript" src="<?php echo $sn; ?>/js/back-end/kiosk/jquery.validate.js"></script>
        <script type="text/javascript" src="<?php echo $sn; ?>/js/back-end/kiosk/easySlider1.7.js"></script>
        <!-- script type="text/javascript" src="<?php echo $sn; ?>/js/back-end/kiosk/jScrollPane.js"></script-->

        <script type="text/javascript" src="<?php echo $sn; ?>/js/back-end/kiosk/jquery.scroll.js"></script>
        <link rel="stylesheet" type="text/css" href="<?php echo $sn; ?>/css/back-end/kiosk/jquery.scroll.css">

        <script type="text/javascript" src="<?php echo $sn; ?>/js/back-end/kiosk/jquery.checkbox.js"></script>
        <link rel="stylesheet" type="text/css" href="<?php echo $sn; ?>/css/back-end/kiosk/jquery.checkbox.css" >

        <script type="text/javascript" src="<?php echo $sn; ?>/js/back-end/kiosk/jquery.keypad.js"></script>
        <link rel="stylesheet" type="text/css" href="<?php echo $sn; ?>/css/back-end/kiosk/jquery.keypad.css">
