<?php
	include "config.phtml";
	include "parameters.phtml";
	$objRoles = new Roles();
	global $arrTemplateTypes;
?>
<style>
.processing_status {
	display: none;
	padding: 4px 0 8px 8px;
	color: red;
	width: 500px;
}
#processing_status {
	display: none;
	padding: 4px 0 8px 8px;
	width: 500px;
	color: #000;
}
.box_activation {
	padding: 6px;
	display: inline;
	cursor: pointer;
}
</style>
<script language="javascript">
	$(document).ready(function()
	{
		$(this).delay(1).queue(function () {
			$(this).dequeue();
			$('.slider:last input[type=checkbox]').iphoneStyle({});
		});
		$('.slider:last .box_activation').click(function () {
			var boolActive = $(this).find("input").val() == "1";
			$('.slider:last .box_activation input').attr('checked', false);
			$('.slider:last .box_activation').css({
				"border": "1px solid black",
				"color": "black"
			});
			$(this).find("input").attr('checked', true);
			$(this).css({
				"border": "1px solid " + (boolActive ? "green" : "red"),
				"color": boolActive ? "green" : "red"
			});
		});
		$('.slider:last .box_activation input[checked=true]').trigger("click");
		$('.slider:last .copy_to_camp').click(function (e) {
			e.preventDefault();
			if (confirm("Are you sure you would like to copy this campaign to your camp account?")) {
				$.ajax({
					type : "POST",
					cache : false,
					start: $(".slider_storeprint #processing_status").html('Loading...').fadeIn("slow"),
					url : '<?php print $sn . "/campaigns/copycampaigntocamp/campaign_id/" . $this->intCampaign; ?>',
					dataType : "text",
					data: $('.slider_storeprint form').serialize(),
					success : function(strResponse) {
						var arrResponse = {};
						try {
							arrResponse = JSON.parse(strResponse);
						} catch(e) {
							$.alert("JSON parsing issue");
							$.alert(strResponse);
							$(".slider_storeprint #processing_status").html('Sorry, there was an error: VU-E102-sakj22');
							return;
						}
						if (arrResponse.failure) {
							if (arrResponse.failure == "true")
								alert("There was an unknown error: VS-P101-d1j32j");
							else
								alert(arrResponse.failure);
						} else {
							alert("Campaign copied");
						}
						$(".slider_storeprint #processing_status").fadeOut();
					}
				});
			}
		});
		$('.slider:last form a.submit').click( function(e) {
			$(".slider:last .processing_status").fadeOut();
			$.ajax({
				type : "POST",
				cache : false,
				start: $(".slider:last #processing_status").html('Loading...').fadeIn(),
				url : '<?php echo $sn . "/campaigns/campaignedit" . $strParamPath; ?>',
				dataType : "text",
				data: $('.slider:last form').serialize(),
				success : function(strResponse) {
					try {
						var arrResponse = jQuery.parseJSON(strResponse);
					} catch(e) {
						$(".slider:last #processing_status").html('Sorry, there was an error: VU-E101-3RR3RE');
						alert("Sorry, there was an error: VA-J101-3RR3RE");
						alert(strResponse);
						return;
					}
					if (typeof(arrResponse) != "object") {
						$(".slider:last #processing_status").html('Sorry, there was an error: VU-E102-SDF8BX');
						alert("Sorry, there was an error: VA-J102-SDF8BX");
						return;
					} else {
						$(".slider:last #processing_status").fadeOut();
						if (arrResponse["error"]) {
							if (typeof(arrResponse["error"]) != "object") {
								$(".slider:last #processing_status").html(arrResponse["error"]);
							} else {
								for (strField in arrResponse["error"])
								{
									//alert($.dump($(".slider:last #" + strField).closest("li").html()));return;
									$(".slider:last #" + strField).closest("li").next().html(arrResponse["error"][strField]).fadeIn();
								}
							}
						} else if (arrResponse["success"] == "true") {
							$(".slider:last #processing_status").html("Save successful.").fadeIn("slow").delay(2000).fadeOut("slow");
						} else {
							$(".slider:last #processing_status").html("Sorry, there was an error: VA-J103-DS7DDS").fadeIn("slow");
							//alert($.dump(arrResponse));
						}
					}
				}
			});
		});
	});
</script>

<div class="slider">
	<div class="col_title">
		<span>Edit Campaign</span>
	</div>

	<div class="col_content camper">
		<div id="lists" class="module lists forms">
			<div class="module_content">
				<ul>
					<li style="font-size:10pt;padding:6px;">
						Add / Edit the campaign logo which is viewed from the transaction manager once a student has been awarded a task.
					</li>
				</ul>
			</div>
		</div>
		<div class="module form lists" id="module-info">
			<div class="module_content list">
				<form>
					<ul>
						<?php include('uimods/uploadmessage.phtml'); ?>
						<li>
							<h3>Campaign Image</h3>
							<input type="hidden" name="image_id" id="usereditor_image_id" value="<?php print @$this->objCampaign->image_id; ?>" />
							<iframe src="<?php print $sn . "/imgs/smalluploader/current_image/" . @$this->objCampaign->image_id; ?>/resultid/usereditor_image_id" width="100%" height="80" scrolling="no">
								<p>Your browser does not support iframes.</p>
							</iframe>
						</li>
<?php
	if ($objRoles->isRole("Super Administrator"))
	{
?>
						<li id="checklist_schooltypes">
							<input type="hidden" name="school_types" value="<?php print $this->strCampaignSchoolTypes; ?>" />
							<a class="link" href="<?php print $sn . "/checklist/schooltypes" . $strParamPath; ?>">
								<div class="icon"></div>
								<div class="title">School Types (<?php
		if (
			count($this->arrCampaignSchoolTypes) == count($arrTemplateTypes)
			|| count($this->arrCampaignSchoolTypes) == 0
		) {
			print "All";
		}
		else
		{
			print count($this->arrCampaignSchoolTypes);
		}
?>)</div>
							</a>
						</li>
<?php
	}
?>
						<!--li>
							<span class="label">Campaign Type:</span>
							<span class="input" style="padding: 8px 7px 0px 2px"><?php echo $this->objCampaign->campaign_type; ?></span>
							<div class="clear"></div>
						</li-->
						<div class="processing_status"></div>
						<li>
							<span class="label">&nbsp;<br/>Campaign Name:</span>
							<span class="input"><span style="color:gray">There is a limit of 18 characters for the campaign name.</span><br/><input type="text" class="required" id="campaign_name" name="campaign_name" value="<?php echo $this->objCampaign->campaign_name; ?>" size="25" minlength="2" /></span>
							<div class="clear"></div>
						</li>
						<div class="processing_status"></div>
						<!--li>
							<span class="label">Goal:</span>
							<span class="input"><textarea rows="3" cols="35" name="description" id="description"><?php echo $this->objCampaign->description; ?></textarea></span>
						</li-->
						<div class="processing_status"></div>
<?php
	if ($objRoles->isAllowed("Super Administrator"))
	{
?>
						<li>
							<span class="label">Default installed:</span>
							<span class="input"><input type="checkbox" id="default_installed" name="default_installed" value="1"<?php print (isset($this->objCampaign) && $this->objCampaign->default_installed) ? " checked" : ""; ?> /></span>
							<div class="clear"></div>
						</li>
<?php
	}
?>
						<div class="processing_status"></div>
						<!--li>
							<span class="label">Points:</span>
							<span class="input"><input type="checkbox" class="required" id="points" name="points" value="1" <?php echo $this->objCampaign->points ? " checked" : " " ; ?> /></span>
							<div class="clear"></div>
						</li>
						<div class="processing_status"></div-->
						<li>
							<span class="label" style="padding:12px 0 9px 0;">Campaign Status:</span>
							<span class="input" style="padding:8px 0 0 0;">
								<div class="box_activation"><input <?php if (!isset($this->objCampaign) || $this->objCampaign->is_active == "1") print "checked='true' ";?>type="radio" name="is_active" value="1" /> Activated</div>
								<div class="box_activation"><input <?php if (isset($this->objCampaign) && $this->objCampaign->is_active != "1") print "checked='true' ";?>type="radio" name="is_active" value="0" /> Deactivated</div>
							</span>
							<div class="clear"></div>
						</li>
						<div class="processing_status"></div>
						<li>
							<span>
								<a href="#" title="Save" class="button submit">Save</a>
<?php
	if ($this->tstyle == "chabadhebrewschool") {
?>
								<a style="float:right;" href="#" title="Copy to Camp" class="button copy_to_camp">Copy to Camp</a>
<?php
	}
?>
							</span>
							<div class="clear"></div>
						</li>
						<div id="processing_status"></div>
					</ul>
				</form>
			</div>
		</div>
	</div>
</div>




<?php
/*
 * Saved links
					<li>
						<a class="link" href="<?php print $sn . "/campaigns/velocities" . $strParamPath; ?>">
							<div class="icon"></div>
							<div class="title">Edit Velocities</div>
						</a>
					</li>
					<li>
						<a class="link" href="<?php print $sn . "/campaigns/campaignrules" . $strParamPath; ?>">
							<div class="icon"></div>
							<div class="title">Edit Rules</div>
						</a>
					</li>
					<li>
						<a class="link" href="<?php print $sn . "/medals/medaleditor" . $strParamPath; ?>">
							<div class="icon"></div>
							<div class="title">Add / Edit Medals</div>
						</a>
					</li>



						<li>
							<span class="label">Class Limitation:</span>
							<span class="input"><input type="hidden" name="image_id" id="usereditor_image_id" value="<?php print intval(@$this->objUser->image_id); ?>" />
							<iframe src="<?php print $sn . '/menu/classes/viewmod/multiselect' . $strParamPath; ?>" width="100%" height="60" scrolling="no">
								<p>Your browser does not support iframes.</p>
							</iframe></span>
							<div class="clear"></div>
						</li>
						<div class="processing_status"></div>


 *
 */
?>