<?php 
	include "config.phtml";
	include "parameters.phtml";
?>
<div class="slider" id="slider_missionedit">
	<div class="col_title">
		<span>Mission Rules</span>
	</div>
	<div class="col_content camper">
		<div class="module lists" id="lists-camper-groups">
			<div class="module_content">
				<ul>
					<li>
						<a class="link" href="<?php print $sn . "/scheduler/calendar" . $strParamPath; ?>">
							<div class="icon"></div>
							<div class="title">View Calendar</div>
						</a>
					</li>
				</ul>
			</div>
		</div>
	</div>
</div>