<?php 
	include "config.phtml";
	include "parameters.phtml";
?>
<script>
$(document).ready(function()
{
	$('#book_id').toChecklist({
		showCheckboxes : true,
		addScrollBar : false,
		maxNumOfSelections : 1,
		onMaxNumExceeded : function() {
			$("#slider_missionbooks #status_message").html("You can only select one book at a time.").fadeIn();
		}
	});
	$('#slider_missionbooks form a.submit').click( function(e) {
		e.preventDefault();
		$.ajax({
			type : "POST",
			cache : false,
			start: $("#slider_missionbooks #status_message").html('Loading...').fadeIn("slow"),
			url : '<?php echo $sn . "/campaigns/missionbooks" . $strParamPath ?>',
			dataType : "text",
			data: $('#slider_missionbooks form').serialize(),
			success : function(strResponse) {
				if (strResponse == "1") {
					$("#slider_missionbooks #status_message").html("Save successful.").fadeIn("slow").delay(2000).fadeOut("slow");
				} else if (strResponse == "0") {
					$("#slider_missionbooks #status_message").html("There wasn't any changes.").fadeIn("slow").delay(2000).fadeOut("slow");
				} else {
					$("#slider_missionbooks #status_message").html(strResponse).fadeIn("slow");
				}
			}
		});
	});
});
</script>
<div class="slider" id="slider_missionbooks">
	<div class="col_title">
		<span>Mission Books</span>
	</div>
	<div class="col_content camper">
		<form>
			<div class="module form" id="module-info" style="padding:3px">
				Select a book to be associated with the currently selected mission.
			</div>
			<select name="book_id" id="book_id" multiple="multiple" style="width:300px">
<?php
	foreach ($this->arrBooks as $objBook)
	{
		print "<option" . ($this->objMission->book_id == $objBook->book_id ? " selected" : "") . " value=\"" . $objBook->book_id . "\">" . $objBook->book_name . "</option>";
	}
?>
			</select>
			<div id="status_message"></div>&nbsp;
			<div class="module_content list">
				<ul>
					<li>
						<span><a href="#" title="Save" class="button submit">Save</a></span>							
						<div class="clear"></div>							
					</li>
				</ul>
			</div>
		</form>
	</div>
</div>