<?php
	include "config.phtml";
	include "parameters.phtml";
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Print Achievement Cards</title>
		<script type="text/javascript" src="<?php print $sn; ?>/js/back-end/admin/jquery3.js"></script>
		<script type="text/javascript" src="<?php print $sn; ?>/js/back-end/admin/jquery.dump.js"></script>
        <style type="text/css">
		.cards {
			width:672px;
			min-height: 800px;
			page-break-after:always;
			font-family:'Myriad Pro',Arial,sans-serif;
			margin:-0.1875in auto 0;
		}
		.cards .row {
			display:table;
			margin:-0.1875in auto 0;
			margin-bottom: 8px;
		}
		.cards .card {
			width:3.5in;
			height:2in;
			text-align:center;

			width:306px;
			height:162px;
			padding:10px 15px 10px 15px;
			display:table-cell;
		}
		.cards .card .container {
			border:2px solid #000;
			border-radius:10px;
			-moz-border-radius:10px;
			height:100%;
		}

		.cards .logo {
			float:left;
			margin-left:30px;
		}
		.cards .institution {
			float:right;
			margin-right:30px;
		}
		.cards .logo img, .cards .institution img {
			margin:5px 0;
			width:55px;
			height:55px;
		}
		.cards .clear {
			clear:both;
		}

		.cards .title img {
			width:250px;
			height:34px;
		}

		.cards .campaign {
			/*clear:both;*/
			font-weight:bold;
			/*position:absolute;*/
			width:302px;
		}

		.cards .name {
			font-size:12px;
			margin:6px 0;
			height:15px;
			/*font-weight:bold;*/
		}

		.cards .barcode {
			font-size:9px;
		}

		.cards .points {
			font-size:12px;
			width:50px;
			font-weight:bold;
			border:2px solid #000000;
			border-radius:7px;
			-moz-border-radius:7px;
			padding:3px;
			margin:-55px auto 10px;
		}
        </style>
    </head>
    <body>
<?php
	$intColsNum = 2;
	for ($intSet=0; $intSet<$this->arrDataParams['intSetCount']; $intSet++)
	{
		//$intItr++;
		$arrTasks = $this->arrTasks;
		do { // pages
?>
		<div class="cards achievement">
<?php
			$arrTasksBuffer = $arrTasks;
			$arrTasks = array_splice($arrTasksBuffer, 10);
			for ($intRow=0; $intRow<5; $intRow++)
			{
?>
			<div class="row">
<?php
				for ($intColumn=0; $intColumn<$intColsNum; $intColumn++)
				{
					if (!isset($arrTasksBuffer[($intRow*2)+$intColumn]))
						continue;
					$objTask = $arrTasksBuffer[($intRow*2)+$intColumn];
?>
				<div class="card">
					<div class="container">
						<div class="logo"><img src="<?php print $sn; ?>/imgs/v/w/55/src/<?php print $this->arrCampaigns[$objTask->campaign_id]->image_id ? $this->arrCampaigns[$objTask->campaign_id]->image_id : $this->objInstitution->image_id; ?>" /></div>
						<div class="institution"><img src="<?php print $sn; ?>/imgs/v/w/55/src/<?php print $this->objInstitution->image_id; ?>" /></div>
						<div class="clear"></div>
						<div class="points"><nobr><?php print $objTask->points; ?> point</nobr></div>
						<div class="campaign"><nobr><?php print $this->arrCampaigns[$objTask->campaign_id]->campaign_name; ?></nobr></div>
						<div class="title"><img src="/images/Achievement_Card.png" /></div>
						<div class="name"><?php print $objTask->task_name; ?></div>
						<div class="barcode"><img src="<?php print $sn; ?>/kiosk/get-barcode-legacy/serial/<?php print $this->arrBarcodes[$intSet][$objTask->task_id]; ?>" width="210" height="20" /><br/><?php print $this->arrBarcodes[$intSet][$objTask->task_id]; ?></div>
					</div>
				</div>
<?php
				}
?>
			</div>
<?php
			}
?>
		</div>
<?php
		} while (count($arrTasks));
		if ($intSet+1<$this->arrDataParams['intSetCount']&&$this->arrDataParams['intSetCount']>1)
		{
?>
		<div class="cards achievement">
			<div class="row"></div>
		</div>
<?php
		}
	}
?>
		<script>
			$('.cards .row').css({
				'margin-bottom' : '<?php print $this->arrDataParams['intRowMargin']; ?>'
			});
			$('.cards').css({
				'margin-top' : '<?php print $this->arrDataParams['intTopMargin']; ?>'
			});
		</script>
	</body>
</html>