<ul class="list_first">
	<li class="list_parent current">
		<a href="#">

				<img src="<?php echo $sn; ?>/images/back-end/admin/icon_school.png" width="28" height="28" alt="Home" />
			Register</a>
	</li>
	<li class="list_parent">
		<a href="#" onclick="window.location.href='<?php echo $sn; ?>/index/index<?php print $strParamPath; ?>';">

				<img src="<?php echo $sn; ?>/images/back-end/admin/icon_door_in.png" width="28" height="28" alt="Back" />
			Login</a>
	</li>
</ul>