<html>
	<head>
		<style>
body {
	margin:50px 0px; padding:0px;
	text-align:center;
}
	
div {
	width:500px;
	height:450px;
	margin:0px auto;
	text-align:left;
	padding:15px;
	border:1px dashed #333;
	background-color:#eee;
}
</style>
	</head>
	<body>
		<div id="container">
			<table width="100%" height="100%" border="2" cellspacing="0" cellpadding="3">
			<tr valign="top"><td><font size="3" face="Calibri">Suggested Grades</font></td>
			
			  <td><font size="3" face="Calibri">Quota</font></td>
			  <td><font size="3" face="Calibri">Lines per year</font></td></tr>
			<tr valign="top"><td><font size="3" face="Calibri">Pre 1A</font></td>
			  <td><font size="3" face="Calibri">0.25</font></td>
			  <td><font size="3" face="Calibri">12</font></td></tr>
			<tr valign="top"><td><font size="3" face="Calibri">1<sup>st</sup> Grade</font></td>
			
			  <td><font size="3" face="Calibri">0.5</font></td>
			  <td><font size="3" face="Calibri">24</font></td></tr>
			<tr valign="top"><td><font size="3" face="Calibri">2<sup>nd</sup> Grade</font></td>
			  <td><font size="3" face="Calibri">0.75</font></td>
			  <td><font size="3" face="Calibri">36</font></td></tr>
			
			<tr valign="top"><td><font size="3" face="Calibri">3<sup>rd</sup> Grade</font></td>
			  <td><font size="3" face="Calibri">1</font></td>
			  <td><font size="3" face="Calibri">48</font></td></tr>
			<tr valign="top"><td><font size="3" face="Calibri">4<sup>th</sup> Grade</font></td>
			  <td><font size="3" face="Calibri">1.5</font></td>
			
			  <td><font size="3" face="Calibri">72</font></td></tr>
			<tr valign="top"><td><font size="3" face="Calibri">5<sup>th</sup> Grade</font></td>
			  <td><font size="3" face="Calibri">2</font></td>
			  <td><font size="3" face="Calibri">96</font></td></tr>
			<tr valign="top"><td><font size="3" face="Calibri">6<sup>th</sup> Grade</font></td>
			
			  <td><font size="3" face="Calibri">2.5</font></td>
			  <td><font size="3" face="Calibri">120</font></td></tr>
			<tr valign="top"><td><font size="3" face="Calibri">7<sup>th</sup> Grade</font></td>
			  <td><font size="3" face="Calibri">3</font></td>
			  <td><font size="3" face="Calibri">144</font></td></tr>
			
			<tr valign="top">
			  <td rowspan="4">&nbsp;</td>
			  <td><font size="3" face="Calibri">3.5</font></td>
			  <td><font size="3" face="Calibri">168</font></td></tr>
			<tr valign="top">
			  <td><font size="3" face="Calibri">4</font></td>
			  <td><font size="3" face="Calibri">192</font></td></tr>
			<tr valign="top">
			
			  <td><font size="3" face="Calibri">4.5</font></td>
			  <td><font size="3" face="Calibri">216</font></td></tr>
			<tr valign="top">
			  <td><font size="3" face="Calibri">5</font></td>
			  <td><font size="3" face="Calibri">240</font></td></tr>
			</table>
		</div>
	</body>
</html>